import { $Reader, $PrintStream, $InputStream, $DataOutputStream } from "@package/java/io";
import { $DebugLib, $PackageLib, $ResourceFinder, $BaseLib } from "@package/org/luaj/vm2/lib";
import { $Object, $Runnable, $Class } from "@package/java/lang";
export * as lib from "@package/org/luaj/vm2/lib";

declare module "@package/org/luaj/vm2" {
    export class $LuaThread extends $LuaValue {
        resume(arg0: $Varargs): $Varargs;
        getStatus(): string;
        isMainThread(): boolean;
        static ZERO: $LuaNumber;
        static ADD: $LuaString;
        globals: $Globals;
        static MODE: $LuaString;
        static LT: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TSTRING: number;
        state: $LuaThread$State;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MUL: $LuaString;
        static STATUS_SUSPENDED: number;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        callstack: $Object;
        static EQ: $LuaString;
        static METATABLE: $LuaString;
        static MAX_CALLSTACK: number;
        static TYPE_NAMES: string[];
        static STATUS_NAMES: string[];
        static POW: $LuaString;
        static STATUS_RUNNING: number;
        static TNIL: number;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        static CALL: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static TNONE: number;
        static STATUS_INITIAL: number;
        static TVALUE: number;
        static ENV: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TINT: number;
        errorfunc: $LuaValue;
        static STATUS_DEAD: number;
        static MOD: $LuaString;
        static thread_orphan_check_interval: number;
        static STATUS_NORMAL: number;
        static TNUMBER: number;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static coroutine_count: number;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static LE: $LuaString;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        constructor(arg0: $Globals);
        constructor(arg0: $Globals, arg1: $LuaValue);
        get status(): string;
        get mainThread(): boolean;
    }
    export class $Globals extends $LuaTable {
        load(arg0: string, arg1: string, arg2: $LuaTable): $LuaValue;
        load(arg0: $Reader, arg1: string): $LuaValue;
        load(arg0: $Reader, arg1: string, arg2: $LuaTable): $LuaValue;
        load(arg0: $InputStream, arg1: string, arg2: string, arg3: $LuaValue): $LuaValue;
        load(arg0: string): $LuaValue;
        load(arg0: string, arg1: string): $LuaValue;
        "yield"(arg0: $Varargs): $Varargs;
        loadfile(arg0: string): $LuaValue;
        loadPrototype(arg0: $InputStream, arg1: string, arg2: string): $Prototype;
        compilePrototype(arg0: $InputStream, arg1: string): $Prototype;
        compilePrototype(arg0: $Reader, arg1: string): $Prototype;
        static ZERO: $LuaNumber;
        static ADD: $LuaString;
        STDERR: $PrintStream;
        loader: $Globals$Loader;
        static MODE: $LuaString;
        static LT: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TSTRING: number;
        package_: $PackageLib;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        STDOUT: $PrintStream;
        static TRUE: $LuaBoolean;
        static EQ: $LuaString;
        finder: $ResourceFinder;
        static METATABLE: $LuaString;
        static TYPE_NAMES: string[];
        baselib: $BaseLib;
        static POW: $LuaString;
        static TNIL: number;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        static CALL: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static TNONE: number;
        static TVALUE: number;
        static ENV: $LuaString;
        static TTABLE: number;
        STDIN: $InputStream;
        running: $LuaThread;
        static UNM: $LuaString;
        compiler: $Globals$Compiler;
        static TINT: number;
        static MOD: $LuaString;
        undumper: $Globals$Undumper;
        static TNUMBER: number;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static LEN: $LuaString;
        debuglib: $DebugLib;
        static TUSERDATA: number;
        static LE: $LuaString;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        constructor();
    }
    export class $LuaThread$State implements $Runnable {
        run(): void;
        lua_yield(arg0: $Varargs): $Varargs;
        lua_resume(arg0: $LuaThread, arg1: $Varargs): $Varargs;
        hookrtrn: boolean;
        inhook: boolean;
        lastline: number;
        "function": $LuaValue;
        hookline: boolean;
        bytecodes: number;
        hookcall: boolean;
        hookfunc: $LuaValue;
        hookcount: number;
        status: number;
    }
    export class $LuaTable extends $LuaValue implements $Metatable {
        keyCount(): number;
        remove(arg0: number): $LuaValue;
        insert(arg0: number, arg1: $LuaValue): void;
        wrap(arg0: $LuaValue): $LuaValue;
        concat(arg0: $LuaString, arg1: number, arg2: number): $LuaValue;
        entry(arg0: $LuaValue, arg1: $LuaValue): $LuaTable$Slot;
        sort(arg0: $LuaValue): void;
        keys(): $LuaValue[];
        unpack(): $Varargs;
        unpack(arg0: number, arg1: number): $Varargs;
        unpack(arg0: number): $Varargs;
        presize(arg0: number, arg1: number): void;
        static hashSlot(arg0: $LuaValue, arg1: number): number;
        hashset(arg0: $LuaValue, arg1: $LuaValue): void;
        static hashmod(arg0: number, arg1: number): number;
        toLuaValue(): $LuaValue;
        static hashpow2(arg0: number, arg1: number): number;
        arrayget(arg0: $LuaValue[], arg1: number): $LuaValue;
        useWeakKeys(): boolean;
        useWeakValues(): boolean;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $Varargs, arg1: number);
        constructor(arg0: $Varargs);
        constructor();
        constructor(arg0: number, arg1: number);
        constructor(arg0: $LuaValue[], arg1: $LuaValue[], arg2: $Varargs);
    }
    export class $LuaString extends $LuaValue {
        static equals(arg0: number[], arg1: number, arg2: number[], arg3: number, arg4: number): boolean;
        static equals(arg0: $LuaString, arg1: number, arg2: $LuaString, arg3: number, arg4: number): boolean;
        static hashCode(arg0: number[], arg1: number, arg2: number): number;
        indexOf(arg0: $LuaString, arg1: number): number;
        indexOf(arg0: number, arg1: number): number;
        static valueOf(arg0: string[]): $LuaString;
        static valueOf(arg0: string[], arg1: number, arg2: number): $LuaString;
        charAt(arg0: number): number;
        lastIndexOf(arg0: $LuaString): number;
        substring(arg0: number, arg1: number): $LuaString;
        write(arg0: $DataOutputStream, arg1: number, arg2: number): void;
        copyInto(arg0: number, arg1: number[], arg2: number, arg3: number): void;
        toInputStream(): $InputStream;
        indexOfAny(arg0: $LuaString): number;
        tonumber(arg0: number): $LuaValue;
        scannumber(arg0: number): number;
        scannumber(): number;
        luaByte(arg0: number): number;
        static valueUsing(arg0: number[]): $LuaString;
        static valueUsing(arg0: number[], arg1: number, arg2: number): $LuaString;
        static encodeToUtf8(arg0: string[], arg1: number, arg2: number[], arg3: number): number;
        isValidUtf8(): boolean;
        static lengthAsUtf8(arg0: string[]): number;
        printToStream(arg0: $PrintStream): void;
        static decodeAsUtf8(arg0: number[], arg1: number, arg2: number): string;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        m_bytes: number[];
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        m_offset: number;
        static MOD: $LuaString;
        static MUL: $LuaString;
        m_length: number;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        get validUtf8(): boolean;
    }
    export class $LuaUserdata extends $LuaValue {
        userdata(): $Object;
        eqmt(arg0: $LuaValue): boolean;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        m_metatable: $LuaValue;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        m_instance: $Object;
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $Object);
        constructor(arg0: $Object, arg1: $LuaValue);
    }
    export class $LuaNumber extends $LuaValue {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
    }
    export class $LocVars {
        tojstring(): string;
        endpc: number;
        varname: $LuaString;
        startpc: number;
        constructor(arg0: $LuaString, arg1: number, arg2: number);
    }
    export class $Globals$Compiler {
    }
    export interface $Globals$Compiler {
        compile(arg0: $InputStream, arg1: string): $Prototype;
    }
    /**
     * Values that may be interpreted as {@link $Globals$Compiler}.
     */
    export type $Globals$Compiler_ = ((arg0: $InputStream, arg1: string) => $Prototype);
    export class $Varargs {
        type(arg0: number): number;
        arg(arg0: number): $LuaValue;
        narg(): number;
        arg1(): $LuaValue;
        "eval"(): $Varargs;
        isfunction(arg0: number): boolean;
        toint(arg0: number): number;
        isnil(arg0: number): boolean;
        tojstring(arg0: number): string;
        tojstring(): string;
        isthread(arg0: number): boolean;
        tofloat(arg0: number): number;
        tochar(arg0: number): string;
        isnumber(arg0: number): boolean;
        istable(arg0: number): boolean;
        toboolean(arg0: number): boolean;
        todouble(arg0: number): number;
        touserdata(arg0: number, arg1: $Class<any>): $Object;
        touserdata(arg0: number): $Object;
        toshort(arg0: number): number;
        isstring(arg0: number): boolean;
        tobyte(arg0: number): number;
        optboolean(arg0: number, arg1: boolean): boolean;
        tolong(arg0: number): number;
        optdouble(arg0: number, arg1: number): number;
        isuserdata(arg0: number): boolean;
        optclosure(arg0: number, arg1: $LuaClosure): $LuaClosure;
        optlong(arg0: number, arg1: number): number;
        checktable(arg0: number): $LuaTable;
        optnumber(arg0: number, arg1: $LuaNumber): $LuaNumber;
        optthread(arg0: number, arg1: $LuaThread): $LuaThread;
        optstring(arg0: number, arg1: $LuaString): $LuaString;
        opttable(arg0: number, arg1: $LuaTable): $LuaTable;
        optvalue(arg0: number, arg1: $LuaValue): $LuaValue;
        checkint(arg0: number): number;
        optinteger(arg0: number, arg1: $LuaInteger): $LuaInteger;
        optjstring(arg0: number, arg1: string): string;
        optint(arg0: number, arg1: number): number;
        checklong(arg0: number): number;
        checkvalue(arg0: number): $LuaValue;
        isTailcall(): boolean;
        subargs(arg0: number): $Varargs;
        isvalue(arg0: number): boolean;
        argcheck(arg0: boolean, arg1: number, arg2: string): void;
        dealias(): $Varargs;
        optuserdata(arg0: number, arg1: $Object): $Object;
        optuserdata(arg0: number, arg1: $Class<any>, arg2: $Object): $Object;
        checkfunction(arg0: number): $LuaFunction;
        checkinteger(arg0: number): $LuaInteger;
        checkstring(arg0: number): $LuaString;
        checkuserdata(arg0: number, arg1: $Class<any>): $Object;
        checkuserdata(arg0: number): $Object;
        checknotnil(arg0: number): $LuaValue;
        checkthread(arg0: number): $LuaThread;
        optfunction(arg0: number, arg1: $LuaFunction): $LuaFunction;
        checkdouble(arg0: number): number;
        checkboolean(arg0: number): boolean;
        checkjstring(arg0: number): string;
        checkclosure(arg0: number): $LuaClosure;
        checknumber(arg0: number): $LuaNumber;
        isnoneornil(arg0: number): boolean;
        constructor();
        get tailcall(): boolean;
    }
    export class $Globals$Loader {
    }
    export interface $Globals$Loader {
        load(arg0: $Prototype, arg1: string, arg2: $LuaValue): $LuaFunction;
    }
    /**
     * Values that may be interpreted as {@link $Globals$Loader}.
     */
    export type $Globals$Loader_ = ((arg0: $Prototype, arg1: string, arg2: $LuaValue) => $LuaFunction);
    export class $Metatable {
    }
    export interface $Metatable {
    }
    export class $LuaInteger extends $LuaNumber {
        static hashCode(arg0: number): number;
        static valueOf(arg0: number): $LuaNumber;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        v: number;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
    }
    export class $LuaBoolean extends $LuaValue {
        booleanValue(): boolean;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        v: boolean;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
    }
    export class $LuaTable$Slot {
    }
    export interface $LuaTable$Slot {
    }
    export class $LuaValue extends $Varargs {
        invoke(arg0: $LuaValue, arg1: $LuaValue, arg2: $Varargs): $Varargs;
        invoke(arg0: $LuaValue, arg1: $Varargs): $Varargs;
        invoke(arg0: $Varargs): $Varargs;
        invoke(): $Varargs;
        invoke(arg0: $LuaValue[]): $Varargs;
        invoke(arg0: $LuaValue[], arg1: $Varargs): $Varargs;
        get(arg0: number): $LuaValue;
        get(arg0: string): $LuaValue;
        get(arg0: $LuaValue): $LuaValue;
        type(): number;
        length(): number;
        method(arg0: string, arg1: $LuaValue): $LuaValue;
        method(arg0: $LuaValue): $LuaValue;
        method(arg0: $LuaValue, arg1: $LuaValue): $LuaValue;
        method(arg0: string, arg1: $LuaValue, arg2: $LuaValue): $LuaValue;
        method(arg0: $LuaValue, arg1: $LuaValue, arg2: $LuaValue): $LuaValue;
        method(arg0: string): $LuaValue;
        pow(arg0: number): $LuaValue;
        pow(arg0: $LuaValue): $LuaValue;
        pow(arg0: number): $LuaValue;
        load(arg0: $LuaValue): $LuaValue;
        static valueOf(arg0: string): $LuaString;
        static valueOf(arg0: number): $LuaInteger;
        static valueOf(arg0: boolean): $LuaBoolean;
        static valueOf(arg0: number[]): $LuaString;
        static valueOf(arg0: number): $LuaNumber;
        static valueOf(arg0: number[], arg1: number, arg2: number): $LuaString;
        add(arg0: number): $LuaValue;
        add(arg0: $LuaValue): $LuaValue;
        add(arg0: number): $LuaValue;
        next(arg0: $LuaValue): $Varargs;
        len(): $LuaValue;
        buffer(): $Buffer;
        concat(arg0: $LuaValue): $LuaValue;
        concat(arg0: $Buffer): $Buffer;
        set(arg0: string, arg1: number): void;
        set(arg0: string, arg1: $LuaValue): void;
        set(arg0: number, arg1: string): void;
        set(arg0: $LuaValue, arg1: $LuaValue): void;
        set(arg0: number, arg1: $LuaValue): void;
        set(arg0: string, arg1: string): void;
        set(arg0: string, arg1: number): void;
        call(arg0: string): $LuaValue;
        call(arg0: $LuaValue, arg1: $LuaValue): $LuaValue;
        call(arg0: $LuaValue, arg1: $LuaValue, arg2: $LuaValue): $LuaValue;
        call(arg0: $LuaValue): $LuaValue;
        call(): $LuaValue;
        mod(arg0: $LuaValue): $LuaValue;
        mod(arg0: number): $LuaValue;
        mod(arg0: number): $LuaValue;
        typename(): string;
        static error(arg0: string): $LuaValue;
        eq(arg0: $LuaValue): $LuaValue;
        lt(arg0: $LuaValue): $LuaValue;
        lt(arg0: number): $LuaValue;
        lt(arg0: number): $LuaValue;
        or(arg0: $LuaValue): $LuaValue;
        sub(arg0: number): $LuaValue;
        sub(arg0: number): $LuaValue;
        sub(arg0: $LuaValue): $LuaValue;
        and(arg0: $LuaValue): $LuaValue;
        not(): $LuaValue;
        div(arg0: number): $LuaValue;
        div(arg0: number): $LuaValue;
        div(arg0: $LuaValue): $LuaValue;
        neg(): $LuaValue;
        mul(arg0: number): $LuaValue;
        mul(arg0: $LuaValue): $LuaValue;
        mul(arg0: number): $LuaValue;
        gt(arg0: $LuaValue): $LuaValue;
        gt(arg0: number): $LuaValue;
        gt(arg0: number): $LuaValue;
        static listOf(arg0: $LuaValue[], arg1: $Varargs): $LuaTable;
        static listOf(arg0: $LuaValue[]): $LuaTable;
        isfunction(): boolean;
        isint(): boolean;
        toint(): number;
        isnil(): boolean;
        isinttype(): boolean;
        isthread(): boolean;
        tofloat(): number;
        tochar(): string;
        isnumber(): boolean;
        islong(): boolean;
        istable(): boolean;
        toboolean(): boolean;
        isclosure(): boolean;
        todouble(): number;
        touserdata(): $Object;
        touserdata(arg0: $Class<any>): $Object;
        tonumber(): $LuaValue;
        tostring(): $LuaValue;
        toshort(): number;
        isstring(): boolean;
        tobyte(): number;
        optboolean(arg0: boolean): boolean;
        tolong(): number;
        optdouble(arg0: number): number;
        isboolean(): boolean;
        isuserdata(arg0: $Class<any>): boolean;
        isuserdata(): boolean;
        optclosure(arg0: $LuaClosure): $LuaClosure;
        optlong(arg0: number): number;
        powWith(arg0: number): $LuaValue;
        powWith(arg0: number): $LuaValue;
        concatmt(arg0: $LuaValue): $LuaValue;
        checktable(): $LuaTable;
        optnumber(arg0: $LuaNumber): $LuaNumber;
        rawsetlist(arg0: number, arg1: $Varargs): void;
        rawlen(): number;
        inext(arg0: $LuaValue): $Varargs;
        optthread(arg0: $LuaThread): $LuaThread;
        optstring(arg0: $LuaString): $LuaString;
        static argerror(arg0: number, arg1: string): $LuaValue;
        isvalidkey(): boolean;
        rawget(arg0: string): $LuaValue;
        rawget(arg0: $LuaValue): $LuaValue;
        rawget(arg0: number): $LuaValue;
        rawset(arg0: string, arg1: $LuaValue): void;
        rawset(arg0: number, arg1: string): void;
        rawset(arg0: number, arg1: $LuaValue): void;
        rawset(arg0: $LuaValue, arg1: $LuaValue): void;
        rawset(arg0: string, arg1: string): void;
        rawset(arg0: string, arg1: number): void;
        rawset(arg0: string, arg1: number): void;
        presize(arg0: number): void;
        opttable(arg0: $LuaTable): $LuaTable;
        static eqmtcall(arg0: $LuaValue, arg1: $LuaValue, arg2: $LuaValue, arg3: $LuaValue): boolean;
        optvalue(arg0: $LuaValue): $LuaValue;
        divInto(arg0: number): $LuaValue;
        lteq(arg0: number): $LuaValue;
        lteq(arg0: number): $LuaValue;
        lteq(arg0: $LuaValue): $LuaValue;
        lteq_b(arg0: $LuaValue): boolean;
        lteq_b(arg0: number): boolean;
        lteq_b(arg0: number): boolean;
        gteq(arg0: $LuaValue): $LuaValue;
        gteq(arg0: number): $LuaValue;
        gteq(arg0: number): $LuaValue;
        gteq_b(arg0: $LuaValue): boolean;
        gteq_b(arg0: number): boolean;
        gteq_b(arg0: number): boolean;
        comparemt(arg0: $LuaValue, arg1: $LuaValue): $LuaValue;
        strcmp(arg0: $LuaString): number;
        strcmp(arg0: $LuaValue): number;
        testfor_b(arg0: $LuaValue, arg1: $LuaValue): boolean;
        strvalue(): $LuaString;
        checkint(): number;
        lt_b(arg0: $LuaValue): boolean;
        lt_b(arg0: number): boolean;
        lt_b(arg0: number): boolean;
        neq(arg0: $LuaValue): $LuaValue;
        subFrom(arg0: number): $LuaValue;
        subFrom(arg0: number): $LuaValue;
        optinteger(arg0: $LuaInteger): $LuaInteger;
        static userdataOf(arg0: $Object, arg1: $LuaValue): $LuaUserdata;
        static userdataOf(arg0: $Object): $LuaUserdata;
        static assert_(arg0: boolean, arg1: string): void;
        static tableOf(): $LuaTable;
        static tableOf(arg0: $LuaValue[]): $LuaTable;
        static tableOf(arg0: $LuaValue[], arg1: $LuaValue[], arg2: $Varargs): $LuaTable;
        static tableOf(arg0: $Varargs, arg1: number): $LuaTable;
        static tableOf(arg0: $LuaValue[], arg1: $LuaValue[]): $LuaTable;
        static tableOf(arg0: number, arg1: number): $LuaTable;
        modFrom(arg0: number): $LuaValue;
        gt_b(arg0: number): boolean;
        gt_b(arg0: $LuaValue): boolean;
        gt_b(arg0: number): boolean;
        metatag(arg0: $LuaValue): $LuaValue;
        optjstring(arg0: string): string;
        neq_b(arg0: $LuaValue): boolean;
        eq_b(arg0: $LuaValue): boolean;
        raweq(arg0: number): boolean;
        raweq(arg0: $LuaString): boolean;
        raweq(arg0: number): boolean;
        raweq(arg0: $LuaValue): boolean;
        raweq(arg0: $LuaUserdata): boolean;
        optint(arg0: number): number;
        concatTo(arg0: $LuaValue): $LuaValue;
        concatTo(arg0: $LuaNumber): $LuaValue;
        concatTo(arg0: $LuaString): $LuaValue;
        checklong(): number;
        onInvoke(arg0: $Varargs): $Varargs;
        static tailcallOf(arg0: $LuaValue, arg1: $Varargs): $Varargs;
        static varargsOf(arg0: $LuaValue[], arg1: $Varargs): $Varargs;
        static varargsOf(arg0: $LuaValue, arg1: $LuaValue, arg2: $Varargs): $Varargs;
        static varargsOf(arg0: $LuaValue[], arg1: number, arg2: number): $Varargs;
        static varargsOf(arg0: $LuaValue[], arg1: number, arg2: number, arg3: $Varargs): $Varargs;
        static varargsOf(arg0: $LuaValue, arg1: $Varargs): $Varargs;
        static varargsOf(arg0: $LuaValue[]): $Varargs;
        optuserdata(arg0: $Object): $Object;
        optuserdata(arg0: $Class<any>, arg1: $Object): $Object;
        setmetatable(arg0: $LuaValue): $LuaValue;
        checkfunction(): $LuaFunction;
        checkglobals(): $Globals;
        checkinteger(): $LuaInteger;
        checkstring(): $LuaString;
        checkuserdata(arg0: $Class<any>): $Object;
        checkuserdata(): $Object;
        checknotnil(): $LuaValue;
        getmetatable(): $LuaValue;
        checkthread(): $LuaThread;
        invokemethod(arg0: $LuaValue, arg1: $LuaValue[]): $Varargs;
        invokemethod(arg0: string, arg1: $Varargs): $Varargs;
        invokemethod(arg0: $LuaValue): $Varargs;
        invokemethod(arg0: string, arg1: $LuaValue[]): $Varargs;
        invokemethod(arg0: string): $Varargs;
        invokemethod(arg0: $LuaValue, arg1: $Varargs): $Varargs;
        optfunction(arg0: $LuaFunction): $LuaFunction;
        checkdouble(): number;
        checkboolean(): boolean;
        checkjstring(): string;
        initupvalue1(arg0: $LuaValue): void;
        checkclosure(): $LuaClosure;
        checknumber(): $LuaNumber;
        checknumber(arg0: string): $LuaNumber;
        strongvalue(): $LuaValue;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
        get function(): boolean;
        get int(): boolean;
        get nil(): boolean;
        get inttype(): boolean;
        get thread(): boolean;
        get number(): boolean;
        get long(): boolean;
        get table(): boolean;
        get closure(): boolean;
        get string(): boolean;
        get boolean(): boolean;
        get validkey(): boolean;
    }
    export class $UpValue {
        getValue(): $LuaValue;
        close(): void;
        setValue(arg0: $LuaValue): void;
        tojstring(): string;
        constructor(arg0: $LuaValue[], arg1: number);
    }
    export class $Globals$Undumper {
    }
    export interface $Globals$Undumper {
        undump(arg0: $InputStream, arg1: string): $Prototype;
    }
    /**
     * Values that may be interpreted as {@link $Globals$Undumper}.
     */
    export type $Globals$Undumper_ = ((arg0: $InputStream, arg1: string) => $Prototype);
    export class $LuaClosure extends $LuaFunction {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        p: $Prototype;
        upValues: $UpValue[];
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $Prototype, arg1: $LuaValue);
    }
    export class $Buffer {
        value(): $LuaValue;
        append(arg0: number): $Buffer;
        append(arg0: $LuaValue): $Buffer;
        append(arg0: $LuaString): $Buffer;
        append(arg0: string): $Buffer;
        prepend(arg0: $LuaString): $Buffer;
        tojstring(): string;
        tostring(): $LuaString;
        concatTo(arg0: $LuaNumber): $Buffer;
        concatTo(arg0: $LuaValue): $Buffer;
        concatTo(arg0: $LuaString): $Buffer;
        setvalue(arg0: $LuaValue): $Buffer;
        makeroom(arg0: number, arg1: number): void;
        constructor(arg0: $LuaValue);
        constructor(arg0: number);
        constructor();
    }
    export class $LuaFunction extends $LuaValue {
        name(): string;
        classnamestub(): string;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
    }
    export class $Prototype {
        shortsource(): string;
        getlocalname(arg0: number, arg1: number): $LuaString;
        p: $Prototype[];
        lineinfo: number[];
        maxstacksize: number;
        code: number[];
        upvalues: $Upvaldesc[];
        is_vararg: number;
        linedefined: number;
        locvars: $LocVars[];
        lastlinedefined: number;
        k: $LuaValue[];
        source: $LuaString;
        numparams: number;
        constructor();
        constructor(arg0: number);
    }
    export class $Upvaldesc {
        name: $LuaString;
        idx: number;
        instack: boolean;
        constructor(arg0: $LuaString, arg1: boolean, arg2: number);
    }
}
