import { $ShaderInstance } from "@package/net/minecraft/client/renderer";
import { $RenderCall_ } from "@package/com/mojang/blaze3d/pipeline";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $AutoStorageIndexBufferExtension } from "@package/foundry/veil/ext";
import { $GlStateManager$SourceFactor_, $GlStateManager$LogicOp_, $GlStateManager$DestFactor_ } from "@package/com/mojang/blaze3d/platform";
import { $ByteBuffer, $IntBuffer, $FloatBuffer } from "@package/java/nio";
import { $TimeSource$NanoTimeSource } from "@package/net/minecraft/util";
import { $RenderSystemAccessor } from "@package/net/createmod/ponder/mixin/client/accessor";
import { $Consumer_, $Supplier_ } from "@package/java/util/function";
import { $GlStateBackup } from "@package/net/neoforged/neoforge/client";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $Tesselator, $VertexFormat$IndexType, $VertexSorting, $VertexFormat$Mode_, $VertexSorting_ } from "@package/com/mojang/blaze3d/vertex";
import { $GLFWErrorCallbackI_ } from "@package/org/lwjgl/glfw";
import { $Runnable_ } from "@package/java/lang";
import { $FogShape_, $FogShape } from "@package/com/mojang/blaze3d/shaders";
import { $Matrix4fStack, $Matrix4f, $Vector3f } from "@package/org/joml";

declare module "@package/com/mojang/blaze3d/systems" {
    export class $RenderSystem$AutoStorageIndexBuffer$IndexGenerator {
    }
    export interface $RenderSystem$AutoStorageIndexBuffer$IndexGenerator {
    }
    /**
     * Values that may be interpreted as {@link $RenderSystem$AutoStorageIndexBuffer$IndexGenerator}.
     */
    export type $RenderSystem$AutoStorageIndexBuffer$IndexGenerator_ = (() => void);
    export class $RenderSystem$AutoStorageIndexBuffer implements $AutoStorageIndexBufferExtension {
        type(): $VertexFormat$IndexType;
        bind(arg0: number): void;
        hasStorage(arg0: number): boolean;
        handler$bjm000$veil$nameBuffer(arg0: $CallbackInfo): void;
        veil$getBuffer(): number;
        veil$ensureStorage(arg0: number): void;
    }
    export class $RenderSystem implements $RenderSystemAccessor {
        static clear(arg0: number, arg1: boolean): void;
        static getString(arg0: number, arg1: $Consumer_<string>): void;
        static setupGuiFlatDiffuseLighting(arg0: $Vector3f, arg1: $Vector3f): void;
        static glBindVertexArray(arg0: number): void;
        static glDeleteVertexArrays(arg0: number): void;
        static glBindBuffer(arg0: number, arg1: number): void;
        static glDeleteBuffers(arg0: number): void;
        static glBufferData(arg0: number, arg1: $ByteBuffer, arg2: number): void;
        static glGenBuffers(arg0: $Consumer_<number>): void;
        static glUniform1i(arg0: number, arg1: number): void;
        static glGenVertexArrays(arg0: $Consumer_<number>): void;
        static beginInitialization(): void;
        static finishInitialization(): void;
        static getBackendDescription(): string;
        static setShaderGlintAlpha(arg0: number): void;
        static setShaderGlintAlpha(arg0: number): void;
        static applyModelViewMatrix(): void;
        static depthFunc(arg0: number): void;
        static colorMask(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean): void;
        static flipFrame(arg0: number): void;
        static clearColor(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static clearDepth(arg0: number): void;
        static stencilOp(arg0: number, arg1: number, arg2: number): void;
        static glUniform1(arg0: number, arg1: $FloatBuffer): void;
        static glUniform1(arg0: number, arg1: $IntBuffer): void;
        static glUniform2(arg0: number, arg1: $IntBuffer): void;
        static glUniform2(arg0: number, arg1: $FloatBuffer): void;
        static glUniform3(arg0: number, arg1: $FloatBuffer): void;
        static glUniform3(arg0: number, arg1: $IntBuffer): void;
        static glUniform4(arg0: number, arg1: $IntBuffer): void;
        static glUniform4(arg0: number, arg1: $FloatBuffer): void;
        /**
         * @deprecated
         */
        static runAsFancy(arg0: $Runnable_): void;
        static setShader(arg0: $Supplier_<$ShaderInstance>): void;
        static blendFunc(arg0: number, arg1: number): void;
        static blendFunc(arg0: $GlStateManager$SourceFactor_, arg1: $GlStateManager$DestFactor_): void;
        static depthMask(arg0: boolean): void;
        static getShaderGlintAlpha(): number;
        static maxSupportedTextureSize(): number;
        static teardownOverlayColor(): void;
        static bindTextureForSetup(arg0: number): void;
        static isFrozenAtPollEvents(): boolean;
        static setupGui3DDiffuseLighting(arg0: $Vector3f, arg1: $Vector3f): void;
        static getSequentialBuffer(arg0: $VertexFormat$Mode_): $RenderSystem$AutoStorageIndexBuffer;
        static setupLevelDiffuseLighting(arg0: $Vector3f, arg1: $Vector3f): void;
        static restoreProjectionMatrix(): void;
        static renderThreadTesselator(): $Tesselator;
        static backupProjectionMatrix(): void;
        static assertOnRenderThreadOrInit(): void;
        static isOnRenderThreadOrInit(): boolean;
        static setProjectionMatrix(arg0: $Matrix4f, arg1: $VertexSorting_): void;
        static lineWidth(arg0: number): void;
        static getModelViewStack(): $Matrix4fStack;
        static getApiDescription(): string;
        static getCapsString(): string;
        static initBackendSystem(): $TimeSource$NanoTimeSource;
        static setupDefaultState(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static initRenderer(arg0: number, arg1: boolean): void;
        static setErrorCallback(arg0: $GLFWErrorCallbackI_): void;
        static limitDisplayFPS(arg0: number): void;
        static catnip$getShaderLightDirections$ponder_$md$9aa1a5$2(): $Vector3f[];
        static logicOp(arg0: $GlStateManager$LogicOp_): void;
        static getShader(): $ShaderInstance;
        static disableBlend(): void;
        static setShaderTexture(arg0: number, arg1: $ResourceLocation_): void;
        static setShaderTexture(arg0: number, arg1: number): void;
        static enableBlend(): void;
        static disableCull(): void;
        static defaultBlendFunc(): void;
        static getModelViewMatrix(): $Matrix4f;
        static setShaderColor(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static enableDepthTest(): void;
        static disableDepthTest(): void;
        static isOnRenderThread(): boolean;
        static recordRenderCall(arg0: $RenderCall_): void;
        static enableScissor(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static disableScissor(): void;
        static enableCull(): void;
        static pixelStore(arg0: number, arg1: number): void;
        static readPixels(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: $ByteBuffer): void;
        static viewport(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static enablePolygonOffset(): void;
        static disableColorLogicOp(): void;
        static disablePolygonOffset(): void;
        static assertOnRenderThread(): void;
        static getProjectionMatrix(): $Matrix4f;
        static initRenderThread(): void;
        static blendFuncSeparate(arg0: $GlStateManager$SourceFactor_, arg1: $GlStateManager$DestFactor_, arg2: $GlStateManager$SourceFactor_, arg3: $GlStateManager$DestFactor_): void;
        static blendFuncSeparate(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static polygonOffset(arg0: number, arg1: number): void;
        static setTextureMatrix(arg0: $Matrix4f): void;
        static resetTextureMatrix(): void;
        static enableColorLogicOp(): void;
        static getShaderFogStart(): number;
        static activeTexture(arg0: number): void;
        static bindTexture(arg0: number): void;
        static setupShaderLights(arg0: $ShaderInstance): void;
        static getShaderTexture(arg0: number): number;
        static getShaderGameTime(): number;
        static getTextureMatrix(): $Matrix4f;
        static getShaderFogColor(): number[];
        static getShaderLineWidth(): number;
        static getShaderFogEnd(): number;
        static getShaderColor(): number[];
        static getShaderFogShape(): $FogShape;
        static setupOverlayColor(arg0: number, arg1: number): void;
        static setShaderFogStart(arg0: number): void;
        static blendEquation(arg0: number): void;
        static setShaderLights(arg0: $Vector3f, arg1: $Vector3f): void;
        static stencilMask(arg0: number): void;
        static drawElements(arg0: number, arg1: number, arg2: number): void;
        static polygonMode(arg0: number, arg1: number): void;
        static texParameter(arg0: number, arg1: number, arg2: number): void;
        static deleteTexture(arg0: number): void;
        static stencilFunc(arg0: number, arg1: number, arg2: number): void;
        static replayQueue(): void;
        static setShaderFogColor(arg0: number, arg1: number, arg2: number): void;
        static setShaderFogColor(arg0: number, arg1: number, arg2: number, arg3: number): void;
        static setShaderFogEnd(arg0: number): void;
        static setShaderFogShape(arg0: $FogShape_): void;
        static clearStencil(arg0: number): void;
        static renderCrosshair(arg0: number): void;
        static setShaderGameTime(arg0: number, arg1: number): void;
        static _setShaderTexture(arg0: number, arg1: number): void;
        static _setShaderTexture(arg0: number, arg1: $ResourceLocation_): void;
        static glUniformMatrix2(arg0: number, arg1: boolean, arg2: $FloatBuffer): void;
        static restoreGlState(arg0: $GlStateBackup): void;
        static glUniformMatrix4(arg0: number, arg1: boolean, arg2: $FloatBuffer): void;
        static glUniformMatrix3(arg0: number, arg1: boolean, arg2: $FloatBuffer): void;
        static getVertexSorting(): $VertexSorting;
        static backupGlState(arg0: $GlStateBackup): void;
        static savedProjectionMatrix: $Matrix4f;
        static shaderTextures: number[];
        static modelViewStack: $Matrix4fStack;
        static modelViewMatrix: $Matrix4f;
        static savedVertexSorting: $VertexSorting;
        static shaderLightDirections: $Vector3f[];
        static shaderGameTime: number;
        constructor();
        static get backendDescription(): string;
        static get frozenAtPollEvents(): boolean;
        static get onRenderThreadOrInit(): boolean;
        static get apiDescription(): string;
        static get capsString(): string;
        static set errorCallback(value: $GLFWErrorCallbackI_);
        static get onRenderThread(): boolean;
        static set upShaderLights(value: $ShaderInstance);
        static get shaderLineWidth(): number;
        static get vertexSorting(): $VertexSorting;
    }
}
