import { $InputStream } from "@package/java/io";
import { $LuaValue, $LuaString, $Varargs, $LuaClosure, $LuaBoolean, $Prototype, $LuaFunction, $LuaNumber, $LuaTable } from "@package/org/luaj/vm2";

declare module "@package/org/luaj/vm2/lib" {
    export class $DebugLib extends $TwoArgFunction {
        traceback(arg0: number): string;
        onCall(arg0: $LuaFunction): void;
        onCall(arg0: $LuaClosure, arg1: $Varargs, arg2: $LuaValue[]): void;
        onReturn(): void;
        static getobjname(arg0: $Prototype, arg1: number, arg2: number): $DebugLib$NameWhat;
        getCallFrame(arg0: number): $DebugLib$CallFrame;
        onInstruction(arg0: number, arg1: $Varargs, arg2: number): void;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TRACE: boolean;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static CALLS: boolean;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
    }
    export class $PackageLib$lua_searcher extends $VarArgFunction {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $PackageLib);
    }
    export class $PackageLib$preload_searcher extends $VarArgFunction {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $PackageLib);
    }
    export class $TwoArgFunction extends $LibFunction {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
    }
    export class $DebugLib$NameWhat {
    }
    export class $BaseLib extends $TwoArgFunction implements $ResourceFinder {
        findResource(arg0: string): $InputStream;
        loadStream(arg0: $InputStream, arg1: string, arg2: string, arg3: $LuaValue): $Varargs;
        loadFile(arg0: string, arg1: string, arg2: $LuaValue): $Varargs;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
    }
    export class $PackageLib extends $TwoArgFunction {
        setLuaPath(arg0: string): void;
        static toClassname(arg0: string): string;
        setIsLoaded(arg0: string, arg1: $LuaTable): void;
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        preload_searcher: $PackageLib$preload_searcher;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static DEFAULT_LUA_PATH: string;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        lua_searcher: $PackageLib$lua_searcher;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        java_searcher: $PackageLib$java_searcher;
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor();
        set luaPath(value: string);
    }
    export class $PackageLib$java_searcher extends $VarArgFunction {
        static ZERO: $LuaNumber;
        static CALL: $LuaString;
        static ADD: $LuaString;
        static TFUNCTION: number;
        static CONCAT: $LuaString;
        static ONE: $LuaNumber;
        static MODE: $LuaString;
        static TNONE: number;
        static LT: $LuaString;
        static TVALUE: number;
        static ENV: $LuaString;
        static EMPTYSTRING: $LuaString;
        static TTABLE: number;
        static UNM: $LuaString;
        static TSTRING: number;
        static INDEX: $LuaString;
        static TOSTRING: $LuaString;
        static TINT: number;
        static NONE: $LuaValue;
        static TTHREAD: number;
        static SUB: $LuaString;
        static MOD: $LuaString;
        static MUL: $LuaString;
        static MINUSONE: $LuaNumber;
        static NILS: $LuaValue[];
        static NOVALS: $LuaValue[];
        static TRUE: $LuaBoolean;
        static TNUMBER: number;
        static EQ: $LuaString;
        static NIL: $LuaValue;
        static DIV: $LuaString;
        static METATABLE: $LuaString;
        static LEN: $LuaString;
        static TUSERDATA: number;
        static TYPE_NAMES: string[];
        static POW: $LuaString;
        static LE: $LuaString;
        static TNIL: number;
        static FALSE: $LuaBoolean;
        static NEWINDEX: $LuaString;
        static s_metatable: $LuaValue;
        static TBOOLEAN: number;
        static TLIGHTUSERDATA: number;
        constructor(arg0: $PackageLib);
    }
    export class $DebugLib$CallFrame {
        shortsource(): string;
        currentline(): number;
        constructor();
    }
    export class $ResourceFinder {
    }
    export interface $ResourceFinder {
        findResource(arg0: string): $InputStream;
    }
    /**
     * Values that may be interpreted as {@link $ResourceFinder}.
     */
    export type $ResourceFinder_ = ((arg0: string) => $InputStream);
}
