import { $IAcceleratedRenderer_, $IBufferDecorator } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated/renderers";
import { $IMemoryLayout, $IMemoryInterface } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/memory";
import { $RenderType } from "@package/net/minecraft/client/renderer";
import { $BakedQuad } from "@package/net/minecraft/client/renderer/block/model";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $NativeImage } from "@package/com/mojang/blaze3d/platform";
import { $Map } from "@package/java/util";
import { $ByteBuffer } from "@package/java/nio";
import { $ILayerFunction } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated/layers/functions";
import { $ICullingProgramDispatcher } from "@package/com/github/argon4w/acceleratedrendering/core/programs/culling";
import { $ElementBufferPool$ElementSegment, $StagingBufferPool$StagingBuffer } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated/pools";
import { $IIrisAcceleratedBufferBuilder } from "@package/com/github/argon4w/acceleratedrendering/compat/iris/interfaces";
import { $LongSupplier } from "@package/java/util/function";
import { $MeshUploaderPool$MeshUploader } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated/pools/meshes";
import { $VertexFormatElement, $VertexConsumer, $VertexFormatElement_, $VertexFormat$Mode, $PoseStack$Pose } from "@package/com/mojang/blaze3d/vertex";
import { $AcceleratedRingBuffers$Buffers } from "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated";
import { $IPolygonProgramDispatcher } from "@package/com/github/argon4w/acceleratedrendering/core/programs/dispatchers";
import { $ServerMesh_, $ServerMesh } from "@package/com/github/argon4w/acceleratedrendering/core/meshes";
import { $ITransformShaderProgramOverride, $IUploadingShaderProgramOverride } from "@package/com/github/argon4w/acceleratedrendering/core/programs/overrides";
import { $Matrix3f, $Matrix4f, $Vector3f } from "@package/org/joml";

declare module "@package/com/github/argon4w/acceleratedrendering/core/buffers/accelerated/builders" {
    export class $IBufferGraph {
    }
    export interface $IBufferGraph {
    }
    export class $IAcceleratedVertexConsumer {
    }
    export interface $IAcceleratedVertexConsumer extends $IBufferDecorator, $IBufferGraph {
        getLayout(): $IMemoryLayout<$VertexFormatElement>;
        decorate(arg0: $VertexConsumer): $VertexConsumer;
        isAccelerated(): boolean;
        getRenderType(): $RenderType;
        endTransform(): void;
        downloadTexture(): $NativeImage;
        getPolygonSize(): number;
        addClientMesh(arg0: $ByteBuffer, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addServerMesh(arg0: $ServerMesh_, arg1: number, arg2: number, arg3: number): void;
        beginTransform(arg0: $Matrix4f, arg1: $Matrix3f): void;
        doRender<T>(arg0: $IAcceleratedRenderer_<T>, arg1: T, arg2: $Matrix4f, arg3: $Matrix3f, arg4: number, arg5: number, arg6: number): void;
        get layout(): $IMemoryLayout<$VertexFormatElement>;
        get accelerated(): boolean;
        get renderType(): $RenderType;
        get polygonSize(): number;
    }
    export class $AcceleratedBufferBuilder implements $IAcceleratedVertexConsumer, $VertexConsumer, $LongSupplier, $IIrisAcceleratedBufferBuilder {
        isEmpty(): boolean;
        getFunction(): $ILayerFunction;
        getAsLong(): number;
        setColor(arg0: number, arg1: number, arg2: number, arg3: number): $VertexConsumer;
        getBuffer(): $AcceleratedRingBuffers$Buffers;
        getMode(): $VertexFormat$Mode;
        getLayout(): $IMemoryLayout<$VertexFormatElement>;
        setOutdated(): void;
        decorate(arg0: $VertexConsumer): $VertexConsumer;
        setUv(arg0: number, arg1: number): $VertexConsumer;
        addVertex(arg0: number, arg1: number, arg2: number): $VertexConsumer;
        addVertex(arg0: $PoseStack$Pose, arg1: number, arg2: number, arg3: number): $VertexConsumer;
        addVertex(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number): void;
        handler$cgj000$acceleratedrendering$addIrisMesh(arg0: $CallbackInfo, arg1: number): void;
        handler$cgj000$acceleratedrendering$constructor(arg0: $StagingBufferPool$StagingBuffer, arg1: $StagingBufferPool$StagingBuffer, arg2: $ElementBufferPool$ElementSegment, arg3: $AcceleratedRingBuffers$Buffers, arg4: $ILayerFunction, arg5: $RenderType, arg6: $CallbackInfo): void;
        handler$cgj000$acceleratedrendering$addIrisVertex(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: $CallbackInfo, arg12: number): void;
        handler$cgj000$acceleratedrendering$addIrisVertex(arg0: number, arg1: number, arg2: number, arg3: $CallbackInfoReturnable<any>): void;
        isOutdated(): boolean;
        getCullingProgramDispatcher(): $ICullingProgramDispatcher;
        getPolygonProgramDispatcher(): $IPolygonProgramDispatcher;
        getVertexCount(): number;
        isAccelerated(): boolean;
        getVertexSize(): number;
        getRenderType(): $RenderType;
        endTransform(): void;
        getPolygonSize(): number;
        addClientMesh(arg0: $ByteBuffer, arg1: number, arg2: number, arg3: number, arg4: number): void;
        addServerMesh(arg0: $ServerMesh_, arg1: number, arg2: number, arg3: number): void;
        beginTransform(arg0: $Matrix4f, arg1: $Matrix3f): void;
        setUv2(arg0: number, arg1: number): $VertexConsumer;
        setNormal(arg0: $PoseStack$Pose, arg1: number, arg2: number, arg3: number): $VertexConsumer;
        setNormal(arg0: number, arg1: number, arg2: number): $VertexConsumer;
        setUv1(arg0: number, arg1: number): $VertexConsumer;
        doRender<T>(arg0: $IAcceleratedRenderer_<T>, arg1: T, arg2: $Matrix4f, arg3: $Matrix3f, arg4: number, arg5: number, arg6: number): void;
        getVertexBuffer(): $StagingBufferPool$StagingBuffer;
        getVaryingSize(): number;
        getVaryingBuffer(): $StagingBufferPool$StagingBuffer;
        getElementSegment(): $ElementBufferPool$ElementSegment;
        getEntityIdOffset(): $IMemoryInterface;
        getUv2Offset(): $IMemoryInterface;
        getVaryingOffset(): $IMemoryInterface;
        getMeshUploaders(): $Map<$ServerMesh, $MeshUploaderPool$MeshUploader>;
        getVaryingSharing(): $IMemoryInterface;
        getColorOffset(): $IMemoryInterface;
        getVaryingMesh(): $IMemoryInterface;
        getMeshVertexCount(): number;
        getUv1Offset(): $IMemoryInterface;
        getTransformOverride(): $ITransformShaderProgramOverride;
        getUploadingOverride(): $IUploadingShaderProgramOverride;
        getVaryingShouldCull(): $IMemoryInterface;
        getTotalVertexCount(): number;
        getPolygonElementCount(): number;
        getEntityOffset(): $IMemoryInterface;
        downloadTexture(): $NativeImage;
        setColor(arg0: number, arg1: number, arg2: number, arg3: number): $VertexConsumer;
        setColor(arg0: number): $VertexConsumer;
        addVertex(arg0: $Vector3f): $VertexConsumer;
        addVertex(arg0: $PoseStack$Pose, arg1: $Vector3f): $VertexConsumer;
        addVertex(arg0: $Matrix4f, arg1: number, arg2: number, arg3: number): $VertexConsumer;
        setOverlay(arg0: number): $VertexConsumer;
        putBulkData(arg0: $PoseStack$Pose, arg1: $BakedQuad, arg2: number[], arg3: number, arg4: number, arg5: number, arg6: number, arg7: number[], arg8: number, arg9: boolean): void;
        putBulkData(arg0: $PoseStack$Pose, arg1: $BakedQuad, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): void;
        setWhiteAlpha(arg0: number): $VertexConsumer;
        setLight(arg0: number): $VertexConsumer;
        applyBakedNormals(arg0: $Vector3f, arg1: $ByteBuffer, arg2: $Matrix3f): void;
        applyBakedLighting(arg0: number, arg1: $ByteBuffer): number;
        putBulkData(arg0: $PoseStack$Pose, arg1: $BakedQuad, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: boolean): void;
        misc(arg0: $VertexFormatElement_, ...arg1: number[]): $VertexConsumer;
        varyingOffset: $IMemoryInterface;
        varyingSharing: $IMemoryInterface;
        varyingShouldCull: $IMemoryInterface;
        varyingMesh: $IMemoryInterface;
        static SHARING_SIZE: number;
        static SHARING_TRANSFORM: $IMemoryInterface;
        static SHARING_NORMAL: $IMemoryInterface;
        constructor(arg0: $StagingBufferPool$StagingBuffer, arg1: $StagingBufferPool$StagingBuffer, arg2: $ElementBufferPool$ElementSegment, arg3: $AcceleratedRingBuffers$Buffers, arg4: $ILayerFunction, arg5: $RenderType);
        get empty(): boolean;
        get function(): $ILayerFunction;
        get asLong(): number;
        get buffer(): $AcceleratedRingBuffers$Buffers;
        get mode(): $VertexFormat$Mode;
        get layout(): $IMemoryLayout<$VertexFormatElement>;
        get cullingProgramDispatcher(): $ICullingProgramDispatcher;
        get polygonProgramDispatcher(): $IPolygonProgramDispatcher;
        get vertexCount(): number;
        get accelerated(): boolean;
        get vertexSize(): number;
        get renderType(): $RenderType;
        get polygonSize(): number;
        get vertexBuffer(): $StagingBufferPool$StagingBuffer;
        get varyingSize(): number;
        get varyingBuffer(): $StagingBufferPool$StagingBuffer;
        get elementSegment(): $ElementBufferPool$ElementSegment;
        get entityIdOffset(): $IMemoryInterface;
        get uv2Offset(): $IMemoryInterface;
        get meshUploaders(): $Map<$ServerMesh, $MeshUploaderPool$MeshUploader>;
        get colorOffset(): $IMemoryInterface;
        get meshVertexCount(): number;
        get uv1Offset(): $IMemoryInterface;
        get transformOverride(): $ITransformShaderProgramOverride;
        get uploadingOverride(): $IUploadingShaderProgramOverride;
        get totalVertexCount(): number;
        get polygonElementCount(): number;
        get entityOffset(): $IMemoryInterface;
        set overlay(value: number);
        set whiteAlpha(value: number);
        set light(value: number);
    }
}
