import { $File, $File_ } from "@package/java/io";
import { $Codec } from "@package/com/mojang/serialization";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Pair } from "@package/com/mojang/datafixers/util";
import { $Component } from "@package/net/minecraft/network/chat";
import { $IGuiTexture, $IGuiTexture_ } from "@package/com/lowdragmc/lowdraglib2/gui/texture";
import { $InspectorView, $HistoryView, $ResourceView } from "@package/com/lowdragmc/lowdraglib2/editor/ui/view";
import { $IProject } from "@package/com/lowdragmc/lowdraglib2/editor/project";
import { $TreeNode, $TreeBuilder$Menu } from "@package/com/lowdragmc/lowdraglib2/gui/util";
import { $List, $LinkedHashMap, $Map_, $List_, $Map } from "@package/java/util";
import { $EditorSettings } from "@package/com/lowdragmc/lowdraglib2/editor/settings";
import { $UIElementProvider_ } from "@package/com/lowdragmc/lowdraglib2/gui/ui/utils";
import { $Tab, $SplitView, $Button, $Menu, $TabView } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements";
import { $Supplier_, $Consumer_, $Supplier } from "@package/java/util/function";
import { $YogaEdge_ } from "@package/org/appliedenergistics/yoga";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Style, $UIElement } from "@package/com/lowdragmc/lowdraglib2/gui/ui";
import { $Layout } from "@package/dev/vfyjxf/taffy/tree";
import { $ViewMenu, $FileMenu } from "@package/com/lowdragmc/lowdraglib2/editor/ui/menu";
import { $Record, $Runnable_ } from "@package/java/lang";
export * as menu from "@package/com/lowdragmc/lowdraglib2/editor/ui/menu";
export * as view from "@package/com/lowdragmc/lowdraglib2/editor/ui/view";
export * as resource from "@package/com/lowdragmc/lowdraglib2/editor/ui/resource";

declare module "@package/com/lowdragmc/lowdraglib2/editor/ui" {
    export class $SplittableWindow$LayoutConfig extends $Record {
        first(): $SplittableWindow$LayoutConfig;
        second(): $SplittableWindow$LayoutConfig;
        serialize(): $CompoundTag;
        static deserialize(arg0: $CompoundTag_): $SplittableWindow$LayoutConfig;
        percentage(): number;
        anchorId(): string;
        vertical(): boolean;
        constructor(anchorId: string, vertical: boolean, percentage: number, first: $SplittableWindow$LayoutConfig_, second: $SplittableWindow$LayoutConfig_);
    }
    export class $EditorLayout extends $Record {
        slots(): $List<$EditorLayout$SlotEntry>;
        serialize(): $CompoundTag;
        static deserialize(arg0: $CompoundTag_): $EditorLayout;
        layoutConfig(): $SplittableWindow$LayoutConfig;
        findSlotForView(arg0: string): $EditorLayout$SlotEntry;
        constructor(layoutConfig: $SplittableWindow$LayoutConfig_, slots: $List_<$EditorLayout$SlotEntry_>);
    }
    export class $View extends $UIElement {
        getName(): string;
        setName(arg0: string): void;
        getIcon(): $IGuiTexture;
        setCanRemove(arg0: boolean): void;
        setIcon(arg0: $IGuiTexture_): void;
        getViewContainer(): $ViewContainer;
        isCanRemove(): boolean;
        setOnRemove(arg0: $Runnable_): void;
        setDynamicName(arg0: $Supplier_<$Component>): void;
        createTab(): $Tab;
        static CODEC: $Codec<$UIElement>;
        static EMPTY_LAYOUT: $Layout;
        constructor();
        constructor(arg0: string, arg1: $IGuiTexture_);
        constructor(arg0: string);
        get viewContainer(): $ViewContainer;
        set onRemove(value: $Runnable_);
        set dynamicName(value: $Supplier_<$Component>);
    }
    export class $ViewContainer extends $UIElement {
        expand(): void;
        selectView(arg0: $View): void;
        getWindow(): $SplittableWindow;
        addView(arg0: $View): $ViewContainer;
        removeView(arg0: $View): void;
        isCollapse(): boolean;
        collapse(): void;
        getAllViews(): $List<$View>;
        isViewSelected(arg0: $View): boolean;
        isEmptyWindow(): boolean;
        hasView(arg0: $View): boolean;
        addViewAt(arg0: $View, arg1: number): $ViewContainer;
        addViews(...arg0: $View[]): $ViewContainer;
        buttonIcon: $UIElement;
        static CODEC: $Codec<$UIElement>;
        collapseButton: $Button;
        static EMPTY_LAYOUT: $Layout;
        tabView: $TabView;
        constructor();
        get window(): $SplittableWindow;
        get allViews(): $List<$View>;
        get emptyWindow(): boolean;
    }
    export class $EditorWindow extends $UIElement {
        static open(arg0: $ResourceLocation_, arg1: $Supplier_<$Editor>): $EditorWindow;
        static openDefault(arg0: $Supplier_<$Editor>): $EditorWindow;
        closeWindow(): void;
        createNewEditor(arg0: $Supplier_<$Editor>): $Editor;
        removeEditor(arg0: $Editor): void;
        hasMultipleEditors(): boolean;
        retoreWindow(): void;
        maximizeWindow(): void;
        isMaximized(): boolean;
        minimizeWindow(): void;
        getCurrentEditor(): $Editor;
        showEditor(arg0: $Editor): void;
        getEditors(): $LinkedHashMap<$Editor, $UIElement>;
        editorButtonContainer: $UIElement;
        static CODEC: $Codec<$UIElement>;
        static DEFAULT_ID: $ResourceLocation;
        editorContainer: $UIElement;
        static EMPTY_LAYOUT: $Layout;
        window: $UIElement;
        windowID: $ResourceLocation;
        constructor(arg0: $Supplier_<$Editor>);
        constructor(arg0: $ResourceLocation_, arg1: $Supplier_<$Editor>);
        get maximized(): boolean;
        get currentEditor(): $Editor;
        get editors(): $LinkedHashMap<$Editor, $UIElement>;
    }
    export class $EditorLayout$SlotEntry extends $Record {
        path(): string;
        serialize(): $CompoundTag;
        static deserialize(arg0: $CompoundTag_): $EditorLayout$SlotEntry;
        viewNames(): $List<string>;
        selectedViewName(): string;
        constructor(path: string, viewNames: $List_<string>, selectedViewName: string);
    }
    export class $Editor extends $UIElement {
        exit(): void;
        exit(arg0: $Runnable_): void;
        close(): void;
        getTitle(): $Component;
        closeCurrentProject(arg0: boolean, arg1: $Runnable_): void;
        isCurrentProjectDirty(): boolean;
        getCurrentProjectFile(): $File;
        getIcon(): $UIElement;
        openMenu<T, C>(arg0: number, arg1: number, arg2: $TreeNode<T, C>, arg3: $UIElementProvider_<T>): $Menu<T, C>;
        openMenu(arg0: number, arg1: number, arg2: $TreeBuilder$Menu): void;
        placeView(arg0: $View, arg1: $Supplier_<$ViewContainer>): void;
        getMenuContainer(): $UIElement;
        getWindow(): $EditorWindow;
        getTop(): $UIElement;
        getAllViews(): $List<$View>;
        askToSaveProject(arg0: $Runnable_): void;
        getCloseButton(): $Button;
        static emptyEditor(): $Editor;
        getBottomWindow(): $SplittableWindow;
        captureLayout(): $EditorLayout;
        getTopPlaceholder(): $UIElement;
        getMainView(): $UIElement;
        getCurrentProject(): $IProject;
        saveAsProject(arg0: $Runnable_): void;
        saveAsProject(arg0: $File_, arg1: $Runnable_): void;
        getButtonContainer(): $UIElement;
        getLeftWindow(): $SplittableWindow;
        getViewFallbacks(): $Map<$View, $Supplier<$ViewContainer>>;
        getResourceView(): $ResourceView;
        getCenterWindow(): $SplittableWindow;
        getViewMenu(): $ViewMenu;
        loadProject(arg0: $IProject, arg1: $File_): void;
        getRightWindow(): $SplittableWindow;
        getHistoryView(): $HistoryView;
        getEditorSettings(): $EditorSettings;
        saveProject(arg0: $Runnable_, arg1: boolean): void;
        saveProject(arg0: $Runnable_): void;
        openSettingsPanel(): void;
        getRootWindow(): $SplittableWindow;
        getSavedLayout(): $EditorLayout;
        getInspectorView(): $InspectorView;
        getFileMenu(): $FileMenu;
        applyLayout(arg0: $EditorLayout_): void;
        static ANCHOR_CENTER: string;
        static ANCHOR_BOTTOM: string;
        resourceView: $ResourceView;
        static EMPTY_LAYOUT: $Layout;
        topPlaceholder: $UIElement;
        icon: $UIElement;
        menuContainer: $UIElement;
        buttonContainer: $UIElement;
        inspectorView: $InspectorView;
        static ANCHOR_RIGHT: string;
        rightWindow: $SplittableWindow;
        top: $UIElement;
        closeButton: $Button;
        static ANCHOR_LEFT: string;
        fileMenu: $FileMenu;
        leftWindow: $SplittableWindow;
        static CODEC: $Codec<$UIElement>;
        historyView: $HistoryView;
        static ANCHOR_ROOT: string;
        viewMenu: $ViewMenu;
        centerWindow: $SplittableWindow;
        editorSettings: $EditorSettings;
        rootWindow: $SplittableWindow;
        bottomWindow: $SplittableWindow;
        mainView: $UIElement;
        constructor();
        get title(): $Component;
        get currentProjectDirty(): boolean;
        get currentProjectFile(): $File;
        get window(): $EditorWindow;
        get allViews(): $List<$View>;
        get currentProject(): $IProject;
        get viewFallbacks(): $Map<$View, $Supplier<$ViewContainer>>;
        get savedLayout(): $EditorLayout;
    }
    export class $SplittableWindow extends $UIElement {
        getFirst(): $SplittableWindow;
        getSecond(): $SplittableWindow;
        rebuildFromLayoutConfig(arg0: $SplittableWindow$LayoutConfig_, arg1: $Map_<string, $SplittableWindow>): void;
        isSplit(): boolean;
        getLeftTop(): $ViewContainer;
        splitStyle(arg0: $Consumer_<$SplittableWindow$SplitStyle>): $SplittableWindow;
        splitNew(arg0: $YogaEdge_): $Pair<$SplittableWindow, $SplittableWindow>;
        getAllViews(): $List<$View>;
        setImmortal(arg0: boolean): $SplittableWindow;
        getViewContainer(): $ViewContainer;
        getLayoutConfig(): $SplittableWindow$LayoutConfig;
        getAnchorId(): string;
        setAnchorId(arg0: string): $SplittableWindow;
        getRightTop(): $ViewContainer;
        getLeftBottom(): $ViewContainer;
        setViewContainer(arg0: $ViewContainer): $SplittableWindow;
        applyLayoutConfig(arg0: $SplittableWindow$LayoutConfig_): $SplittableWindow;
        getRightBottom(): $ViewContainer;
        removeSplitWindow(arg0: $SplittableWindow): void;
        setParentWindow(arg0: $SplittableWindow): $SplittableWindow;
        getSplitView(): $SplitView;
        getParentWindow(): $SplittableWindow;
        isImmortal(): boolean;
        splitWith(arg0: $YogaEdge_, arg1: $SplittableWindow): $Pair<$SplittableWindow, $SplittableWindow>;
        getSplitStyle(): $SplittableWindow$SplitStyle;
        static CODEC: $Codec<$UIElement>;
        static EMPTY_LAYOUT: $Layout;
        constructor(arg0: $SplittableWindow, arg1: $ViewContainer);
        constructor(arg0: $SplittableWindow);
        constructor();
        get first(): $SplittableWindow;
        get second(): $SplittableWindow;
        get split(): boolean;
        get leftTop(): $ViewContainer;
        get allViews(): $List<$View>;
        get layoutConfig(): $SplittableWindow$LayoutConfig;
        get rightTop(): $ViewContainer;
        get leftBottom(): $ViewContainer;
        get rightBottom(): $ViewContainer;
        get splitView(): $SplitView;
    }
    export class $SplittableWindow$SplitStyle extends $Style {
        static init(): void;
        percentage(): number;
        percentage(arg0: number): $SplittableWindow$SplitStyle;
        maxPercentage(arg0: number): $SplittableWindow$SplitStyle;
        maxPercentage(): number;
        minPercentage(): number;
        minPercentage(arg0: number): $SplittableWindow$SplitStyle;
        holder: $UIElement;
        constructor(arg0: $SplittableWindow);
    }
}
