import { $InputStream, $OutputStream } from "@package/java/io";
import { $Charset } from "@package/java/nio/charset";
import { $Comparable, $Object, $CharSequence } from "@package/java/lang";
import { $ByteOrder, $ByteBuffer } from "@package/java/nio";
import { $ScatteringByteChannel, $FileChannel, $GatheringByteChannel } from "@package/java/nio/channels";
import { $ReferenceCounted, $ByteProcessor_ } from "@package/com/github/steveice10/netty/util";

declare module "@package/com/github/steveice10/netty/buffer" {
    export class $ByteBuf implements $ReferenceCounted, $Comparable<$ByteBuf> {
        toString(arg0: number, arg1: number, arg2: $Charset): string;
        toString(arg0: $Charset): string;
        compareTo(arg0: $ByteBuf): number;
        indexOf(arg0: number, arg1: number, arg2: number): number;
        getBoolean(arg0: number): boolean;
        getByte(arg0: number): number;
        getShort(arg0: number): number;
        getChar(arg0: number): string;
        getInt(arg0: number): number;
        getLong(arg0: number): number;
        getFloat(arg0: number): number;
        getDouble(arg0: number): number;
        clear(): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuf, arg2: number, arg3: number): $ByteBuf;
        getBytes(arg0: number, arg1: $FileChannel, arg2: number, arg3: number): number;
        getBytes(arg0: number, arg1: $GatheringByteChannel, arg2: number): number;
        getBytes(arg0: number, arg1: $OutputStream, arg2: number): $ByteBuf;
        getBytes(arg0: number, arg1: number[]): $ByteBuf;
        getBytes(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuf;
        getBytes(arg0: number, arg1: $ByteBuffer): $ByteBuf;
        isDirect(): boolean;
        hasArray(): boolean;
        array(): number[];
        arrayOffset(): number;
        writeInt(arg0: number): $ByteBuf;
        readInt(): number;
        setBoolean(arg0: number, arg1: boolean): $ByteBuf;
        setByte(arg0: number, arg1: number): $ByteBuf;
        setChar(arg0: number, arg1: number): $ByteBuf;
        setShort(arg0: number, arg1: number): $ByteBuf;
        setInt(arg0: number, arg1: number): $ByteBuf;
        setLong(arg0: number, arg1: number): $ByteBuf;
        setFloat(arg0: number, arg1: number): $ByteBuf;
        setDouble(arg0: number, arg1: number): $ByteBuf;
        copy(): $ByteBuf;
        copy(arg0: number, arg1: number): $ByteBuf;
        unwrap(): $ByteBuf;
        capacity(): number;
        capacity(arg0: number): $ByteBuf;
        isReadOnly(): boolean;
        slice(arg0: number, arg1: number): $ByteBuf;
        slice(): $ByteBuf;
        duplicate(): $ByteBuf;
        readBytes(arg0: $GatheringByteChannel, arg1: number): number;
        readBytes(arg0: $FileChannel, arg1: number, arg2: number): number;
        readBytes(arg0: $ByteBuf, arg1: number, arg2: number): $ByteBuf;
        readBytes(arg0: $ByteBuf, arg1: number): $ByteBuf;
        readBytes(arg0: $ByteBuf): $ByteBuf;
        readBytes(arg0: number): $ByteBuf;
        readBytes(arg0: $OutputStream, arg1: number): $ByteBuf;
        readBytes(arg0: number[], arg1: number, arg2: number): $ByteBuf;
        readBytes(arg0: number[]): $ByteBuf;
        readBytes(arg0: $ByteBuffer): $ByteBuf;
        writeBytes(arg0: $FileChannel, arg1: number, arg2: number): number;
        writeBytes(arg0: $ByteBuf): $ByteBuf;
        writeBytes(arg0: $InputStream, arg1: number): number;
        writeBytes(arg0: number[]): $ByteBuf;
        writeBytes(arg0: $ByteBuffer): $ByteBuf;
        writeBytes(arg0: number[], arg1: number, arg2: number): $ByteBuf;
        writeBytes(arg0: $ScatteringByteChannel, arg1: number): number;
        writeBytes(arg0: $ByteBuf, arg1: number, arg2: number): $ByteBuf;
        writeBytes(arg0: $ByteBuf, arg1: number): $ByteBuf;
        /**
         * @deprecated
         */
        order(arg0: $ByteOrder): $ByteBuf;
        /**
         * @deprecated
         */
        order(): $ByteOrder;
        writeChar(arg0: number): $ByteBuf;
        readChar(): string;
        writeFloat(arg0: number): $ByteBuf;
        readFloat(): number;
        skipBytes(arg0: number): $ByteBuf;
        readBoolean(): boolean;
        readByte(): number;
        readUnsignedByte(): number;
        readShort(): number;
        readUnsignedShort(): number;
        readLong(): number;
        readDouble(): number;
        getUnsignedShort(arg0: number): number;
        writeBoolean(arg0: boolean): $ByteBuf;
        writeByte(arg0: number): $ByteBuf;
        writeShort(arg0: number): $ByteBuf;
        writeLong(arg0: number): $ByteBuf;
        writeDouble(arg0: number): $ByteBuf;
        isReadable(arg0: number): boolean;
        isReadable(): boolean;
        isWritable(): boolean;
        isWritable(arg0: number): boolean;
        setIndex(arg0: number, arg1: number): $ByteBuf;
        forEachByteDesc(arg0: number, arg1: number, arg2: $ByteProcessor_): number;
        forEachByteDesc(arg0: $ByteProcessor_): number;
        forEachByte(arg0: $ByteProcessor_): number;
        forEachByte(arg0: number, arg1: number, arg2: $ByteProcessor_): number;
        nioBuffer(arg0: number, arg1: number): $ByteBuffer;
        nioBuffer(): $ByteBuffer;
        alloc(): $ByteBufAllocator;
        writeZero(arg0: number): $ByteBuf;
        getMedium(arg0: number): number;
        setIntLE(arg0: number, arg1: number): $ByteBuf;
        setZero(arg0: number, arg1: number): $ByteBuf;
        setLongLE(arg0: number, arg1: number): $ByteBuf;
        getShortLE(arg0: number): number;
        readMedium(): number;
        setMedium(arg0: number, arg1: number): $ByteBuf;
        readIntLE(): number;
        setShortLE(arg0: number, arg1: number): $ByteBuf;
        getFloatLE(index: number): number;
        readLongLE(): number;
        getIntLE(arg0: number): number;
        setBytes(arg0: number, arg1: $ByteBuf): $ByteBuf;
        setBytes(arg0: number, arg1: $ByteBuf, arg2: number): $ByteBuf;
        setBytes(arg0: number, arg1: $FileChannel, arg2: number, arg3: number): number;
        setBytes(arg0: number, arg1: number[], arg2: number, arg3: number): $ByteBuf;
        setBytes(arg0: number, arg1: $ByteBuffer): $ByteBuf;
        setBytes(arg0: number, arg1: $InputStream, arg2: number): number;
        setBytes(arg0: number, arg1: $ScatteringByteChannel, arg2: number): number;
        setBytes(arg0: number, arg1: $ByteBuf, arg2: number, arg3: number): $ByteBuf;
        setBytes(arg0: number, arg1: number[]): $ByteBuf;
        writeIntLE(arg0: number): $ByteBuf;
        retain(): $ByteBuf;
        retain(arg0: number): $ByteBuf;
        readSlice(arg0: number): $ByteBuf;
        setFloatLE(index: number, value: number): $ByteBuf;
        getLongLE(arg0: number): number;
        nioBuffers(): $ByteBuffer[];
        nioBuffers(arg0: number, arg1: number): $ByteBuffer[];
        memoryAddress(): number;
        maxCapacity(): number;
        asReadOnly(): $ByteBuf;
        getCharSequence(arg0: number, arg1: number, arg2: $Charset): $CharSequence;
        writableBytes(): number;
        maxWritableBytes(): number;
        resetReaderIndex(): $ByteBuf;
        markWriterIndex(): $ByteBuf;
        discardReadBytes(): $ByteBuf;
        ensureWritable(arg0: number): $ByteBuf;
        ensureWritable(arg0: number, arg1: boolean): number;
        getUnsignedByte(arg0: number): number;
        getUnsignedMedium(arg0: number): number;
        getMediumLE(arg0: number): number;
        getUnsignedInt(arg0: number): number;
        resetWriterIndex(): $ByteBuf;
        getUnsignedIntLE(arg0: number): number;
        setMediumLE(arg0: number, arg1: number): $ByteBuf;
        setDoubleLE(index: number, value: number): $ByteBuf;
        readMediumLE(): number;
        readUnsignedMedium(): number;
        writerIndex(arg0: number): $ByteBuf;
        writerIndex(): number;
        markReaderIndex(): $ByteBuf;
        getUnsignedShortLE(arg0: number): number;
        getDoubleLE(index: number): number;
        readableBytes(): number;
        setCharSequence(arg0: number, arg1: $CharSequence, arg2: $Charset): number;
        readShortLE(): number;
        readUnsignedInt(): number;
        readUnsignedIntLE(): number;
        readFloatLE(): number;
        readerIndex(): number;
        readerIndex(arg0: number): $ByteBuf;
        hasMemoryAddress(): boolean;
        readCharSequence(arg0: number, arg1: $Charset): $CharSequence;
        writeFloatLE(value: number): $ByteBuf;
        writeShortLE(arg0: number): $ByteBuf;
        isContiguous(): boolean;
        writeMedium(arg0: number): $ByteBuf;
        writeDoubleLE(value: number): $ByteBuf;
        nioBufferCount(): number;
        writeMediumLE(arg0: number): $ByteBuf;
        bytesBefore(arg0: number, arg1: number): number;
        bytesBefore(arg0: number, arg1: number, arg2: number): number;
        bytesBefore(arg0: number): number;
        readDoubleLE(): number;
        internalNioBuffer(arg0: number, arg1: number): $ByteBuffer;
        readRetainedSlice(arg0: number): $ByteBuf;
        writeLongLE(arg0: number): $ByteBuf;
        writeCharSequence(arg0: $CharSequence, arg1: $Charset): number;
        retainedSlice(): $ByteBuf;
        retainedSlice(arg0: number, arg1: number): $ByteBuf;
        retainedDuplicate(): $ByteBuf;
        readUnsignedMediumLE(): number;
        getUnsignedMediumLE(arg0: number): number;
        discardSomeReadBytes(): $ByteBuf;
        readUnsignedShortLE(): number;
        maxFastWritableBytes(): number;
        touch(arg0: $Object): $ReferenceCounted;
        touch(): $ReferenceCounted;
        constructor();
        get direct(): boolean;
        get readOnly(): boolean;
        get contiguous(): boolean;
    }
    export class $ByteBufAllocator {
        static DEFAULT: $ByteBufAllocator;
    }
    export interface $ByteBufAllocator {
        buffer(): $ByteBuf;
        buffer(arg0: number, arg1: number): $ByteBuf;
        buffer(arg0: number): $ByteBuf;
        directBuffer(): $ByteBuf;
        directBuffer(arg0: number, arg1: number): $ByteBuf;
        directBuffer(arg0: number): $ByteBuf;
        compositeBuffer(arg0: number): $CompositeByteBuf;
        compositeBuffer(): $CompositeByteBuf;
        isDirectBufferPooled(): boolean;
        compositeDirectBuffer(): $CompositeByteBuf;
        compositeDirectBuffer(arg0: number): $CompositeByteBuf;
        compositeHeapBuffer(): $CompositeByteBuf;
        compositeHeapBuffer(arg0: number): $CompositeByteBuf;
        calculateNewCapacity(arg0: number, arg1: number): number;
        heapBuffer(arg0: number, arg1: number): $ByteBuf;
        heapBuffer(): $ByteBuf;
        heapBuffer(arg0: number): $ByteBuf;
        ioBuffer(): $ByteBuf;
        ioBuffer(arg0: number): $ByteBuf;
        ioBuffer(arg0: number, arg1: number): $ByteBuf;
        get directBufferPooled(): boolean;
    }
}
