import { $Level_, $Level } from "@package/net/minecraft/world/level";
import { $Path, $PathType_, $NodeEvaluator, $PathFinder } from "@package/net/minecraft/world/level/pathfinder";
import { $BlockPos, $BlockPos_, $Vec3i } from "@package/net/minecraft/core";
import { $Stream } from "@package/java/util/stream";
import { $Mob, $Entity } from "@package/net/minecraft/world/entity";
import { $Set_ } from "@package/java/util";
import { $Vec3_, $Vec3 } from "@package/net/minecraft/world/phys";

declare module "@package/net/minecraft/world/entity/ai/navigation" {
    export class $GroundPathNavigation extends $PathNavigation {
        setAvoidSun(arg0: boolean): void;
        hasValidPathType(arg0: $PathType_): boolean;
        canOpenDoors(): boolean;
        canPassDoors(): boolean;
        setCanOpenDoors(arg0: boolean): void;
        setCanPassDoors(arg0: boolean): void;
        setCanWalkOverFences(arg0: boolean): void;
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
        set avoidSun(value: boolean);
        set canWalkOverFences(value: boolean);
    }
    export class $AmphibiousPathNavigation extends $PathNavigation {
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
    }
    export class $PathNavigation {
        stop(): void;
        isDone(): boolean;
        getPath(): $Path;
        tick(): void;
        moveTo(arg0: $Entity, arg1: number): boolean;
        moveTo(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): boolean;
        moveTo(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        moveTo(arg0: $Path, arg1: number): boolean;
        followThePath(): void;
        doStuckDetection(arg0: $Vec3_): void;
        canMoveDirectly(arg0: $Vec3_, arg1: $Vec3_): boolean;
        setSpeedModifier(arg0: number): void;
        createPathFinder(arg0: number): $PathFinder;
        canUpdatePath(): boolean;
        getTempMobPos(): $Vec3;
        getTargetPos(): $BlockPos;
        canCutCorner(arg0: $PathType_): boolean;
        getNodeEvaluator(): $NodeEvaluator;
        isInProgress(): boolean;
        canFloat(): boolean;
        createPath(arg0: $BlockPos_, arg1: number): $Path;
        createPath(arg0: number, arg1: number, arg2: number, arg3: number): $Path;
        createPath(arg0: $Entity, arg1: number): $Path;
        createPath(arg0: $Stream<$BlockPos_>, arg1: number): $Path;
        createPath(arg0: $Set_<$BlockPos_>, arg1: number): $Path;
        createPath(arg0: $Set_<$BlockPos_>, arg1: number, arg2: boolean, arg3: number): $Path;
        createPath(arg0: $BlockPos_, arg1: number, arg2: number): $Path;
        createPath(arg0: $Set_<$BlockPos_>, arg1: number, arg2: boolean, arg3: number, arg4: number): $Path;
        recomputePath(): void;
        setCanFloat(arg0: boolean): void;
        getMaxDistanceToWaypoint(): number;
        static isClearForMovementBetween(arg0: $Mob, arg1: $Vec3_, arg2: $Vec3_, arg3: boolean): boolean;
        isStableDestination(arg0: $BlockPos_): boolean;
        shouldRecomputePath(arg0: $BlockPos_): boolean;
        isStuck(): boolean;
        getGroundY(arg0: $Vec3_): number;
        trimPath(): void;
        resetMaxVisitedNodesMultiplier(): void;
        setMaxVisitedNodesMultiplier(arg0: number): void;
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
        get done(): boolean;
        get tempMobPos(): $Vec3;
        get targetPos(): $BlockPos;
        get inProgress(): boolean;
        get stuck(): boolean;
        set maxVisitedNodesMultiplier(value: number);
    }
    export class $WaterBoundPathNavigation extends $PathNavigation {
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
    }
    export class $WallClimberNavigation extends $GroundPathNavigation {
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
    }
    export class $FlyingPathNavigation extends $PathNavigation {
        canOpenDoors(): boolean;
        canPassDoors(): boolean;
        setCanOpenDoors(arg0: boolean): void;
        setCanPassDoors(arg0: boolean): void;
        mob: $Mob;
        lastStuckCheck: number;
        level: $Level;
        lastTimeoutCheck: number;
        timeoutLimit: number;
        lastStuckCheckPos: $Vec3;
        maxDistanceToWaypoint: number;
        nodeEvaluator: $NodeEvaluator;
        timeoutTimer: number;
        hasDelayedRecomputation: boolean;
        speedModifier: number;
        path: $Path;
        timeoutCachedNode: $Vec3i;
        timeLastRecompute: number;
        constructor(arg0: $Mob, arg1: $Level_);
    }
}
