export * as minecraft from "@package/net/minecraft";
export * as neoforged from "@package/net/neoforged";
export * as fabricmc from "@package/net/fabricmc";
export * as mehvahdjukaar from "@package/net/mehvahdjukaar";
export * as caffeinemc from "@package/net/caffeinemc";
export * as createmod from "@package/net/createmod";
export * as blay09 from "@package/net/blay09";
export * as irisshaders from "@package/net/irisshaders";
export * as p3pp3rf1y from "@package/net/p3pp3rf1y";
