import { $File } from "@package/java/io";
import { $Consumer_, $Consumer, $BiFunction_ } from "@package/java/util/function";
import { $RenderNode, $Base$RenderPhase_ } from "@package/com/sighs/apricityui/render";
import { $ClientScheduler$Cancellable } from "@package/com/sighs/apricityui/task";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $CopyOnWriteArrayList } from "@package/java/util/concurrent";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $CSS$DebugRule } from "@package/com/sighs/apricityui/resource";
import { $Record, $Object, $Cloneable } from "@package/java/lang";
import { $Text$WrappedTextCache, $Transform, $Filter$FilterState, $Size, $Position, $Background, $Box, $Text } from "@package/com/sighs/apricityui/style";
import { $ArrayList, $HashMap, $UUID, $List, $Map, $Set, $UUID_ } from "@package/java/util";
import { $Body } from "@package/com/sighs/apricityui/element";

declare module "@package/com/sighs/apricityui/init" {
    export class $Window {
        setTimeout(arg0: $Consumer_<$ClientScheduler$Cancellable>, arg1: number): $ClientScheduler$Cancellable;
        removeEventListener(arg0: string, arg1: $Consumer_<$Object>): void;
        removeEventListener(arg0: string, arg1: $Consumer_<$Object>, arg2: boolean): void;
        dispatchEvent(arg0: $Object): boolean;
        addEventListener(arg0: string, arg1: $Consumer_<$Object>, arg2: boolean): void;
        addEventListener(arg0: string, arg1: $Consumer_<$Object>): void;
        fireResizeEvent(): void;
        setInterval(arg0: $Consumer_<$ClientScheduler$Cancellable>, arg1: number): $ClientScheduler$Cancellable;
        getInnerWidth(): number;
        getInnerHeight(): number;
        cancelAnimationFrame(arg0: number): void;
        requestAnimationFrame(arg0: $Consumer_<number>): number;
        getDevicePixelRatio(): number;
        createMouseEvent(arg0: string, arg1: number, arg2: number, arg3: number): $Window$WindowMouseEvent;
        getPerformance(): $Window$Performance;
        localStorage: $LocalStorage;
        static window: $Window;
        constructor();
        get innerWidth(): number;
        get innerHeight(): number;
        get devicePixelRatio(): number;
        get performance(): $Window$Performance;
    }
    export class $Element {
        remove(): void;
        append(arg0: $Element): void;
        static register(arg0: string, arg1: $BiFunction_<$Document, string, $Element>): void;
        static init(arg0: $Element): $Element;
        setValue(arg0: string): void;
        prepend(arg0: $Element): void;
        getAttributes(): $HashMap<string, string>;
        setAttribute(arg0: string, arg1: string): void;
        getAttribute(arg0: string): string;
        tick(): void;
        removeAttribute(arg0: string): void;
        getDepth(): number;
        hasAttribute(arg0: string): boolean;
        canScrollVertically(): boolean;
        canScrollHorizontally(): boolean;
        triggerEvent(arg0: $Consumer_<$Event>): void;
        removeEventListener(arg0: string, arg1: $Consumer_<$Event>, arg2: boolean): void;
        addEventListener(arg0: string, arg1: $Consumer_<$Event>, arg2: boolean): void;
        addEventListener(arg0: string, arg1: $Consumer_<$Event>): void;
        getRoute(): $ArrayList<$Element>;
        setHover(arg0: boolean): void;
        canFocus(): boolean;
        drawPhase(arg0: $PoseStack, arg1: $Base$RenderPhase_): void;
        setActive(arg0: boolean): void;
        getRawComputedStyle(): $Style;
        hasInnerTextSelection(): boolean;
        addInternalEventListener(arg0: string, arg1: $Consumer_<$Event>, arg2: boolean): void;
        addInternalEventListener(arg0: string, arg1: $Consumer_<$Event>): void;
        getCustomPropertyInherit(arg0: string): string;
        getRawCustomProperty(arg0: string): string;
        getSelectedInnerText(): string;
        getParentStackContext(): $Element;
        getTargetScrollLeft(): number;
        getRenderer(): $RenderElement;
        setFocus(arg0: boolean): void;
        updateInlineStyle(): void;
        getCustomProperty(arg0: string): string;
        isStackContext(): boolean;
        clearTextSelection(): void;
        static isElementFocusing(arg0: $Element): boolean;
        invalidateStyle(): void;
        setScrollLeft(arg0: number): void;
        getScrollLeft(): number;
        setScrollTop(arg0: number): void;
        getScrollTop(): number;
        canSelectInnerText(): boolean;
        getComputedStyle(): $Style;
        querySelectorAll(arg0: string): $List<$Element>;
        querySelector(arg0: string): $Element;
        addDirtyFlags(arg0: number): void;
        selectAllInnerText(): void;
        getRouteArray(): $Element[];
        forEachRoute(arg0: $Consumer_<$Element>): void;
        getClassNames(): $Set<string>;
        hasDirtyFlag(arg0: number): boolean;
        clearDirtyFlags(): void;
        resetRenderer(): void;
        getTargetScrollTop(): number;
        getStyle(): $Style;
        canScroll(): boolean;
        document: $Document;
        scrollHeight: number;
        classNames: $Set<string>;
        isActive: boolean;
        uuid: $UUID;
        isLoaded: boolean;
        parentElement: $Element;
        children: $CopyOnWriteArrayList<$Element>;
        targetScrollLeft: number;
        targetScrollTop: number;
        id: string;
        scrollLeft: number;
        EventListener: $CopyOnWriteArrayList<$Event>;
        value: string;
        scrollWidth: number;
        cssCache: $HashMap<string, string>;
        innerText: string;
        isHover: boolean;
        isVisible: boolean;
        tagName: string;
        scrollTop: number;
        depth: number;
        isPointerEnabled: boolean;
        isFocus: boolean;
        style: $Style;
        constructor(arg0: $Document, arg1: string);
        get attributes(): $HashMap<string, string>;
        get route(): $ArrayList<$Element>;
        set hover(value: boolean);
        set active(value: boolean);
        get rawComputedStyle(): $Style;
        get selectedInnerText(): string;
        get parentStackContext(): $Element;
        get renderer(): $RenderElement;
        set focus(value: boolean);
        get stackContext(): boolean;
        get computedStyle(): $Style;
        get routeArray(): $Element[];
    }
    export class $Style$TextStroke extends $Record {
        color(): number;
        width(): number;
        static NONE: $Style$TextStroke;
        constructor(width: number, color: number);
    }
    export class $Style implements $Cloneable {
        get(arg0: string): string;
        clone(): $Style;
        update(arg0: string, arg1: string): void;
        merge(arg0: string): void;
        static getFontSize(arg0: $Element): number;
        static getVisibility(arg0: $Element): string;
        resolveVarReferences(arg0: $Element): void;
        static getTextDirection(arg0: $Element): string;
        getCustomProperty(arg0: string): string;
        static allowsUserScrollX(arg0: $Style): boolean;
        static getFontColor(arg0: $Element): number;
        static clipsOverflow(arg0: string): boolean;
        static clipsOverflow(arg0: $Style): boolean;
        static allowsUserScrollY(arg0: $Style): boolean;
        static isUserSelectable(arg0: $Element): boolean;
        static getSelectionColor(arg0: $Element): number;
        static isUserSelectAll(arg0: $Element): boolean;
        static isObliqueValue(arg0: string): boolean;
        static parseTextStroke(arg0: string): $Style$TextStroke;
        static parseFontWeight(arg0: string): number;
        static isOblique(arg0: $Element): boolean;
        static isVisible(arg0: $Element): boolean;
        static normalizeVisibility(arg0: string): string;
        static normalizeUserSelect(arg0: string): string;
        toCss(): string;
        static transformStyleName(arg0: string): string;
        static normalizeOverflow(arg0: string): string;
        static resolveOverflowX(arg0: $Style): string;
        static getUserSelect(arg0: $Element): string;
        static allowsUserScroll(arg0: string): boolean;
        static getTextStroke(arg0: $Element): $Style$TextStroke;
        static getTextAlign(arg0: $Element): string;
        static getVerticalAlign(arg0: $Element): string;
        static getWhiteSpace(arg0: $Element): string;
        static getTextIndent(arg0: $Element): number;
        static getLetterSpacing(arg0: $Element): number;
        static resolveOverflowY(arg0: $Style): string;
        static getFontFamily(arg0: $Element): string;
        static getFontWeight(arg0: $Element): number;
        paddingRight: string;
        minHeight: string;
        marginRight: string;
        flexWrap: string;
        flexShrink: string;
        animationTimingFunction: string;
        height: string;
        maxWidth: string;
        zIndex: string;
        verticalAlign: string;
        animationName: string;
        margin: string;
        alignItems: string;
        clipPath: string;
        fontStyle: string;
        justifyContent: string;
        animation: string;
        overflowX: string;
        overflowY: string;
        left: string;
        pointerEvents: string;
        fontSize: string;
        animationIterationCount: string;
        backgroundRepeat: string;
        paddingLeft: string;
        borderImageWidth: string;
        borderImageSlice: string;
        flexGrow: string;
        rowGap: string;
        boxSizing: string;
        borderTop: string;
        top: string;
        maxHeight: string;
        backgroundSize: string;
        backgroundPosition: string;
        animationFillMode: string;
        backgroundColor: string;
        animationDelay: string;
        flexDirection: string;
        display: string;
        flexBasis: string;
        minWidth: string;
        right: string;
        transition: string;
        filter: string;
        width: string;
        borderImageOutset: string;
        lineHeight: string;
        opacity: string;
        marginTop: string;
        boxShadow: string;
        selectionColor: string;
        alignContent: string;
        borderLeft: string;
        overflow: string;
        paddingBottom: string;
        fontFamily: string;
        gridRow: string;
        borderBottom: string;
        fontWeight: string;
        border: string;
        alignSelf: string;
        textStroke: string;
        visibility: string;
        backdropFilter: string;
        textAlign: string;
        bottom: string;
        userSelect: string;
        justifySelf: string;
        marginLeft: string;
        borderImageSource: string;
        columnGap: string;
        borderRadius: string;
        borderRight: string;
        marginBottom: string;
        position: string;
        cursor: string;
        color: string;
        backgroundImage: string;
        gridColumn: string;
        animationDirection: string;
        textIndent: string;
        transform: string;
        flex: string;
        gap: string;
        paddingTop: string;
        textOverflow: string;
        direction: string;
        padding: string;
        whiteSpace: string;
        borderImage: string;
        letterSpacing: string;
        justifyItems: string;
        animationDuration: string;
        gridTemplateRows: string;
        gridTemplateColumns: string;
        animationPlayState: string;
        static DEFAULT: $Style;
        borderImageRepeat: string;
        constructor();
    }
    export class $RenderElement {
        static observeStyle(arg0: $Element, arg1: $Style, arg2: $Style): void;
        static observeAttribute(arg0: $Element, arg1: $HashMap<string, string>, arg2: $HashMap<string, string>): void;
        cursor: $RenderElement$Cache<string>;
        computedStyle: $RenderElement$Cache<$Style>;
        wrappedText: $RenderElement$Cache<$Text$WrappedTextCache>;
        backdropFilter: $RenderElement$Cache<$Filter$FilterState>;
        box: $RenderElement$Cache<$Box>;
        filter: $RenderElement$Cache<$Filter$FilterState>;
        transform: $RenderElement$Cache<$List<$Transform>>;
        route: $RenderElement$Cache<$Element[]>;
        size: $RenderElement$Cache<$Size>;
        background: $RenderElement$Cache<$Background>;
        text: $RenderElement$Cache<$Text>;
        position: $RenderElement$Cache<$Position>;
        opacity: $RenderElement$Cache<number>;
        constructor(arg0: $Element);
    }
    export class $Window$WindowEvent {
        type: string;
        constructor(arg0: string);
    }
    export class $Window$WindowMouseEvent extends $Window$WindowEvent {
        button: number;
        clientY: number;
        clientX: number;
        bubbles: boolean;
        type: string;
        pageY: number;
        pageX: number;
        constructor(arg0: string, arg1: number, arg2: number, arg3: number);
    }
    export class $Document {
        refresh(): void;
        getElements(): $ArrayList<$Element>;
        createElement(arg0: string): $Element;
        static remove(arg0: string): void;
        remove(): void;
        static remove(arg0: $UUID_): void;
        static get(arg0: string): $ArrayList<$Document>;
        static create(arg0: string): $Document;
        getPath(): string;
        is(arg0: $UUID_): boolean;
        is(arg0: string): boolean;
        static getAll(): $List<$Document>;
        tickElements(): void;
        commitStyleRecalc(): void;
        commitRenderState(): void;
        getDirtyElements(): $Set<$Element>;
        stepMotionRender(): void;
        isReloadPersistent(): boolean;
        setActiveElement(arg0: $Element): void;
        getPaintList(): $ArrayList<$RenderNode>;
        getElementById(arg0: string): $Element;
        removeElement(arg0: $Element): void;
        static getByUUID(arg0: string): $Document;
        recordID(arg0: $Element): void;
        clearAllTextSelectionsExcept(arg0: $Element): void;
        setHasAnimationSpec(arg0: $Element, arg1: boolean): void;
        getPreviousCursorElement(): $Element;
        setPreviousCursorElement(arg0: $Element): void;
        hasAnyTextSelection(): boolean;
        clearAllTextSelections(): void;
        setTransitionActive(arg0: $Element, arg1: boolean): void;
        invalidateSelectorIndex(): void;
        flushPendingStyleUpdates(): void;
        reapplyStylesFromCache(): void;
        rebuildSelectorIndex(): void;
        setReloadPersistent(arg0: boolean): void;
        getRefreshGeneration(): number;
        static refreshAll(): void;
        requestStyleRecalc(arg0: $Element): void;
        updateElement(arg0: $Element): void;
        querySelectorAll(arg0: string): $List<$Element>;
        querySelector(arg0: string): $Element;
        getActiveElement(): $Element;
        createRelation(arg0: $Element, arg1: $Element, arg2: boolean): void;
        setFocusedElement(arg0: $Element): void;
        getFocusedElement(): $Element;
        getUuid(): $UUID;
        clearFocus(): void;
        createHTML(arg0: string): $Element;
        tickFrame(): void;
        stepMotion(): void;
        markDirty(arg0: number): void;
        markDirty(arg0: $Element, arg1: number): void;
        static createInWorld(arg0: string): $Document;
        CSSDebugRules: $List<$CSS$DebugRule>;
        JSCache: $List<string>;
        CSSCache: $Map<string, $Map<string, string>>;
        body: $Body;
        inWorld: boolean;
        constructor(arg0: string, arg1: boolean);
        get elements(): $ArrayList<$Element>;
        get path(): string;
        static get all(): $List<$Document>;
        get dirtyElements(): $Set<$Element>;
        get paintList(): $ArrayList<$RenderNode>;
        get refreshGeneration(): number;
        get uuid(): $UUID;
    }
    export class $LocalStorage {
        save(): void;
        localStorage: $CompoundTag;
        static LOCAL_STORAGE_FILE_PATH: $File;
        constructor();
    }
    export class $Window$Performance {
        now(): number;
        constructor();
    }
    export class $RenderElement$Cache<T> {
        get(): T;
        clear(): void;
        set(arg0: T): void;
        constructor();
    }
    export class $Event {
        stopPropagation(): void;
        static getRoute(arg0: $Element): $ArrayList<$Element>;
        static tiggerEvent(arg0: $Event): boolean;
        static triggerSingle(arg0: $Event): boolean;
        useCapture: boolean;
        internal: boolean;
        currentTarget: $Element;
        listener: $Consumer<$Event>;
        stoppedPropagation: boolean;
        type: string;
        target: $Element;
        constructor(arg0: $Element, arg1: string, arg2: $Consumer_<$Event>, arg3: boolean);
        constructor(arg0: $Element, arg1: string, arg2: $Consumer_<$Event>, arg3: boolean, arg4: boolean);
    }
}
