import { $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $ItemStack_ } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $IEntityWithComplexSpawn } from "@package/net/neoforged/neoforge/entity";
import { $EntityType_, $Entity$RemovalReason, $LivingEntity, $Pose, $PortalProcessor, $EntityType, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $ImmutableList } from "@package/com/google/common/collect";
import { $Projectile } from "@package/net/minecraft/world/entity/projectile";
import { $UUID, $List, $List_ } from "@package/java/util";
import { $EntityKineticBulletAccessor } from "@package/mod/chloeprime/gunsmithlib/mixin";
import { $GunData, $BulletData } from "@package/com/tacz/guns/resource/pojo/data/gun";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SynchedEntityData, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $BlockPos } from "@package/net/minecraft/core";
import { $OBB$Part } from "@package/com/atsuishio/superbwarfare/tools";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Vec3_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $EnhancedKineticBullet } from "@package/mod/chloeprime/gunsmithlib/common/internal";
import { $Vector2d, $Vector3f } from "@package/org/joml";
export * as shooter from "@package/com/tacz/guns/entity/shooter";

declare module "@package/com/tacz/guns/entity" {
    export class $EntityKineticBullet extends $Projectile implements $IEntityWithComplexSpawn, $EntityKineticBulletAccessor, $EnhancedKineticBullet {
        gunsmithlib$setPotionCloudMinSizeRate(arg0: number): void;
        gunsmithlib$getPotionCloudMinSizeRate(): number;
        isTracerAmmo(): boolean;
        getCameraXRot(): number;
        setCameraXRot(arg0: number): void;
        setCameraYRot(arg0: number): void;
        getCameraYRot(): number;
        getGunDisplayId(): $ResourceLocation;
        getAmmoId(): $ResourceLocation;
        gunsmithlib$getPotionCloudDuration(): number;
        gunsmithlib$setPotionCloudDuration(arg0: number): void;
        gunsmithlib$getPotionEffects(): $List<any>;
        gunsmithlib$setPotionEffects(arg0: $List_<any>): void;
        shootFromRotation(arg0: $Entity, arg1: number, arg2: number, arg3: number, arg4: number, arg5: $Vector2d): void;
        shoot(arg0: number, arg1: number, arg2: number, arg3: $Vector2d): void;
        getTracerSizeOverride(): number;
        setShotDamageMultiplier(arg0: number): void;
        applyShotgunDamageSpread(arg0: number): void;
        gunsmithlib$getHitPos(): $Vec3;
        getTracerColorOverride(): (number[]) | undefined;
        setFirstPersonRenderOffset(arg0: $Vector3f): void;
        getFirstPersonRenderOffset(): $Vector3f;
        getDamage(arg0: $Vec3_): number;
        writeSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        readSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        getExplosionRadius(): number;
        isExplosion(): boolean;
        getExplosion(): boolean;
        setGravity(arg0: number): void;
        setArmorIgnore(arg0: number): void;
        getGunId(): $ResourceLocation;
        getGravity(): number;
        setExplosionDelayCount(arg0: number): void;
        getLife(): number;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static TYPE: $EntityType<$EntityKineticBullet>;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        passengers: $ImmutableList<$Entity>;
        static CONTENTS_SLOT_INDEX: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        create_diesel_generators$turretPos: $BlockPos;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        sbw$currentHitPart: $OBB$Part;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        static TRACER_SIZE_OVERRIDER_KEY: string;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        ownerUUID: $UUID;
        static USE_MAGIC_DAMAGE_ON: $TagKey<$EntityType<never>>;
        static PRETEND_MELEE_DAMAGE_ON: $TagKey<$EntityType<never>>;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static TRACER_COLOR_OVERRIDER_KEY: string;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static USE_VOID_DAMAGE_ON: $TagKey<$EntityType<never>>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        constructor(arg0: $Level_, arg1: $LivingEntity, arg2: $ItemStack_, arg3: $ResourceLocation_, arg4: $ResourceLocation_, arg5: boolean, arg6: $GunData, arg7: $BulletData);
        constructor(arg0: $Level_, arg1: $LivingEntity, arg2: $ItemStack_, arg3: $ResourceLocation_, arg4: $ResourceLocation_, arg5: $ResourceLocation_, arg6: boolean, arg7: $GunData, arg8: $BulletData);
        constructor(arg0: $EntityType_<$Projectile>, arg1: number, arg2: number, arg3: number, arg4: $Level_);
        constructor(arg0: $EntityType_<$Projectile>, arg1: $Level_);
        get tracerAmmo(): boolean;
        get gunDisplayId(): $ResourceLocation;
        get ammoId(): $ResourceLocation;
        get tracerSizeOverride(): number;
        set shotDamageMultiplier(value: number);
        get tracerColorOverride(): (number[]) | undefined;
        get explosionRadius(): number;
        set armorIgnore(value: number);
        get gunId(): $ResourceLocation;
        set explosionDelayCount(value: number);
        get life(): number;
    }
}
