import { $DefaultConstructorMarker } from "@package/kotlin/jvm/internal";
import { $EntityResult } from "@package/com/atsuishio/superbwarfare/world/phys";
import { $GunData, $ShootParameters_, $DefaultGunData } from "@package/com/atsuishio/superbwarfare/data/gun";
import { $Item$Properties, $Item, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $Entity } from "@package/net/minecraft/world/entity";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $IEnergyStorage } from "@package/net/neoforged/neoforge/energy";
import { $Map_, $Map, $UUID_ } from "@package/java/util";
import { $EnergyStorageItem, $ItemScreenProvider } from "@package/com/atsuishio/superbwarfare/item";
import { $InteractionHand_ } from "@package/net/minecraft/world";
import { $Consumer_, $Consumer } from "@package/java/util/function";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $ServerLevel } from "@package/net/minecraft/server/level";
import { $Screen } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $PMC, $PropertyModifier } from "@package/com/atsuishio/superbwarfare/data";
import { $Block } from "@package/net/minecraft/world/level/block";
import { $Object } from "@package/java/lang";
import { $GunResource } from "@package/com/atsuishio/superbwarfare/resource/gun";
import { $Vec3_, $BlockHitResult } from "@package/net/minecraft/world/phys";

declare module "@package/com/atsuishio/superbwarfare/item/gun" {
    export class $GunItem extends $Item implements $ItemScreenProvider, $EnergyStorageItem, $PropertyModifier<$GunData, $DefaultGunData> {
        init(arg0: $GunData): void;
        tick(arg0: $Entity, arg1: $GunData, arg2: boolean): void;
        getCustomMagazine(arg0: $GunData): number;
        getEnergyBarColor(arg0: $GunResource): number;
        hasCustomBarrel(arg0: $GunData): boolean;
        getValidScopes(): number[];
        getMaxEnergy(arg0: $ItemStack_): number;
        getValidGrips(): number[];
        getCustomWeight(arg0: $GunData): number;
        hasCustomScope(arg0: $GunData): boolean;
        hasCustomStock(arg0: $GunData): boolean;
        getValidStocks(): number[];
        getValidMagazines(): number[];
        hasMeleeAttack(arg0: $GunData): boolean;
        getValidBarrels(): number[];
        getCustomZoom(arg0: $GunData): number;
        getCustomDamage(arg0: $GunData): number;
        getCustomRPM(arg0: $GunData): number;
        getCustomVelocity(arg0: $GunData): number;
        getCustomHeadshot(arg0: $GunData): number;
        hasCustomGrip(arg0: $GunData): boolean;
        hasCustomMagazine(arg0: $GunData): boolean;
        canSwitchScope(arg0: $GunData): boolean;
        onFireKeyPress(arg0: $GunData, arg1: $Player, arg2: boolean): void;
        getItemScreen(arg0: $ItemStack_, arg1: $Player, arg2: $InteractionHand_): $Screen;
        enableShootTimer(): boolean;
        canEditAttachments(arg0: $GunData): boolean;
        getDefaultData(arg0: $GunData): $DefaultGunData;
        onFireKeyRelease(arg0: $GunData, arg1: $Player, arg2: number, arg3: boolean): void;
        shootBullet(arg0: $ShootParameters_): boolean;
        shootBullet(arg0: $Entity, arg1: $ServerLevel, arg2: $Vec3_, arg3: $Vec3_, arg4: $GunData, arg5: number, arg6: boolean, arg7: $UUID_): boolean;
        canAdjustZoom(arg0: $GunData): boolean;
        playFireSounds(arg0: $GunData, arg1: $Entity, arg2: boolean): void;
        getEnergyProvider(arg0: $GunData, arg1: $Entity): $IEnergyStorage;
        onChangeSlot(arg0: $GunData, arg1: $Entity): void;
        isInitialized(arg0: $GunData): boolean;
        getCustomSoundRadius(arg0: $GunData): number;
        addReloadTimeBehavior(arg0: $Map_<number, $Consumer_<$GunData>>): void;
        addBoltTimeBehavior(arg0: $Map_<number, $Consumer_<$GunData>>): void;
        getMaxExtractEnergy(arg0: $ItemStack_): number;
        getCustomBypassArmor(arg0: $GunData): number;
        getMaxReceiveEnergy(arg0: $ItemStack_): number;
        shoot(arg0: $GunData, arg1: $Entity, arg2: number, arg3: boolean, arg4: $UUID_, arg5: $Vec3_): void;
        shoot(arg0: $GunData, arg1: $Entity, arg2: number, arg3: boolean, arg4: $UUID_): void;
        shoot(arg0: $ServerLevel, arg1: $Vec3_, arg2: $Vec3_, arg3: $GunData, arg4: number, arg5: boolean, arg6: $UUID_): void;
        shoot(arg0: $ShootParameters_): void;
        shoot(arg0: $Entity, arg1: $ServerLevel, arg2: $Vec3_, arg3: $Vec3_, arg4: $GunData, arg5: number, arg6: boolean, arg7: $UUID_): void;
        hasBulletInBarrel(arg0: $GunData): boolean;
        onRayHitEntity(arg0: $Entity, arg1: $ServerLevel, arg2: $GunData, arg3: $EntityResult, arg4: $Vec3_, arg5: $Vec3_): void;
        onRayHitBlock(arg0: $Entity, arg1: $ServerLevel, arg2: $Entity, arg3: $GunData, arg4: $Vec3_, arg5: $BlockHitResult, arg6: $Vec3_): void;
        getGunIcon(arg0: $ItemStack_): $ResourceLocation;
        getGunIcon(arg0: $GunData): $ResourceLocation;
        isOpenBolt(arg0: $GunData): boolean;
        hasBipod(arg0: $GunData): boolean;
        whenNoAmmo(arg0: $GunData): void;
        afterShoot(arg0: $ShootParameters_): void;
        afterShoot(arg0: $Entity, arg1: $ServerLevel, arg2: $Vec3_, arg3: $Vec3_, arg4: $GunData, arg5: number, arg6: boolean, arg7: $UUID_): void;
        canShoot(arg0: $GunData, arg1: $Entity): boolean;
        shootRay(arg0: $ShootParameters_): boolean;
        useSpecialFireProcedure(arg0: $GunData): boolean;
        hideBulletChainBelowShots(): number;
        getCustomBoltActionTime(arg0: $GunData): number;
        modifyProperty(arg0: $PMC<$GunData, $DefaultGunData>): void;
        beforeShoot(arg0: $Entity, arg1: $ServerLevel, arg2: $Vec3_, arg3: $Vec3_, arg4: $GunData, arg5: number, arg6: boolean): void;
        beforeShoot(arg0: $ShootParameters_): void;
        getRayHitEntitySound(arg0: $GunData): $SoundEvent;
        getRayHitBlockSound(arg0: $GunData): $SoundEvent;
        static Companion: $GunItem$Companion;
        reloadTimeBehaviors: $Map<number, $Consumer<$GunData>>;
        static BASE_ATTACK_DAMAGE_ID: $ResourceLocation;
        static DEFAULT_MAX_STACK_SIZE: number;
        static MAX_BAR_WIDTH: number;
        static BASE_ATTACK_SPEED_ID: $ResourceLocation;
        static ABSOLUTE_MAX_STACK_SIZE: number;
        canRepair: boolean;
        boltTimeBehaviors: $Map<number, $Consumer<$GunData>>;
        moonlight$clientAnimationProvider: $Object;
        static BY_BLOCK: $Map<$Block, $Item>;
        constructor(arg0: $Item$Properties);
        get validScopes(): number[];
        get validGrips(): number[];
        get validStocks(): number[];
        get validMagazines(): number[];
        get validBarrels(): number[];
    }
    export class $GunItem$Companion {
        constructor(arg0: $DefaultConstructorMarker);
    }
}
