import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $MoveControl, $LookControl, $JumpControl } from "@package/net/minecraft/world/entity/ai/control";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $EntityType_, $Pose, $PortalProcessor, $Entity, $EntityDimensions, $Entity$RemovalReason, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $UUID, $List, $Stack, $Map, $Set } from "@package/java/util";
import { $AbstractGolem } from "@package/net/minecraft/world/entity/animal";
import { $RandomSource } from "@package/net/minecraft/util";
import { $PlayerModel } from "@package/net/minecraft/client/model";
import { $InteractionHand } from "@package/net/minecraft/world";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $HolderLookup$Provider, $BlockPos, $BlockPos_, $SectionPos, $Vec3i } from "@package/net/minecraft/core";
import { $OBB$Part } from "@package/com/atsuishio/superbwarfare/tools";
import { $Brain } from "@package/net/minecraft/world/entity/ai";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $PathNavigation } from "@package/net/minecraft/world/entity/ai/navigation";
import { $Enum } from "@package/java/lang";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $WorldAttached, $Couple } from "@package/net/createmod/catnip/data";
import { $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey } from "@package/net/minecraft/tags";
import { $DyeColor_, $ItemStack_, $ItemStack, $DyeColor } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $ImmutableList } from "@package/com/google/common/collect";
import { $EntityDataAccessor, $SynchedEntityData } from "@package/net/minecraft/network/syncher";
import { $DamageContainer } from "@package/net/neoforged/neoforge/common/damagesource";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $MountedToolbox } from "@package/com/railwayteam/railways/content/conductor/toolbox";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $DamageSource } from "@package/net/minecraft/world/damagesource";
export * as toolbox from "@package/com/railwayteam/railways/content/conductor/toolbox";

declare module "@package/com/railwayteam/railways/content/conductor" {
    export class $ConductorEntity extends $AbstractGolem {
        setColor(arg0: $DyeColor_): void;
        getColor(): $DyeColor;
        static spawn(arg0: $Level_, arg1: $BlockPos_, arg2: $ItemStack_): $ConductorEntity;
        turnView(arg0: number, arg1: number): void;
        onSpyInteract(arg0: $BlockPos_): void;
        isInMinecart(): boolean;
        isCarryingToolbox(): boolean;
        hasSentChunks(): boolean;
        canUseBlock(arg0: $BlockState_): boolean;
        equipToolbox(arg0: $ItemStack_): void;
        isPossessed(): boolean;
        unequipToolbox(): $ItemStack;
        setHasSentChunks(arg0: boolean): void;
        isHoldingSchedules(): boolean;
        static defaultColor(): $DyeColor;
        doCheckFallDamage(arg0: number, arg1: boolean): void;
        stopViewing(arg0: $ServerPlayer): void;
        getOrCreateToolboxHolder(): $MountedToolbox;
        getToolboxDisplayStack(): $ItemStack;
        updatePossessionInputs(): void;
        setChunkLoadingDistance(arg0: number): void;
        isCorrectEngineerCap(arg0: $ItemStack_): boolean;
        static hasRecentlyDismounted(arg0: $Player): boolean;
        getSecondaryHeadStack(): $ItemStack;
        isHoldingSchedulesClient(): boolean;
        isPossessedAndClient(): boolean;
        static canSpyInteract(arg0: $BlockState_): boolean;
        startViewing(arg0: $ServerPlayer): boolean;
        static colorFrom(arg0: number): $DyeColor;
        getToolbox(): $MountedToolbox;
        setJob(arg0: $ConductorEntity$Job_): void;
        static createAttributes(): $AttributeSupplier$Builder;
        canReach(arg0: $Vec3i): boolean;
        static isPlayerDisguised(arg0: $Player): boolean;
        addSchedule(arg0: $ItemStack_): void;
        getForwardSignalStrength(): number;
        teleportToForce(arg0: number, arg1: number, arg2: number): void;
        static idFrom(arg0: $DyeColor_): number;
        getJob(): $ConductorEntity$Job;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static MAX_WEARING_ARMOR_CHANCE: number;
        lastHurtByPlayerTime: number;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        autoSpinAttackItemStack: $ItemStack;
        lerpYRot: number;
        static DEFAULT_BASE_GRAVITY: number;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static ENTITY_COUNTER: $AtomicInteger;
        static FREQUENCY_DATA: $Map<string, $Couple<$EntityDataAccessor<$ItemStack>>>;
        static RECENTLY_DISMOUNTED_PLAYERS: $List<$Player>;
        lerpYHeadRot: number;
        static DEFAULT_WALK_TARGET_VALUE: number;
        static MAX_PICKUP_LOOT_CHANCE: number;
        visualBaseEntity: $Player;
        navigation: $PathNavigation;
        useItem: $ItemStack;
        yHeadRot: number;
        noPhysics: boolean;
        fallFlyTicks: number;
        autoSpinAttackDmg: number;
        yo: number;
        static DATA_LIVING_ENTITY_FLAGS: $EntityDataAccessor<number>;
        yBodyRotO: number;
        static FLAG_ONFIRE: number;
        sbw$beastKilled: boolean;
        removalReason: $Entity$RemovalReason;
        zza: number;
        passengers: $ImmutableList<$Entity>;
        rotOffs: number;
        goalSelector: $GoalSelector;
        handDropChances: number[];
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        armorDropChances: number[];
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        lastHurt: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        sbw$currentHitPart: $OBB$Part;
        lastDamageSource: $DamageSource;
        appliedScale: number;
        yya: number;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        xRotLast: number;
        yRotLast: number;
        dead: boolean;
        verticalCollision: boolean;
        static RANDOM_SPAWN_BONUS_ID: $ResourceLocation;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        static ATTRIBUTES_FIELD: string;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        yLast: number;
        lerpHeadSteps: number;
        flyDist: number;
        brain: $Brain<never>;
        static PASSENGERS_TAG: string;
        stringUUID: string;
        wasOnFire: boolean;
        autoSpinAttackTicks: number;
        attackAnim: number;
        noActionTime: number;
        zOld: number;
        firstGoodY: number;
        timeOffs: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        firstGoodZ: number;
        static LIVING_ENTITY_FLAG_SPIN_ATTACK: number;
        oldSectionPos: $SectionPos;
        firstGoodX: number;
        wasTouchingWater: boolean;
        rotA: number;
        horizontalCollision: boolean;
        visualBaseModel: $PlayerModel<never>;
        firstTick: boolean;
        damageContainers: $Stack<$DamageContainer>;
        static HOLDING_SCHEDULES: $EntityDataAccessor<boolean>;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        run: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        uuid: $UUID;
        xLast: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        static COLOR: $EntityDataAccessor<number>;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        jumpControl: $JumpControl;
        animStepO: number;
        static JOB: $EntityDataAccessor<number>;
        receivedMovePacketCount: number;
        lastHurtByPlayer: $Player;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        static PICKUP_REACH: number;
        ambientSoundTime: number;
        static BLOCK: $EntityDataAccessor<$BlockPos>;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        oRun: number;
        targetSelector: $GoalSelector;
        lookControl: $LookControl;
        bob: number;
        create_diesel_generators$turretPos: $BlockPos;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        ventCooldown: number;
        xpReward: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        useItemRemaining: number;
        entityData: $SynchedEntityData;
        static FAKE_PLAYER_PROFILE: $GameProfile;
        static SLEEPING_DIMENSIONS: $EntityDimensions;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        moveControl: $MoveControl;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static WITH_TOOLBOXES: $WorldAttached<$Set<$ConductorEntity>>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        static LIVING_ENTITY_FLAG_OFF_HAND: number;
        random: $RandomSource;
        lerpSteps: number;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static LIVING_ENTITY_FLAG_IS_USING: number;
        bodyArmorDropChance: number;
        lastDamageStamp: number;
        levelCallback: $EntityInLevelCallback;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        lerpX: number;
        lerpZ: number;
        knownMovePacketCount: number;
        lerpY: number;
        lerpXRot: number;
        removeArrowTime: number;
        walkDistO: number;
        lastGoodX: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        lastGoodY: number;
        lastGoodZ: number;
        zLast: number;
        animStep: number;
        yBodyRot: number;
        blocksBuilding: boolean;
        deathScore: number;
        oBob: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        invulnerableDuration: number;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        constructor(arg0: $EntityType_<$AbstractGolem>, arg1: $Level_);
        get inMinecart(): boolean;
        get carryingToolbox(): boolean;
        get possessed(): boolean;
        get holdingSchedules(): boolean;
        get orCreateToolboxHolder(): $MountedToolbox;
        get toolboxDisplayStack(): $ItemStack;
        set chunkLoadingDistance(value: number);
        get secondaryHeadStack(): $ItemStack;
        get holdingSchedulesClient(): boolean;
        get possessedAndClient(): boolean;
        get toolbox(): $MountedToolbox;
        get forwardSignalStrength(): number;
    }
    export class $ServerPlayerPossessionAccess {
    }
    export interface $ServerPlayerPossessionAccess {
        railways$getPossessedConductor(): $ConductorEntity;
        railways$setPossessedConductor(arg0: $ConductorEntity): void;
    }
    export class $ConductorEntity$Job extends $Enum<$ConductorEntity$Job> {
        static values(): $ConductorEntity$Job[];
        static valueOf(arg0: string): $ConductorEntity$Job;
        static TOOLBOX_CARRIER: $ConductorEntity$Job;
        static REDSTONE_OPERATOR: $ConductorEntity$Job;
        static SPY: $ConductorEntity$Job;
        static REMOTE_CONTROL: $ConductorEntity$Job;
        static DEFAULT: $ConductorEntity$Job;
    }
    /**
     * Values that may be interpreted as {@link $ConductorEntity$Job}.
     */
    export type $ConductorEntity$Job_ = "redstone_operator" | "toolbox_carrier" | "remote_control" | "spy";
}
