import { $Int2ObjectArrayMap } from "@package/it/unimi/dsi/fastutil/ints";
import { $Pair } from "@package/org/apache/commons/lang3/tuple";
import { $GunAnimationStateContext } from "@package/com/tacz/guns/client/animation/statemachine";
import { $BedrockGunModel } from "@package/com/tacz/guns/client/model";
import { $ShellEjection, $LayerGunShow, $MuzzleFlash, $GunDisplay, $DamageStyle, $GunTransform, $AmmoCountStyle, $ControllableData } from "@package/com/tacz/guns/client/resource/pojo/display/gun";
import { $Optional, $List, $EnumMap } from "@package/java/util";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $AmmoParticle } from "@package/com/tacz/guns/client/resource/pojo/display/ammo";
import { $LuaAnimationStateMachine } from "@package/com/tacz/guns/api/client/animation/statemachine";
import { $LuaTable } from "@package/org/luaj/vm2";
import { $FireMode } from "@package/com/tacz/guns/api/item/gun";
import { $LaserConfig } from "@package/com/tacz/guns/client/resource/pojo/display";
import { $EnhancedGunDisplayInstance } from "@package/mod/chloeprime/gunsmithlib/client/gunpack_extension";
export * as pojo from "@package/com/tacz/guns/client/resource/pojo";
export * as index from "@package/com/tacz/guns/client/resource/index";

declare module "@package/com/tacz/guns/client/resource" {
    export class $GunDisplayInstance implements $EnhancedGunDisplayInstance {
        static create(arg0: $ResourceLocation_, arg1: $GunDisplay): $GunDisplayInstance;
        warmUpModel(): void;
        is3rdFixedHand(): boolean;
        warmUpRuntime(): void;
        getZoomModelFov(): number;
        getDamageStyle(): $DamageStyle;
        getAmmoCountStyle(): $AmmoCountStyle;
        isShowCrosshair(): boolean;
        getLaserConfig(): $LaserConfig;
        getModelTexture(): $ResourceLocation;
        getParticle(): $AmmoParticle;
        getTransform(): $GunTransform;
        warmUpLod(): void;
        getSounds(arg0: string): $ResourceLocation;
        gunsmith$getGunsmithLibExtension(): $Optional<any>;
        getIronZoom(): number;
        getHUDTexture(): $ResourceLocation;
        getTracerColor(): number[];
        getMuzzleFlash(): $MuzzleFlash;
        getPreloadSounds(): $List<$ResourceLocation>;
        getShellEjection(): $ShellEjection;
        getOffhandShow(): $LayerGunShow;
        getGunModel(): $BedrockGunModel;
        getHotbarShow(): $Int2ObjectArrayMap<$LayerGunShow>;
        getSlotTexture(): $ResourceLocation;
        getLodModel(): $Pair<$BedrockGunModel, $ResourceLocation>;
        getHudEmptyTexture(): $ResourceLocation;
        getAnimationStateMachine(): $LuaAnimationStateMachine<$GunAnimationStateContext>;
        gunsmith$acceptOverride(arg0: $GunDisplayInstance): void;
        getStateMachineParam(): $LuaTable;
        getThirdPersonAnimation(): string;
        getPlayerAnimator3rd(): $ResourceLocation;
        getControllableData(): $EnumMap<$FireMode, $ControllableData>;
        enablesTransparency(): boolean;
        get 3rdFixedHand(): boolean;
        get zoomModelFov(): number;
        get damageStyle(): $DamageStyle;
        get ammoCountStyle(): $AmmoCountStyle;
        get showCrosshair(): boolean;
        get laserConfig(): $LaserConfig;
        get modelTexture(): $ResourceLocation;
        get particle(): $AmmoParticle;
        get transform(): $GunTransform;
        get ironZoom(): number;
        get HUDTexture(): $ResourceLocation;
        get tracerColor(): number[];
        get muzzleFlash(): $MuzzleFlash;
        get preloadSounds(): $List<$ResourceLocation>;
        get shellEjection(): $ShellEjection;
        get offhandShow(): $LayerGunShow;
        get gunModel(): $BedrockGunModel;
        get hotbarShow(): $Int2ObjectArrayMap<$LayerGunShow>;
        get slotTexture(): $ResourceLocation;
        get lodModel(): $Pair<$BedrockGunModel, $ResourceLocation>;
        get hudEmptyTexture(): $ResourceLocation;
        get animationStateMachine(): $LuaAnimationStateMachine<$GunAnimationStateContext>;
        get stateMachineParam(): $LuaTable;
        get thirdPersonAnimation(): string;
        get playerAnimator3rd(): $ResourceLocation;
        get controllableData(): $EnumMap<$FireMode, $ControllableData>;
    }
}
