import { $LDLRegister } from "@package/com/lowdragmc/lowdraglib2/registry/annotation";
import { $Rect2i } from "@package/net/minecraft/client/renderer";
import { $Codec } from "@package/com/mojang/serialization";
import { $Tag_, $Tag, $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $IGuiTexture_, $IGuiTexture } from "@package/com/lowdragmc/lowdraglib2/gui/texture";
import { $StyleOrigin, $Stylesheet, $StyleRule, $StyleOrigin_, $StyleEngine, $BasicStyle, $Property, $LayoutStyle, $StyleBag } from "@package/com/lowdragmc/lowdraglib2/gui/ui/style";
import { $Size } from "@package/com/lowdragmc/lowdraglib2/math";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $AnimationEngine } from "@package/com/lowdragmc/lowdraglib2/utils/animation";
import { $AbstractContainerMenu } from "@package/net/minecraft/world/inventory";
import { $TaffyDisplay_ } from "@package/dev/vfyjxf/taffy/style";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $FocusNavigationEvent_, $ScreenRectangle } from "@package/net/minecraft/client/gui/navigation";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $Transform2D } from "@package/com/lowdragmc/lowdraglib2/gui/ui/data";
import { $IConfigurable, $IConfigurableHistory } from "@package/com/lowdragmc/lowdraglib2/configurator";
import { $RPCEvent, $RPCEmitter, $RPCEvent_ } from "@package/com/lowdragmc/lowdraglib2/gui/sync/rpc";
import { $TooltipComponent } from "@package/net/minecraft/world/inventory/tooltip";
import { $GuiEventListener } from "@package/net/minecraft/client/gui/components/events";
import { $Vector2f, $Matrix4f } from "@package/org/joml";
import { $IModularUIHolder } from "@package/com/lowdragmc/lowdraglib2/gui/holder";
import { $SyncValue, $UISyncManager } from "@package/com/lowdragmc/lowdraglib2/gui/sync";
import { $GUIContext } from "@package/com/lowdragmc/lowdraglib2/gui/ui/rendering";
import { $Map, $Set, $List, $List_ } from "@package/java/util";
import { $Configurator, $ConfiguratorGroup } from "@package/com/lowdragmc/lowdraglib2/configurator/ui";
import { $Supplier_, $Consumer_, $Function, $Consumer, $BiConsumer_, $Function_, $Supplier } from "@package/java/util/function";
import { $HolderLookup$Provider } from "@package/net/minecraft/core";
import { $IPersistedSerializable } from "@package/com/lowdragmc/lowdraglib2/syncdata";
import { $UIEventListener, $UIEventListener_, $UIEvent, $DragHandler } from "@package/com/lowdragmc/lowdraglib2/gui/ui/event";
import { $Class, $Object } from "@package/java/lang";
import { $StyleAnimation } from "@package/com/lowdragmc/lowdraglib2/gui/ui/style/animation";
import { $Event } from "@package/net/neoforged/bus/api";
import { $Pair } from "@package/oshi/util/tuples";
import { $NarratableEntry$NarrationPriority, $NarrationElementOutput, $NarratableEntry } from "@package/net/minecraft/client/gui/narration";
import { $Renderable } from "@package/net/minecraft/client/gui/components";
import { $ImmutableList } from "@package/com/google/common/collect";
import { $AutoRegistry$Holder, $AutoRegistry$LDLibRegister, $ILDLRegister, $AutoRegistry$Holder_ } from "@package/com/lowdragmc/lowdraglib2/registry";
import { $Pattern } from "@package/java/util/regex";
import { $TaffyLayoutStyle } from "@package/com/lowdragmc/lowdraglib2/gui/ui/layout";
import { $YogaDisplay_, $YogaOverflow_ } from "@package/org/appliedenergistics/yoga";
import { $Stream } from "@package/java/util/stream";
import { $Screen } from "@package/net/minecraft/client/gui/screens";
import { $ResourceLocation, $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $NodeId, $TaffyTree, $Layout } from "@package/dev/vfyjxf/taffy/tree";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $Font, $ComponentPath, $GuiGraphics } from "@package/net/minecraft/client/gui";
import { $Document, $Element } from "@package/org/w3c/dom";
import { $StreamCodec } from "@package/net/minecraft/network/codec";
export * as elements from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements";
export * as style from "@package/com/lowdragmc/lowdraglib2/gui/ui/style";
export * as data from "@package/com/lowdragmc/lowdraglib2/gui/ui/data";
export * as event from "@package/com/lowdragmc/lowdraglib2/gui/ui/event";
export * as layout from "@package/com/lowdragmc/lowdraglib2/gui/ui/layout";
export * as rendering from "@package/com/lowdragmc/lowdraglib2/gui/ui/rendering";
export * as utils from "@package/com/lowdragmc/lowdraglib2/gui/ui/utils";

declare module "@package/com/lowdragmc/lowdraglib2/gui/ui" {
    export class $UIElement implements $IConfigurable, $IPersistedSerializable, $ILDLRegister<$UIElement, $Supplier<$UIElement>> {
        name(): string;
        transform(arg0: $Consumer_<$Transform2D>): $UIElement;
        getClasses(): $Set<string>;
        addClass(arg0: string): $UIElement;
        getParent(): $UIElement;
        getId(): string;
        copy(): $UIElement;
        isActive(): boolean;
        layout(arg0: $Consumer_<$LayoutStyle>): $UIElement;
        style(arg0: $Consumer_<$BasicStyle>): $UIElement;
        getChildren(): $List<$UIElement>;
        removeChild(arg0: $UIElement): boolean;
        getElementName(): string;
        addChild(arg0: $UIElement): $UIElement;
        initScreen(arg0: number, arg1: number): void;
        getStyle(): $BasicStyle;
        isVisible(): boolean;
        addClasses(...arg0: string[]): $UIElement;
        select<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        select(arg0: string): $Stream<$UIElement>;
        removeEventListener(arg0: string, arg1: $UIEventListener_, arg2: boolean): void;
        removeEventListener(arg0: string, arg1: $UIEventListener_): void;
        addEventListener(arg0: string, arg1: $UIEventListener_, arg2: boolean): $UIElement;
        addEventListener(arg0: string, arg1: $UIEventListener_): $UIElement;
        hasClass(arg0: string): boolean;
        getLayout(): $LayoutStyle;
        setId(arg0: string): $UIElement;
        setAllowHitTest(arg0: boolean): $UIElement;
        getEditorName(): $Component;
        internalSetup(): void;
        isEditorVisible(): boolean;
        getLayoutStyle(): $LayoutStyle;
        canAddEditorChild(arg0: $AutoRegistry$Holder_<$LDLRegister, $UIElement, $Supplier_<$UIElement>>): boolean;
        getTaffyStyle(): $TaffyLayoutStyle;
        getEditorIcon(): $IGuiTexture;
        initEditorTemplate(): void;
        deserializeNBT(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        stopInteractionEventsPropagation(): $UIElement;
        setActive(arg0: boolean): $UIElement;
        isFocused(): boolean;
        static isKeyDown(arg0: number): boolean;
        blur(): void;
        isCulled(): boolean;
        getRegistry(): $AutoRegistry$LDLibRegister<$UIElement, $Supplier<$UIElement>>;
        sendMessage(arg0: string, arg1: $CompoundTag_): void;
        sendMessage(arg0: string): void;
        focus(): void;
        removeSyncValue(arg0: $SyncValue<never>): $UIElement;
        onMessage(arg0: string, arg1: $BiConsumer_<$UIElement, $CompoundTag>): $UIElement;
        disabled(): $UIElement;
        getDebugInfo(): $List<$Component>;
        beforeDeserialize(): void;
        buildConfigurator(arg0: $ConfiguratorGroup): void;
        drawContents(arg0: $GUIContext): void;
        isMouseOver(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        isMouseOver(arg0: number, arg1: number): boolean;
        getModularUI(): $ModularUI;
        clearLocalStylesheets(): $UIElement;
        addServerEventListener(arg0: string, arg1: $UIEventListener_): $UIElement;
        addServerEventListener(arg0: string, arg1: $UIEventListener_, arg2: boolean): $UIElement;
        getEditorVisibleChildren(): $List<$UIElement>;
        removeLocalStylesheet(arg0: $Stylesheet): $UIElement;
        getWorldToLocalPose(): $Matrix4f;
        getWorldMouseNormal(arg0: number, arg1: number): $Vector2f;
        adaptPositionToElement(arg0: $UIElement): void;
        adaptPositionToScreen(): void;
        getBaubleServerEvent(arg0: string): $RPCEvent;
        moveInlineAsDefault(): $UIElement;
        removeServerEventListener(arg0: string, arg1: $UIEventListener_, arg2: boolean): $UIElement;
        removeServerEventListener(arg0: string, arg1: $UIEventListener_): $UIElement;
        drawInBackgroundInternal(arg0: $GUIContext): void;
        drawBackgroundAdditional(arg0: $GUIContext): void;
        getLocalToWorldPose(): $Matrix4f;
        getLocalMouseNormal(arg0: number, arg1: number): $Vector2f;
        getLocalStylesheets(): $List<$Stylesheet>;
        getCaptureListeners(arg0: string): $List<$UIEventListener>;
        getFirstAncestorOfType<T extends $UIElement>(arg0: $Class<T>): T;
        getCaptureServerEvent(arg0: string): $RPCEvent;
        drawBackgroundTexture(arg0: $GUIContext): void;
        clearSortedChildrenCache(): void;
        clearStructurePathCache(): void;
        clearAllExternalChildren(): void;
        isIntersectWithPoint(arg0: number, arg1: number): boolean;
        drawBackgroundOverlay(arg0: $GUIContext): void;
        markTaffyStyleDirty(): void;
        worldToLocalLayoutOffset(arg0: $Vector2f): $Vector2f;
        isFocusable(): boolean;
        setFocusable(arg0: boolean): $UIElement;
        serverTick(): void;
        setVisible(arg0: boolean): $UIElement;
        animation(arg0: $Consumer_<$StyleAnimation>): $UIElement;
        animation(): $StyleAnimation;
        isInternalUI(): boolean;
        getLocalMouse(arg0: number, arg1: number): $Vector2f;
        getTaffyLayout(): $Layout;
        removeRPCEvent(arg0: $RPCEvent_): $UIElement;
        getSafeChildren(): $List<$UIElement>;
        getPositionX(): number;
        getContentX(): number;
        getContentY(): number;
        selectRegex(arg0: string): $Stream<$UIElement>;
        selectRegex<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        getFlattenChildren(): $List<$UIElement>;
        getStructurePath(): $ImmutableList<$UIElement>;
        addLocalStylesheet(arg0: $Stylesheet): $UIElement;
        addLocalStylesheet(arg0: string): $UIElement;
        getTaffyTree(): $TaffyTree;
        appendExtraAreas(arg0: $List_<$Rect2i>): void;
        getContentWidth(): number;
        isSelfOrChildHover(): boolean;
        getSortedChildren(): $List<$UIElement>;
        getSizeWidth(): number;
        /**
         * @deprecated
         */
        setOverflow(arg0: $YogaOverflow_): $UIElement;
        worldToLocal(arg0: $Vector2f): $Vector2f;
        getPositionY(): number;
        getSizeHeight(): number;
        addSyncValue(arg0: $SyncValue<never>): $UIElement;
        addSyncValue(arg0: $Function_<$UIElement, $SyncValue<never>>): $UIElement;
        selfAndAllChildren(): $Stream<$UIElement>;
        clearPoseCache(): void;
        isDisplayed(): boolean;
        getPaddingY(): number;
        static isMouseOverRect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number): boolean;
        isAllowHitTest(): boolean;
        getWorldMouse(arg0: number, arg1: number): $Vector2f;
        removeClass(arg0: string): $UIElement;
        addRPCEvent(arg0: $Function_<$UIElement, $RPCEvent>): $RPCEmitter;
        addRPCEvent(arg0: $RPCEvent_): $RPCEmitter;
        isAncestorOf(arg0: $UIElement): boolean;
        clearLayoutCache(): void;
        onClassIdChanged(): void;
        getPaddingHeight(): number;
        allChildrenStream(): $Stream<$UIElement>;
        drawInBackground(arg0: $GUIContext): void;
        getMarginLeft(): number;
        getSiblingIndex(): number;
        getStyleBag(): $StyleBag;
        addEditorChild(arg0: $UIElement, arg1: number): void;
        getMarginBottom(): number;
        getMarginRight(): number;
        getPaddingWidth(): number;
        removeAllRules(): void;
        onStyleChanged(): void;
        isMouseOverElement(arg0: number, arg1: number): boolean;
        markAsInternal(): $UIElement;
        setOverflowVisible(arg0: boolean): $UIElement;
        getMarginTop(): number;
        clearAllChildren(): void;
        isChildFocused(): boolean;
        addStyleRules(arg0: $List_<$StyleRule>): void;
        worldToLocalNormal(arg0: $Vector2f): $Vector2f;
        localToWorldNormal(arg0: $Vector2f): $Vector2f;
        removeStyleRules(arg0: $List_<$StyleRule>): void;
        isMouseOverContent(arg0: number, arg1: number): boolean;
        removeClasses(...arg0: string[]): $UIElement;
        setEnforceFocus(arg0: $Consumer_<$UIEvent>): $UIElement;
        localToWorld(arg0: $Vector2f): $Vector2f;
        hasEventListener(arg0: string, arg1: $UIEventListener_): boolean;
        hasEventListener(arg0: string, arg1: $UIEventListener_, arg2: boolean): boolean;
        isOverlapping(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        getBubbleListeners(arg0: string): $List<$UIEventListener>;
        getLayoutX(): number;
        lss(arg0: string, arg1: $Object): $UIElement;
        lss(arg0: string, arg1: $Object, arg2: $StyleOrigin_): $UIElement;
        removeSelf(): boolean;
        sendEvent(arg0: $RPCEvent_, ...arg1: $Object[]): void;
        sendEvent<T>(arg0: $RPCEvent_, arg1: $Consumer_<T>, ...arg2: $Object[]): void;
        offMessage(arg0: string, arg1: $Consumer_<$CompoundTag>): $UIElement;
        hasChild(arg0: $UIElement): boolean;
        hitTest(arg0: number, arg1: number): $Pair<$UIElement, number>;
        static isAltDown(): boolean;
        addChildAt(arg0: $UIElement, arg1: number): $UIElement;
        getNodeId(): $NodeId;
        startDrag(arg0: $Object, arg1: $IGuiTexture_): $DragHandler;
        /**
         * @deprecated
         */
        setDisplay(arg0: $YogaDisplay_): $UIElement;
        setDisplay(arg0: $TaffyDisplay_): $UIElement;
        setDisplay(arg0: boolean): $UIElement;
        screenTick(): void;
        getStyles(): $List<$Style>;
        selectId(arg0: string): $Stream<$UIElement>;
        selectId<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        getLayoutY(): number;
        setClasses(...arg0: string[]): $UIElement;
        hasParent(): boolean;
        selfCall(arg0: $Consumer_<$UIElement>): $UIElement;
        loadXml(arg0: $Element): void;
        isHover(): boolean;
        getContentHeight(): number;
        getPaddingX(): number;
        static isShiftDown(): boolean;
        isMouseDown(arg0: number): boolean;
        static isCtrlDown(): boolean;
        addChildren(...arg0: $UIElement[]): $UIElement;
        createDirectConfigurator(): $Configurator;
        createHistoryRecorder(): $IConfigurableHistory;
        getConfigurableName(): string;
        deserializeAdditionalNBT(arg0: $Tag_, arg1: $HolderLookup$Provider): void;
        serializeAdditionalNBT(arg0: $HolderLookup$Provider): $Tag;
        writeToBuff(arg0: $ByteBuf): void;
        afterSerialize(): void;
        readFromBuff(arg0: $ByteBuf): void;
        afterDeserialize(): void;
        beforeSerialize(): void;
        group(): string;
        getRegisterUI(): $LDLRegister;
        getRegistryHolderOptional(): ($AutoRegistry$Holder<$LDLRegister, $CompoundTag, $Supplier<$UIElement>>) | undefined;
        isLDLRegister(): boolean;
        getRegistryHolder(): $AutoRegistry$Holder<$LDLRegister, $CompoundTag, $Supplier<$UIElement>>;
        getChatComponent(): $Component;
        getTranslateKey(): string;
        registryName(): $ResourceLocation;
        static CODEC: $Codec<$UIElement>;
        static EMPTY_LAYOUT: $Layout;
        constructor();
        get parent(): $UIElement;
        get children(): $List<$UIElement>;
        get elementName(): string;
        get editorName(): $Component;
        get editorVisible(): boolean;
        get layoutStyle(): $LayoutStyle;
        get taffyStyle(): $TaffyLayoutStyle;
        get editorIcon(): $IGuiTexture;
        get focused(): boolean;
        get culled(): boolean;
        get registry(): $AutoRegistry$LDLibRegister<$UIElement, $Supplier<$UIElement>>;
        get debugInfo(): $List<$Component>;
        get modularUI(): $ModularUI;
        get editorVisibleChildren(): $List<$UIElement>;
        get worldToLocalPose(): $Matrix4f;
        get localToWorldPose(): $Matrix4f;
        get localStylesheets(): $List<$Stylesheet>;
        get internalUI(): boolean;
        get taffyLayout(): $Layout;
        get safeChildren(): $List<$UIElement>;
        get positionX(): number;
        get contentX(): number;
        get contentY(): number;
        get flattenChildren(): $List<$UIElement>;
        get structurePath(): $ImmutableList<$UIElement>;
        get taffyTree(): $TaffyTree;
        get contentWidth(): number;
        get selfOrChildHover(): boolean;
        get sortedChildren(): $List<$UIElement>;
        get sizeWidth(): number;
        set overflow(value: $YogaOverflow_);
        get positionY(): number;
        get sizeHeight(): number;
        get displayed(): boolean;
        get paddingY(): number;
        get paddingHeight(): number;
        get marginLeft(): number;
        get siblingIndex(): number;
        get styleBag(): $StyleBag;
        get marginBottom(): number;
        get marginRight(): number;
        get paddingWidth(): number;
        set overflowVisible(value: boolean);
        get marginTop(): number;
        get childFocused(): boolean;
        set enforceFocus(value: $Consumer_<$UIEvent>);
        get layoutX(): number;
        static get altDown(): boolean;
        get nodeId(): $NodeId;
        get styles(): $List<$Style>;
        get layoutY(): number;
        get hover(): boolean;
        get contentHeight(): number;
        get paddingX(): number;
        static get shiftDown(): boolean;
        static get ctrlDown(): boolean;
        get configurableName(): string;
        get registerUI(): $LDLRegister;
        get registryHolderOptional(): ($AutoRegistry$Holder<$LDLRegister, $CompoundTag, $Supplier<$UIElement>>) | undefined;
        get LDLRegister(): boolean;
        get registryHolder(): $AutoRegistry$Holder<$LDLRegister, $CompoundTag, $Supplier<$UIElement>>;
        get chatComponent(): $Component;
        get translateKey(): string;
    }
    export class $UITemplate {
        static of(arg0: $UIElement, ...arg1: $ResourceLocation_[]): $UITemplate;
        static of(arg0: $CompoundTag_, arg1: string, ...arg2: $ResourceLocation_[]): $UITemplate;
        static of(arg0: $UIElement): $UITemplate;
        copy(): $UITemplate;
        getData(): $CompoundTag;
        setData(arg0: $CompoundTag_): void;
        static missing(): $UITemplate;
        getAllStylesheets(): $List<$Stylesheet>;
        createUI(): $UI;
        getCustomStylesheet(): $Stylesheet;
        initUI(arg0: $UIElement): void;
        getBuiltinStyles(): string;
        getStylesheets(): $List<$ResourceLocation>;
        setBuiltinStyles(arg0: string): void;
        copyStylesFrom(arg0: $UITemplate): void;
        static CODEC: $Codec<$UITemplate>;
        static STREAM_CODEC: $StreamCodec<$FriendlyByteBuf, $UITemplate>;
        get allStylesheets(): $List<$Stylesheet>;
        get customStylesheet(): $Stylesheet;
        get stylesheets(): $List<$ResourceLocation>;
    }
    export class $ModularUI$ModularUIWidget implements $GuiEventListener, $NarratableEntry, $Renderable, $IModularUIHolder {
        renderUISpacing(arg0: $UIElement, arg1: $GuiGraphics): void;
        keyPressed(arg0: number, arg1: number, arg2: number): boolean;
        setFocused(arg0: boolean): void;
        mouseMoved(arg0: number, arg1: number): void;
        charTyped(arg0: string, arg1: number): boolean;
        isHovered(): boolean;
        render(arg0: $GuiGraphics, arg1: number, arg2: number, arg3: number): void;
        isFocused(): boolean;
        getRectangle(): $ScreenRectangle;
        isMouseOver(arg0: number, arg1: number): boolean;
        updateNarration(arg0: $NarrationElementOutput): void;
        narrationPriority(): $NarratableEntry$NarrationPriority;
        mouseScrolled(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        mouseDragged(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): boolean;
        mouseReleased(arg0: number, arg1: number, arg2: number): boolean;
        keyReleased(arg0: number, arg1: number, arg2: number): boolean;
        mouseClicked(arg0: number, arg1: number, arg2: number): boolean;
        getModularUI(): $ModularUI;
        getCurrentFocusPath(): $ComponentPath;
        nextFocusPath(arg0: $FocusNavigationEvent_): $ComponentPath;
        isActive(): boolean;
        getSyncManager(): $UISyncManager;
        hasModularUI(): boolean;
        getTabOrderGroup(): number;
        writeInitialData(arg0: $RegistryFriendlyByteBuf): void;
        readInitialData(arg0: $RegistryFriendlyByteBuf): void;
        constructor(arg0: $ModularUI);
        get hovered(): boolean;
        get rectangle(): $ScreenRectangle;
        get modularUI(): $ModularUI;
        get currentFocusPath(): $ComponentPath;
        get active(): boolean;
        get syncManager(): $UISyncManager;
        get tabOrderGroup(): number;
    }
    export class $UI$DynamicSizeProvider {
    }
    export interface $UI$DynamicSizeProvider extends $Function<$Size, $Size> {
        apply(arg0: $Size): $Size;
    }
    /**
     * Values that may be interpreted as {@link $UI$DynamicSizeProvider}.
     */
    export type $UI$DynamicSizeProvider_ = ((arg0: $Size) => $Size);
    export class $UI {
        static of(): $UI;
        static of(arg0: $Document): $UI;
        static of(arg0: $UIElement, arg1: $List_<$Stylesheet>, arg2: $UI$DynamicSizeProvider_): $UI;
        static of(arg0: $UIElement, arg1: $List_<$Stylesheet>): $UI;
        static of(arg0: $UIElement, ...arg1: $Stylesheet[]): $UI;
        static of(arg0: $UIElement, ...arg1: $ResourceLocation_[]): $UI;
        static of(arg0: $UIElement, ...arg1: string[]): $UI;
        static of(arg0: $UIElement, arg1: $UI$DynamicSizeProvider_): $UI;
        static of(arg0: $UIElement): $UI;
        static empty(): $UI;
        getRootElement(): $UIElement;
        getDynamicSize(): $UI$DynamicSizeProvider;
        select<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        select(arg0: string): $Stream<$UIElement>;
        selectRegex(arg0: string): $Stream<$UIElement>;
        selectRegex<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        selectId(arg0: string): $Stream<$UIElement>;
        selectId<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        toTemplate(): $UITemplate;
        getStylesheets(): $List<$Stylesheet>;
        stylesheets: $List<$Stylesheet>;
        dynamicSize: $UI$DynamicSizeProvider;
        rootElement: $UIElement;
    }
    export class $ModularUI {
        static of(arg0: $UI, arg1: $Player): $ModularUI;
        static of(arg0: $UI): $ModularUI;
        init(arg0: number, arg1: number): void;
        tick(): void;
        getWidget(): $ModularUI$ModularUIWidget;
        onRemoved(): void;
        setFocused(arg0: boolean): void;
        select<T>(arg0: string, arg1: $Class<T>): $Stream<T>;
        select(arg0: string): $Stream<$UIElement>;
        setScreen(arg0: $Screen): void;
        getFocusedElement(): $UIElement;
        getElementById(arg0: string): $UIElement;
        getWidth(): number;
        setMenu(arg0: $AbstractContainerMenu): void;
        isFocused(): boolean;
        clearFocus(): void;
        setDebugMode(arg0: boolean): void;
        setScreenAndInit(arg0: $Screen): void;
        getTooltipFont(): $Font;
        enableDebugger(arg0: boolean): void;
        getTooltipTexts(): $List<$Component>;
        getLastMouseX(): number;
        getAnimationEngine(): $AnimationEngine;
        getLayoutWidth(): number;
        hasElementWithId(arg0: string): boolean;
        isTickWhileRending(): boolean;
        setAllowDebugMode(arg0: boolean): void;
        getAllElementsById(): $Map<string, $List<$UIElement>>;
        setDrawDrag(arg0: boolean): void;
        isAllowDebugMode(): boolean;
        isDrawTooltips(): boolean;
        getElementsById(arg0: string): $List<$UIElement>;
        setDrawTooltips(arg0: boolean): void;
        getLastMouseDownY(): number;
        cleanTooltip(): void;
        getElementsByType<T extends $UIElement>(arg0: $Class<T>): $List<T>;
        getLastMouseY(): number;
        getLastMouseDownX(): number;
        getAllElements(): $List<$UIElement>;
        getLayoutHeight(): number;
        getMenu(): $AbstractContainerMenu;
        getElementByIdPattern(arg0: $Pattern): $UIElement;
        getElementsByIdRegex(arg0: string): $List<$UIElement>;
        getLastMouseDragElement(): $UIElement;
        getLastMouseClickButton(): number;
        getLastPressedModifiers(): number;
        getElementByIdRegex(arg0: string): $UIElement;
        getLastHoveredElements(): $List<$UIElement>;
        getLastMouseDownElement(): $UIElement;
        getElementsByIdContains(arg0: string): $List<$UIElement>;
        getElementsByIdStartsWith(arg0: string): $List<$UIElement>;
        getLastMouseMoveElement(): $UIElement;
        getLastMouseClickElement(): $UIElement;
        getElementsByIdEndsWith(arg0: string): $List<$UIElement>;
        getElementCountById(arg0: string): number;
        getLastPressedKeyCode(): number;
        getLastPressedScanCode(): number;
        getLastMouseClickTime(): number;
        getElementsByIdPattern(arg0: $Pattern): $List<$UIElement>;
        setTickWhileRending(arg0: boolean): void;
        getAllElementsByType(): $Map<$Class<never>, $List<$UIElement>>;
        getScreenWidth(): number;
        getScreenHeight(): number;
        shouldCloseOnKeyInventory(arg0: boolean): $ModularUI;
        shouldCloseOnKeyInventory(): boolean;
        getGuiExtraAreas(): $List<$Rect2i>;
        shouldCloseOnEsc(): boolean;
        shouldCloseOnEsc(arg0: boolean): $ModularUI;
        isDrawDrag(): boolean;
        getHeight(): number;
        getTooltipComponent(): $TooltipComponent;
        getLastMouseDownButton(): number;
        requestFocus(arg0: $UIElement): void;
        getLastHoveredElement(): $UIElement;
        getTaffyTree(): $TaffyTree;
        getLastDrawPose(): $Matrix4f;
        getDragHandler(): $DragHandler;
        unregisterElement(arg0: $UIElement): void;
        getStyleEngine(): $StyleEngine;
        registerElement(arg0: $UIElement): void;
        getTickCounter(): number;
        getLeftPos(): number;
        getTopPos(): number;
        setHoverTooltip(arg0: $List_<$Component_>, arg1: $ItemStack_, arg2: $Font, arg3: $TooltipComponent): void;
        tickServer(): void;
        getTooltipStack(): $ItemStack;
        isDebugMode(): boolean;
        getScreen(): $Screen;
        syncManager: $UISyncManager;
        ui: $UI;
        player: $Player;
        constructor(arg0: $UI);
        constructor(arg0: $UI, arg1: $Player);
        get widget(): $ModularUI$ModularUIWidget;
        get focusedElement(): $UIElement;
        get width(): number;
        set screenAndInit(value: $Screen);
        get tooltipFont(): $Font;
        get tooltipTexts(): $List<$Component>;
        get lastMouseX(): number;
        get animationEngine(): $AnimationEngine;
        get layoutWidth(): number;
        get allElementsById(): $Map<string, $List<$UIElement>>;
        get lastMouseDownY(): number;
        get lastMouseY(): number;
        get lastMouseDownX(): number;
        get allElements(): $List<$UIElement>;
        get layoutHeight(): number;
        get lastMouseDragElement(): $UIElement;
        get lastMouseClickButton(): number;
        get lastPressedModifiers(): number;
        get lastHoveredElements(): $List<$UIElement>;
        get lastMouseDownElement(): $UIElement;
        get lastMouseMoveElement(): $UIElement;
        get lastMouseClickElement(): $UIElement;
        get lastPressedKeyCode(): number;
        get lastPressedScanCode(): number;
        get lastMouseClickTime(): number;
        get allElementsByType(): $Map<$Class<never>, $List<$UIElement>>;
        get screenWidth(): number;
        get screenHeight(): number;
        get guiExtraAreas(): $List<$Rect2i>;
        get height(): number;
        get tooltipComponent(): $TooltipComponent;
        get lastMouseDownButton(): number;
        get lastHoveredElement(): $UIElement;
        get taffyTree(): $TaffyTree;
        get lastDrawPose(): $Matrix4f;
        get dragHandler(): $DragHandler;
        get styleEngine(): $StyleEngine;
        get tickCounter(): number;
        get leftPos(): number;
        get topPos(): number;
        get tooltipStack(): $ItemStack;
    }
    export class $Style implements $IConfigurable, $IPersistedSerializable {
        getValue<T>(arg0: $Property<T>): (T) | undefined;
        getValue<T>(arg0: $Property<T>, arg1: $StyleOrigin_): T;
        getDefault<T>(arg0: $Property<T>): T;
        set<T>(arg0: $StyleOrigin_, arg1: $Property<T>, arg2: T): void;
        set<T>(arg0: $Property<T>, arg1: T): void;
        setDefault<T>(arg0: $Property<T>, arg1: T): void;
        copyFrom(arg0: $Style): void;
        deserializeNBT(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static pipeline<T extends $Style>(arg0: $StyleOrigin_, arg1: T, arg2: $Consumer_<T>): T;
        setInline<T>(arg0: $Property<T>, arg1: T): void;
        getInline<T>(arg0: $Property<T>): T;
        beforeDeserialize(): void;
        buildConfigurator(arg0: $ConfiguratorGroup): void;
        setPipelineState(arg0: $StyleOrigin_): void;
        static defaultPipeline<T extends $Style>(arg0: T, arg1: $Consumer_<T>): T;
        getValueSave<T>(arg0: $Property<T>): T;
        getPipelineState(): $StyleOrigin;
        getImportant<T>(arg0: $Property<T>): T;
        getPropertiesList(): $ImmutableList<$Property<never>>;
        static inlinePipeline<T extends $Style>(arg0: T, arg1: $Consumer_<T>): T;
        valueGetter<T>(arg0: $Property<T>): $Supplier<T>;
        setImportant<T>(arg0: $Property<T>, arg1: T): void;
        valueSetter<T>(arg0: $Property<T>): $Consumer<T>;
        static importantPipeline<T extends $Style>(arg0: T, arg1: $Consumer_<T>): T;
        createDirectConfigurator(): $Configurator;
        createHistoryRecorder(): $IConfigurableHistory;
        getConfigurableName(): string;
        deserializeAdditionalNBT(arg0: $Tag_, arg1: $HolderLookup$Provider): void;
        serializeAdditionalNBT(arg0: $HolderLookup$Provider): $Tag;
        writeToBuff(arg0: $ByteBuf): void;
        afterSerialize(): void;
        readFromBuff(arg0: $ByteBuf): void;
        afterDeserialize(): void;
        beforeSerialize(): void;
        holder: $UIElement;
        constructor(arg0: $UIElement);
        get propertiesList(): $ImmutableList<$Property<never>>;
        get configurableName(): string;
    }
    export class $UITemplate$CreateUI extends $Event {
        template: $UITemplate;
        ui: $UI;
        constructor(arg0: $UITemplate, arg1: $UI);
    }
}
