import { $Consumer_, $Supplier_ } from "@package/java/util/function";
import { $FloatOptional } from "@package/org/appliedenergistics/yoga/numeric";
import { $YogaOverflow_ } from "@package/org/appliedenergistics/yoga";
import { $UIElement } from "@package/com/lowdragmc/lowdraglib2/gui/ui";
import { $TaffySize, $TaffyRect } from "@package/dev/vfyjxf/taffy/geometry";
import { $FlexDirection_, $TaffyDisplay_, $TaffyStyle, $GridAutoFlow_, $TaffyPosition_, $AlignItems_, $TaffyDirection_, $AlignContent_, $FlexWrap_, $LengthPercentageAuto, $TaffyDimension, $LengthPercentage } from "@package/dev/vfyjxf/taffy/style";
import { $LPSize_, $GridTemplateAreas_, $LPARect_, $Grid_, $GridTemplate_, $GridAuto_ } from "@package/com/lowdragmc/lowdraglib2/gui/ui/data";

declare module "@package/com/lowdragmc/lowdraglib2/gui/ui/layout" {
    export class $TaffyLayoutStyle$LPARectData {
        setAll(arg0: $LengthPercentageAuto): void;
        setBottom(arg0: $LengthPercentageAuto): void;
        setRight(arg0: $LengthPercentageAuto): void;
        setTop(arg0: $LengthPercentageAuto): void;
        setLeft(arg0: $LengthPercentageAuto): void;
        onChanged(): void;
        setRect(arg0: $LPARect_): void;
        setVertical(arg0: $LengthPercentageAuto): void;
        setHorizontal(arg0: $LengthPercentageAuto): void;
        constructor(arg0: $Supplier_<$TaffyRect<$LengthPercentageAuto>>, arg1: $Consumer_<$TaffyRect<$LengthPercentageAuto>>);
        set all(value: $LengthPercentageAuto);
        set bottom(value: $LengthPercentageAuto);
        set right(value: $LengthPercentageAuto);
        set top(value: $LengthPercentageAuto);
        set left(value: $LengthPercentageAuto);
        set rect(value: $LPARect_);
        set vertical(value: $LengthPercentageAuto);
        set horizontal(value: $LengthPercentageAuto);
    }
    export class $TaffyLayoutStyle$LPSizeData {
        setAll(arg0: $LengthPercentageAuto): void;
        setSize(arg0: $LPSize_): void;
        onChanged(): void;
        setVertical(arg0: $LengthPercentageAuto): void;
        setHorizontal(arg0: $LengthPercentageAuto): void;
        static toLP(arg0: $LengthPercentageAuto): $LengthPercentage;
        constructor(arg0: $Supplier_<$TaffySize<$LengthPercentage>>, arg1: $Consumer_<$TaffySize<$LengthPercentage>>);
        set all(value: $LengthPercentageAuto);
        set size(value: $LPSize_);
        set vertical(value: $LengthPercentageAuto);
        set horizontal(value: $LengthPercentageAuto);
    }
    export class $TaffyLayoutStyle$LPRectData {
        setAll(arg0: $LengthPercentageAuto): void;
        setBottom(arg0: $LengthPercentageAuto): void;
        setRight(arg0: $LengthPercentageAuto): void;
        setTop(arg0: $LengthPercentageAuto): void;
        setLeft(arg0: $LengthPercentageAuto): void;
        onChanged(): void;
        setRect(arg0: $LPARect_): void;
        setVertical(arg0: $LengthPercentageAuto): void;
        setHorizontal(arg0: $LengthPercentageAuto): void;
        static toLP(arg0: $LengthPercentageAuto): $LengthPercentage;
        static lpaEquals(arg0: $LengthPercentageAuto, arg1: $LengthPercentage): boolean;
        constructor(arg0: $Supplier_<$TaffyRect<$LengthPercentage>>, arg1: $Consumer_<$TaffyRect<$LengthPercentage>>);
        set all(value: $LengthPercentageAuto);
        set bottom(value: $LengthPercentageAuto);
        set right(value: $LengthPercentageAuto);
        set top(value: $LengthPercentageAuto);
        set left(value: $LengthPercentageAuto);
        set rect(value: $LPARect_);
        set vertical(value: $LengthPercentageAuto);
        set horizontal(value: $LengthPercentageAuto);
    }
    export class $TaffyLayoutStyle {
        setDisplay(arg0: $TaffyDisplay_): void;
        setDirection(arg0: $TaffyDirection_): void;
        setFlex(arg0: $FloatOptional): void;
        setBottom(arg0: $LengthPercentageAuto): void;
        setRight(arg0: $LengthPercentageAuto): void;
        setTop(arg0: $LengthPercentageAuto): void;
        setLeft(arg0: $LengthPercentageAuto): void;
        setPosition(arg0: $TaffyPosition_): void;
        setWidth(arg0: $TaffyDimension): void;
        setHeight(arg0: $TaffyDimension): void;
        setMaxWidth(arg0: $TaffyDimension): void;
        setMaxHeight(arg0: $TaffyDimension): void;
        setFlexGrow(arg0: $FloatOptional): void;
        setMinHeight(arg0: $TaffyDimension): void;
        setMinWidth(arg0: $TaffyDimension): void;
        setFlexShrink(arg0: $FloatOptional): void;
        setFlexBasis(arg0: $TaffyDimension): void;
        setAlignContent(arg0: $AlignContent_): void;
        setFlexDirection(arg0: $FlexDirection_): void;
        setAlignItems(arg0: $AlignItems_): void;
        setAlignSelf(arg0: $AlignItems_): void;
        setJustifyContent(arg0: $AlignContent_): void;
        setGridRow(arg0: $Grid_): void;
        setJustifySelf(arg0: $AlignItems_): void;
        setOverFlow(arg0: $YogaOverflow_): void;
        setAspectRate(arg0: $FloatOptional): void;
        setGridAutoRows(arg0: $GridAuto_): void;
        setGridAutoColumns(arg0: $GridAuto_): void;
        setGridAutoFlow(arg0: $GridAutoFlow_): void;
        setJustifyItems(arg0: $AlignItems_): void;
        setGridColumn(arg0: $Grid_): void;
        setFlexWrap(arg0: $FlexWrap_): void;
        setGridTemplateAreas(arg0: $GridTemplateAreas_): void;
        setGridTemplateRows(arg0: $GridTemplate_): void;
        setGridTemplateColumns(arg0: $GridTemplate_): void;
        padding: $TaffyLayoutStyle$LPRectData;
        margin: $TaffyLayoutStyle$LPARectData;
        static DEFAULT_TAFFY_STYLE: $TaffyStyle;
        gap: $TaffyLayoutStyle$LPSizeData;
        style: $TaffyStyle;
        element: $UIElement;
        constructor(arg0: $UIElement);
        set display(value: $TaffyDisplay_);
        set direction(value: $TaffyDirection_);
        set flex(value: $FloatOptional);
        set bottom(value: $LengthPercentageAuto);
        set right(value: $LengthPercentageAuto);
        set top(value: $LengthPercentageAuto);
        set left(value: $LengthPercentageAuto);
        set position(value: $TaffyPosition_);
        set width(value: $TaffyDimension);
        set height(value: $TaffyDimension);
        set maxWidth(value: $TaffyDimension);
        set maxHeight(value: $TaffyDimension);
        set flexGrow(value: $FloatOptional);
        set minHeight(value: $TaffyDimension);
        set minWidth(value: $TaffyDimension);
        set flexShrink(value: $FloatOptional);
        set flexBasis(value: $TaffyDimension);
        set alignContent(value: $AlignContent_);
        set flexDirection(value: $FlexDirection_);
        set alignItems(value: $AlignItems_);
        set alignSelf(value: $AlignItems_);
        set justifyContent(value: $AlignContent_);
        set gridRow(value: $Grid_);
        set justifySelf(value: $AlignItems_);
        set overFlow(value: $YogaOverflow_);
        set aspectRate(value: $FloatOptional);
        set gridAutoRows(value: $GridAuto_);
        set gridAutoColumns(value: $GridAuto_);
        set gridAutoFlow(value: $GridAutoFlow_);
        set justifyItems(value: $AlignItems_);
        set gridColumn(value: $Grid_);
        set flexWrap(value: $FlexWrap_);
        set gridTemplateAreas(value: $GridTemplateAreas_);
        set gridTemplateRows(value: $GridTemplate_);
        set gridTemplateColumns(value: $GridTemplate_);
    }
}
