import { $FabricEntitySelectorReader } from "@package/net/fabricmc/fabric/api/command/v2";
import { $Component } from "@package/net/minecraft/network/chat";
import { $CompletableFuture } from "@package/java/util/concurrent";
import { $StringReader } from "@package/com/mojang/brigadier";
import { $EntityType_, $Entity } from "@package/net/minecraft/world/entity";
import { $List, $UUID_, $List_ } from "@package/java/util";
import { $MinMaxBounds$Doubles, $WrappedMinMaxBounds_, $MinMaxBounds$Ints_, $MinMaxBounds$Doubles_, $WrappedMinMaxBounds, $MinMaxBounds$Ints } from "@package/net/minecraft/advancements/critereon";
import { $CommandSourceStack } from "@package/net/minecraft/commands";
import { $Predicate, $Consumer_, $BiConsumer, $Consumer, $BiConsumer_, $BiFunction, $Predicate_, $Function_, $BiFunction_ } from "@package/java/util/function";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $DynamicCommandExceptionType, $SimpleCommandExceptionType } from "@package/com/mojang/brigadier/exceptions";
import { $Suggestions, $SuggestionsBuilder } from "@package/com/mojang/brigadier/suggestion";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $AABB_, $Vec3 } from "@package/net/minecraft/world/phys";
export * as options from "@package/net/minecraft/commands/arguments/selector/options";

declare module "@package/net/minecraft/commands/arguments/selector" {
    export class $EntitySelectorParser implements $FabricEntitySelectorReader {
        isLimited(): boolean;
        parse(): $EntitySelector;
        getLevel(): $MinMaxBounds$Ints;
        setLevel(arg0: $MinMaxBounds$Ints_): void;
        getOrder(): $BiConsumer<$Vec3, $List<$Entity>>;
        getY(): number;
        getX(): number;
        getDistance(): $MinMaxBounds$Doubles;
        setDistance(arg0: $MinMaxBounds$Doubles_): void;
        getReader(): $StringReader;
        setOrder(arg0: $BiConsumer_<$Vec3, $List<$Entity>>): void;
        getSelector(): $EntitySelector;
        getZ(): number;
        parseSelector(): void;
        isSorted(): boolean;
        setX(arg0: number): void;
        setZ(arg0: number): void;
        setY(arg0: number): void;
        setHasGamemodeEquals(arg0: boolean): void;
        setHasTeamNotEquals(arg0: boolean): void;
        isTypeLimitedInversely(): boolean;
        hasGamemodeNotEquals(): boolean;
        setHasGamemodeNotEquals(arg0: boolean): void;
        setHasNameNotEquals(arg0: boolean): void;
        setTypeLimitedInversely(): void;
        setIncludesEntities(arg0: boolean): void;
        shouldInvertValue(): boolean;
        setSuggestions(arg0: $BiFunction_<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>): void;
        setWorldLimited(): void;
        hasNameEquals(): boolean;
        hasNameNotEquals(): boolean;
        setHasNameEquals(arg0: boolean): void;
        hasAdvancements(): boolean;
        setHasScores(arg0: boolean): void;
        limitToType(arg0: $EntityType_<never>): void;
        setHasTeamEquals(arg0: boolean): void;
        setHasAdvancements(arg0: boolean): void;
        isTypeLimited(): boolean;
        isCurrentEntity(): boolean;
        hasTeamEquals(): boolean;
        addPredicate(arg0: $Predicate_<$Entity>): void;
        setMaxResults(arg0: number): void;
        hasGamemodeEquals(): boolean;
        parseNameOrUUID(): void;
        getCustomFlag(arg0: $ResourceLocation_): boolean;
        finalizePredicates(): void;
        fillSuggestions(arg0: $SuggestionsBuilder, arg1: $Consumer_<$SuggestionsBuilder>): $CompletableFuture<$Suggestions>;
        parseOptions(): void;
        setCustomFlag(arg0: $ResourceLocation_, arg1: boolean): void;
        hasTeamNotEquals(): boolean;
        setSorted(arg0: boolean): void;
        hasScores(): boolean;
        setRotX(arg0: $WrappedMinMaxBounds_): void;
        setDeltaY(arg0: number): void;
        getDeltaX(): number;
        setDeltaX(arg0: number): void;
        setRotY(arg0: $WrappedMinMaxBounds_): void;
        setDeltaZ(arg0: number): void;
        getRotY(): $WrappedMinMaxBounds;
        getRotX(): $WrappedMinMaxBounds;
        setLimited(arg0: boolean): void;
        getDeltaZ(): number;
        getDeltaY(): number;
        isTag(): boolean;
        static allowSelectors<S>(arg0: S): boolean;
        static ERROR_SELECTORS_NOT_ALLOWED: $SimpleCommandExceptionType;
        static SUGGEST_NOTHING: $BiFunction<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>;
        static SYNTAX_NOT: string;
        static ORDER_RANDOM: $BiConsumer<$Vec3, $List<$Entity>>;
        static ERROR_EXPECTED_END_OF_OPTIONS: $SimpleCommandExceptionType;
        static SYNTAX_TAG: string;
        static ERROR_EXPECTED_OPTION_VALUE: $DynamicCommandExceptionType;
        static ERROR_UNKNOWN_SELECTOR_TYPE: $DynamicCommandExceptionType;
        static SYNTAX_OPTIONS_KEY_VALUE_SEPARATOR: string;
        static SYNTAX_SELECTOR_START: string;
        static ERROR_MISSING_SELECTOR_TYPE: $SimpleCommandExceptionType;
        static ERROR_INVALID_NAME_OR_UUID: $SimpleCommandExceptionType;
        static ORDER_NEAREST: $BiConsumer<$Vec3, $List<$Entity>>;
        static ORDER_FURTHEST: $BiConsumer<$Vec3, $List<$Entity>>;
        constructor(arg0: $StringReader, arg1: boolean);
        get reader(): $StringReader;
        get selector(): $EntitySelector;
        set includesEntities(value: boolean);
        set suggestions(value: $BiFunction_<$SuggestionsBuilder, $Consumer<$SuggestionsBuilder>, $CompletableFuture<$Suggestions>>);
        get typeLimited(): boolean;
        get currentEntity(): boolean;
        set maxResults(value: number);
        get tag(): boolean;
    }
    export class $EntitySelector {
        includesEntities(): boolean;
        findSingleEntity(arg0: $CommandSourceStack): $Entity;
        getMaxResults(): number;
        findPlayers(arg0: $CommandSourceStack): $List<$ServerPlayer>;
        isSelfSelector(): boolean;
        findEntities(arg0: $CommandSourceStack): $List<$Entity>;
        findSinglePlayer(arg0: $CommandSourceStack): $ServerPlayer;
        isWorldLimited(): boolean;
        usesSelector(): boolean;
        static joinNames(arg0: $List_<$Entity>): $Component;
        static ORDER_ARBITRARY: $BiConsumer<$Vec3, $List<$Entity>>;
        contextFreePredicates: $List<$Predicate<$Entity>>;
        static INFINITE: number;
        constructor(arg0: number, arg1: boolean, arg2: boolean, arg3: $List_<$Predicate_<$Entity>>, arg4: $MinMaxBounds$Doubles_, arg5: $Function_<$Vec3, $Vec3>, arg6: $AABB_, arg7: $BiConsumer_<$Vec3, $List<$Entity>>, arg8: boolean, arg9: string, arg10: $UUID_, arg11: $EntityType_<never>, arg12: boolean);
        get maxResults(): number;
        get selfSelector(): boolean;
        get worldLimited(): boolean;
    }
}
