import { $PrintWriter } from "@package/java/io";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $DimensionSpecialEffects } from "@package/net/minecraft/client/renderer";
import { $RegionDetection } from "@package/xaero/map/file";
import { $LeveledRegion, $LayeredRegionManager } from "@package/xaero/map/region";
import { $DimensionHighlighterHandler, $HighlighterRegistry } from "@package/xaero/map/highlight";
import { $Minecraft } from "@package/net/minecraft/client";
import { $ArrayList, $List, $List_, $Hashtable } from "@package/java/util";
import { $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $Registry } from "@package/net/minecraft/core";
import { $Path } from "@package/java/nio/file";
import { $MapFullReloader, $MapProcessor } from "@package/xaero/map";
import { $ResourceKey_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Object, $Iterable } from "@package/java/lang";
import { $DimensionType, $DimensionType_ } from "@package/net/minecraft/world/level/dimension";

declare module "@package/xaero/map/world" {
    export class $MapConnectionManager {
        isConnected(arg0: $MapConnectionNode, arg1: $MapConnectionNode): boolean;
        isEmpty(): boolean;
        save(arg0: $PrintWriter): void;
        removeConnection(arg0: $MapConnectionNode, arg1: $MapConnectionNode): void;
        addConnection(arg0: $MapConnectionNode, arg1: $MapConnectionNode): void;
        renameDimension(arg0: string, arg1: string): void;
        constructor();
        get empty(): boolean;
    }
    export class $MapWorld {
        getDimensionTeleportCommandFormat(): string;
        unconfirmMultiworldTypeUnsynced(): void;
        isUsingDefaultPlayerTeleport(): boolean;
        isFutureMultiworldTypeConfirmed(arg0: $MapDimension): boolean;
        setUseDefaultPlayerTeleport(arg0: boolean): void;
        getEffectiveTeleportCommandFormat(): string;
        isCurrentMultiworldTypeConfirmed(): boolean;
        setDimensionTeleportCommandFormat(arg0: string): void;
        setPlayerTeleportCommandFormat(arg0: string): void;
        getPlayerTeleportCommandFormat(): string;
        load(): void;
        getDimensions(arg0: $List_<$MapDimension>): void;
        saveConfig(): void;
        switchToFutureMultiworldTypeUnsynced(): void;
        getEffectivePlayerTeleportCommandFormat(): string;
        getEffectiveDimensionTeleportCommandFormat(): string;
        getDimension(arg0: $ResourceKey_<$Level>): $MapDimension;
        createDimensionUnsynced(arg0: $ResourceKey_<$Level>): $MapDimension;
        isIgnoreHeightmaps(): boolean;
        getFutureDimension(): $MapDimension;
        getCurrentDimension(): $MapDimension;
        getCurrentDimensionId(): $ResourceKey<$Level>;
        clearAllCachedHighlightHashes(): void;
        isMultiplayer(): boolean;
        isUsingUnknownDimensionType(): boolean;
        isIgnoreServerLevelId(): boolean;
        static convertWorldFolderToRootId(arg0: number, arg1: string): string;
        getCustomDimensionId(): $ResourceKey<$Level>;
        getCurrentMultiworld(): string;
        getFutureDimensionId(): $ResourceKey<$Level>;
        isUsingCustomDimension(): boolean;
        setIgnoreHeightmaps(arg0: boolean): void;
        isCacheOnlyMode(): boolean;
        getMapProcessor(): $MapProcessor;
        confirmMultiworldTypeUnsynced(): void;
        toggleMultiworldTypeUnsynced(): void;
        getFutureMultiworldUnsynced(): string;
        getMainId(): string;
        getPotentialDimId(): $ResourceKey<$Level>;
        getDimensionsList(): $List<$MapDimension>;
        getMapConnections(): $MapConnectionManager;
        getPlayerMapKey(): $MapConnectionNode;
        setFutureDimensionId(arg0: $ResourceKey_<$Level>): void;
        switchToFutureUnsynced(): void;
        onWorldChangeUnsynced(arg0: $ClientLevel): void;
        setUseDefaultMapTeleport(arg0: boolean): void;
        setCustomDimensionId(arg0: $ResourceKey_<$Level>): void;
        getCurrentMultiworldType(): number;
        setTeleportCommandFormat(arg0: string): void;
        getTeleportCommandFormat(): string;
        getFutureMultiworldType(arg0: $MapDimension): number;
        isUsingDefaultMapTeleport(): boolean;
        getOldUnfixedMainId(): string;
        toggleDimension(arg0: boolean): void;
        constructor(arg0: string, arg1: string, arg2: $MapProcessor);
        get usingDefaultPlayerTeleport(): boolean;
        set useDefaultPlayerTeleport(value: boolean);
        get effectiveTeleportCommandFormat(): string;
        get currentMultiworldTypeConfirmed(): boolean;
        get effectivePlayerTeleportCommandFormat(): string;
        get effectiveDimensionTeleportCommandFormat(): string;
        get futureDimension(): $MapDimension;
        get currentDimension(): $MapDimension;
        get currentDimensionId(): $ResourceKey<$Level>;
        get multiplayer(): boolean;
        get usingUnknownDimensionType(): boolean;
        get ignoreServerLevelId(): boolean;
        get currentMultiworld(): string;
        get usingCustomDimension(): boolean;
        get cacheOnlyMode(): boolean;
        get mapProcessor(): $MapProcessor;
        get futureMultiworldUnsynced(): string;
        get mainId(): string;
        get potentialDimId(): $ResourceKey<$Level>;
        get dimensionsList(): $List<$MapDimension>;
        get mapConnections(): $MapConnectionManager;
        get playerMapKey(): $MapConnectionNode;
        set useDefaultMapTeleport(value: boolean);
        get currentMultiworldType(): number;
        get usingDefaultMapTeleport(): boolean;
        get oldUnfixedMainId(): string;
    }
    export class $MapConnectionNode {
        static fromString(arg0: string): $MapConnectionNode;
        getNamedString(arg0: $MapWorld): string;
        getMw(): string;
        getDimId(): $ResourceKey<$Level>;
        constructor(arg0: $ResourceKey_<$Level>, arg1: string);
        get mw(): string;
        get dimId(): $ResourceKey<$Level>;
    }
    export class $MapDimension {
        getFutureCustomSelectedMultiworld(): string;
        getWorldSaveRegionDetection(arg0: number, arg1: number): $RegionDetection;
        isFutureUsingWorldSaveUnsynced(): boolean;
        getLinkedWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        onClearCachedHighlightHashes(): void;
        clear(): void;
        pickDefaultCustomMultiworldUnsynced(): void;
        getSkyDarken(arg0: number, arg1: $ClientLevel, arg2: $Registry<$DimensionType_>): number;
        getMultiworldIdsCopy(): $List<string>;
        getLayeredMapRegions(): $LayeredRegionManager;
        getMultiworldName(arg0: string): string;
        getCaveModeType(): number;
        switchToFutureMultiworldWritableValueUnsynced(): void;
        preDetection(): void;
        getWorldSaveDetectedRegions(): $Iterable<$Hashtable<number, $RegionDetection>>;
        isUsingUnknownDimensionType(arg0: $Registry<$DimensionType_>): boolean;
        startFullMapReload(arg0: number, arg1: boolean, arg2: $MapProcessor): void;
        clearFullMapReload(): void;
        static getDimensionType(arg0: $MapDimension, arg1: $ResourceKey_<$Level>, arg2: $Registry<$DimensionType_>): $DimensionType;
        getDimensionType(arg0: $Registry<$DimensionType_>): $DimensionType;
        addWorldSaveRegionDetection(arg0: $RegionDetection): void;
        getCurrentMultiworld(): string;
        getHighlightHandler(): $DimensionHighlighterHandler;
        isUsingWorldSave(): boolean;
        getMapWorld(): $MapWorld;
        isCacheOnlyMode(arg0: $Registry<$DimensionType_>): boolean;
        calculateDimDiv(arg0: $Registry<$DimensionType_>, arg1: $DimensionType_): number;
        updateFutureAutomaticUnsynced(arg0: $Minecraft, arg1: $Object): void;
        resetCustomMultiworldUnsynced(): void;
        isFutureMultiworldServerBased(): boolean;
        deleteMultiworldMapDataUnsynced(arg0: string): void;
        getFutureMultiworldUnsynced(): string;
        getShadowG(): number;
        getShadowB(): number;
        getShadowR(): number;
        onCreationUnsynced(): void;
        getMainFolderPath(): $Path;
        setMultiworldName(arg0: string, arg1: string): void;
        saveConfigUnsynced(): void;
        getOldFolderPath(): $Path;
        deleteMultiworldId(arg0: string): void;
        toggleCaveModeType(arg0: boolean): void;
        isAutoSelected(): boolean;
        getPlayerMapKey(): $MapConnectionNode;
        switchToFutureUnsynced(): void;
        setMultiworldUnsynced(arg0: string): void;
        getDimensionEffects(arg0: $Registry<$DimensionType_>): $DimensionSpecialEffects;
        confirmMultiworldUnsynced(): void;
        onWorldChangeUnsynced(arg0: $Level_): void;
        hasDoneRegionDetection(): boolean;
        hasConfirmedMultiworld(): boolean;
        addMultiworldChecked(arg0: string): boolean;
        getSelectedMapKeyUnsynced(): $MapConnectionNode;
        onClearCachedHighlightHash(arg0: number, arg1: number): void;
        getDimId(): $ResourceKey<$Level>;
        getDimensionTypeId(): $ResourceLocation;
        getFullReloader(): $MapFullReloader;
        calculateDimScale(arg0: $Registry<$DimensionType_>): number;
        futureMultiworldWritable: boolean;
        futureMultiworldServerBased: boolean;
        currentMultiworldWritable: boolean;
        regionsToCache: $ArrayList<$LeveledRegion<never>>;
        constructor(arg0: $MapWorld, arg1: $ResourceKey_<$Level>, arg2: $HighlighterRegistry);
        get futureCustomSelectedMultiworld(): string;
        get futureUsingWorldSaveUnsynced(): boolean;
        get linkedWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        get multiworldIdsCopy(): $List<string>;
        get layeredMapRegions(): $LayeredRegionManager;
        get caveModeType(): number;
        get worldSaveDetectedRegions(): $Iterable<$Hashtable<number, $RegionDetection>>;
        get currentMultiworld(): string;
        get highlightHandler(): $DimensionHighlighterHandler;
        get usingWorldSave(): boolean;
        get mapWorld(): $MapWorld;
        get futureMultiworldUnsynced(): string;
        get shadowG(): number;
        get shadowB(): number;
        get shadowR(): number;
        get mainFolderPath(): $Path;
        get oldFolderPath(): $Path;
        get autoSelected(): boolean;
        get playerMapKey(): $MapConnectionNode;
        set multiworldUnsynced(value: string);
        get selectedMapKeyUnsynced(): $MapConnectionNode;
        get dimId(): $ResourceKey<$Level>;
        get dimensionTypeId(): $ResourceLocation;
        get fullReloader(): $MapFullReloader;
    }
}
