import { $NetInput, $NetOutput } from "@package/com/github/steveice10/packetlib/io";
import { $IGlobalPosition, $IOSupplier_, $IPosition, $IOConsumer_ } from "@package/com/replaymod/replaystudio/util";
import { $StringOrNbtText } from "@package/com/replaymod/replaystudio/protocol/data";
import { $ByteBuf } from "@package/com/github/steveice10/netty/buffer";
import { $Tag, $CompoundTag } from "@package/com/github/steveice10/opennbt/tag/builtin";
import { $ByteBufNetInput, $ByteBufNetOutput } from "@package/com/github/steveice10/packetlib/tcp/io";
import { $Enum, $AutoCloseable } from "@package/java/lang";
import { $List, $BitSet, $List_ } from "@package/java/util";
import { $State_, $State } from "@package/com/replaymod/replaystudio/lib/viaversion/api/protocol/packet";
import { $ProtocolVersion } from "@package/com/replaymod/replaystudio/lib/viaversion/api/protocol/version";
export * as data from "@package/com/replaymod/replaystudio/protocol/data";

declare module "@package/com/replaymod/replaystudio/protocol" {
    export class $Packet {
        getId(): number;
        reader(): $Packet$Reader;
        getType(): $PacketType;
        copy(): $Packet;
        release(): boolean;
        atLeast(protocolVersion: $ProtocolVersion): boolean;
        overwrite(): $Packet$Writer;
        atMost(protocolVersion: $ProtocolVersion): boolean;
        getProtocolVersion(): $ProtocolVersion;
        getRegistry(): $PacketTypeRegistry;
        olderThan(protocolVersion: $ProtocolVersion): boolean;
        retain(): $Packet;
        getBuf(): $ByteBuf;
        constructor(registry: $PacketTypeRegistry, id: number, type: $PacketType_, buf: $ByteBuf);
        constructor(registry: $PacketTypeRegistry, packetId: number, buf: $ByteBuf);
        constructor(registry: $PacketTypeRegistry, type: $PacketType_, buf: $ByteBuf);
        constructor(registry: $PacketTypeRegistry, type: $PacketType_);
        get id(): number;
        get type(): $PacketType;
        get protocolVersion(): $ProtocolVersion;
        get registry(): $PacketTypeRegistry;
        get buf(): $ByteBuf;
    }
    export class $Packet$Writer extends $ByteBufNetOutput implements $AutoCloseable {
        close(): void;
        writeText(value: $StringOrNbtText): void;
        writeList<T>(list: $List_<T>, entryWriter: $IOConsumer_<T>): void;
        static writeList<T>(registry: $PacketTypeRegistry, out: $NetOutput, list: $List_<T>, entryWriter: $IOConsumer_<T>): void;
        static writeNBT(registry: $PacketTypeRegistry, out: $NetOutput, tag: $Tag): void;
        writeNBT(tag: $Tag): void;
        static writeBitSet(registry: $PacketTypeRegistry, out: $NetOutput, bitSet: $BitSet): void;
        writeBitSet(bitSet: $BitSet): void;
        writeGlobalPosition(pos: $IGlobalPosition): void;
        static writeGlobalPosition(registry: $PacketTypeRegistry, out: $NetOutput, pos: $IGlobalPosition): void;
        static writePosition(registry: $PacketTypeRegistry, out: $NetOutput, pos: $IPosition): void;
        writePosition(pos: $IPosition): void;
    }
    export class $PacketTypeRegistry {
        static get(version: $ProtocolVersion, state: $State_): $PacketTypeRegistry;
        getId(type: $PacketType_): number;
        getState(): $State;
        getType(id: number): $PacketType;
        getVersion(): $ProtocolVersion;
        atLeast(protocolVersion: $ProtocolVersion): boolean;
        atMost(protocolVersion: $ProtocolVersion): boolean;
        withState(state: $State_): $PacketTypeRegistry;
        olderThan(protocolVersion: $ProtocolVersion): boolean;
        withLoginSuccess(): $PacketTypeRegistry;
        get state(): $State;
        get version(): $ProtocolVersion;
    }
    export class $PacketType extends $Enum<$PacketType> {
        static values(): $PacketType[];
        static valueOf(name: string): $PacketType;
        getState(): $State;
        isUnknown(): boolean;
        getInitialVersion(): $ProtocolVersion;
        getRemovedVersion(): $ProtocolVersion;
        getInitialId(): number;
        static DestroyEntities: $PacketType;
        static Difficulty: $PacketType;
        static CloseWindow: $PacketType;
        static EntityVelocity: $PacketType;
        static WindowProperty: $PacketType;
        static CombatEnter: $PacketType;
        static ConfigCustomPayload: $PacketType;
        static MapData: $PacketType;
        static JoinGame: $PacketType;
        static SpawnParticle: $PacketType;
        static SwitchCamera: $PacketType;
        static Tags: $PacketType;
        static EntityPosition: $PacketType;
        static UpdateViewDistance: $PacketType;
        static BlockBreakAnim: $PacketType;
        static CombatEntityDead: $PacketType;
        static NotifyClient: $PacketType;
        static OpenWindow: $PacketType;
        static UnknownLogin: $PacketType;
        static LoginSuccess: $PacketType;
        static DisplayScoreboard: $PacketType;
        static TradeList: $PacketType;
        static SpawnPainting: $PacketType;
        static SpawnObject: $PacketType;
        static UnloadChunk: $PacketType;
        static EntityCollectItem: $PacketType;
        static BlockChange: $PacketType;
        static EntityMetadata: $PacketType;
        static EntityEquipment: $PacketType;
        static Chat: $PacketType;
        static ChangeHeldItem: $PacketType;
        static EntityStatus: $PacketType;
        static Team: $PacketType;
        static UpdateSign: $PacketType;
        static Statistics: $PacketType;
        static SpawnPlayer: $PacketType;
        static ConfigFinish: $PacketType;
        static SpawnPosition: $PacketType;
        static UpdateTime: $PacketType;
        static OpenTileEntityEditor: $PacketType;
        static CombatEnd: $PacketType;
        static EntityMovement: $PacketType;
        static PlayerActionAck: $PacketType;
        static PlayEffect: $PacketType;
        static UpdateHealth: $PacketType;
        static DestroyEntity: $PacketType;
        static UpdateLight: $PacketType;
        static ConfigRegistries: $PacketType;
        static EntityTeleport: $PacketType;
        static UpdateTileEntity: $PacketType;
        static UnknownPlay: $PacketType;
        static EntityEffect: $PacketType;
        static EntityHeadLook: $PacketType;
        static EntityProperties: $PacketType;
        static EntityPositionRotation: $PacketType;
        static PlayerPositionRotation: $PacketType;
        static Explosion: $PacketType;
        static UpdateScore: $PacketType;
        static SpawnMob: $PacketType;
        static ConfigKeepAlive: $PacketType;
        static SetExperience: $PacketType;
        static ConfigSelectKnownPacks: $PacketType;
        static UnknownConfiguration: $PacketType;
        static Respawn: $PacketType;
        static ConfigPing: $PacketType;
        static KeepAlive: $PacketType;
        static OpenHorseWindow: $PacketType;
        static UpdateViewPosition: $PacketType;
        static Combat: $PacketType;
        static Reconfigure: $PacketType;
        static EntityNBTUpdate: $PacketType;
        static ConfigDisconnect: $PacketType;
        static PlayerAbilities: $PacketType;
        static ConfigFeatures: $PacketType;
        static ChunkData: $PacketType;
        static WindowItems: $PacketType;
        static SetPassengers: $PacketType;
        static PlaySound: $PacketType;
        static UpdateSimulationDistance: $PacketType;
        static EntityRemoveEffect: $PacketType;
        static PlayerListEntry: $PacketType;
        static PlayerUseBed: $PacketType;
        static SpawnGlobalEntity: $PacketType;
        static EntitySoundEffect: $PacketType;
        static EntityRotation: $PacketType;
        static Disconnect: $PacketType;
        static PlayerListEntryRemove: $PacketType;
        static WorldBorder: $PacketType;
        static PluginMessage: $PacketType;
        static MultiBlockChange: $PacketType;
        static Features: $PacketType;
        static BulkChunkData: $PacketType;
        static EntityAnimation: $PacketType;
        static SpawnExpOrb: $PacketType;
        static Bundle: $PacketType;
        static SetSlot: $PacketType;
        static ScoreboardObjective: $PacketType;
        static ConfirmTransaction: $PacketType;
        static EntityAttach: $PacketType;
        static ConfigTags: $PacketType;
        static BlockValue: $PacketType;
        static TabComplete: $PacketType;
        get state(): $State;
        get unknown(): boolean;
        get initialVersion(): $ProtocolVersion;
        get removedVersion(): $ProtocolVersion;
        get initialId(): number;
    }
    /**
     * Values that may be interpreted as {@link $PacketType}.
     */
    export type $PacketType_ = "unknownlogin" | "unknownconfiguration" | "unknownplay" | "loginsuccess" | "configcustompayload" | "configdisconnect" | "configfinish" | "configkeepalive" | "configping" | "configregistries" | "configfeatures" | "configtags" | "configselectknownpacks" | "keepalive" | "joingame" | "chat" | "updatetime" | "entityequipment" | "spawnposition" | "updatehealth" | "respawn" | "playerpositionrotation" | "changehelditem" | "playerusebed" | "entityanimation" | "spawnplayer" | "entitycollectitem" | "spawnobject" | "spawnmob" | "spawnpainting" | "spawnexporb" | "entityvelocity" | "destroyentities" | "entitymovement" | "entityposition" | "entityrotation" | "entitypositionrotation" | "entityteleport" | "entityheadlook" | "entitystatus" | "entityattach" | "entitymetadata" | "entityeffect" | "entityremoveeffect" | "setexperience" | "entityproperties" | "chunkdata" | "multiblockchange" | "blockchange" | "blockvalue" | "blockbreakanim" | "bulkchunkdata" | "explosion" | "playeffect" | "playsound" | "spawnparticle" | "notifyclient" | "spawnglobalentity" | "openwindow" | "closewindow" | "setslot" | "windowitems" | "windowproperty" | "confirmtransaction" | "updatesign" | "mapdata" | "updatetileentity" | "opentileentityeditor" | "statistics" | "playerlistentry" | "playerabilities" | "tabcomplete" | "scoreboardobjective" | "updatescore" | "displayscoreboard" | "team" | "pluginmessage" | "disconnect" | "difficulty" | "combat" | "switchcamera" | "worldborder" | "entitynbtupdate" | "unloadchunk" | "setpassengers" | "openhorsewindow" | "updatelight" | "tradelist" | "updateviewposition" | "updateviewdistance" | "entitysoundeffect" | "tags" | "playeractionack" | "combatend" | "combatenter" | "combatentitydead" | "destroyentity" | "updatesimulationdistance" | "features" | "playerlistentryremove" | "bundle" | "reconfigure";
    export class $Packet$Reader extends $ByteBufNetInput implements $AutoCloseable {
        close(): void;
        readList<T>(entryReader: $IOSupplier_<T>): $List<T>;
        static readList<T>(registry: $PacketTypeRegistry, arg1: $NetInput, entryReader: $IOSupplier_<T>): $List<T>;
        static readNBT(registry: $PacketTypeRegistry, arg1: $NetInput): $CompoundTag;
        readNBT(): $CompoundTag;
        readBitSet(): $BitSet;
        static readBitSet(registry: $PacketTypeRegistry, arg1: $NetInput): $BitSet;
        readPosition(): $IPosition;
        static readPosition(registry: $PacketTypeRegistry, arg1: $NetInput): $IPosition;
        static readGlobalPosition(registry: $PacketTypeRegistry, arg1: $NetInput): $IGlobalPosition;
        readGlobalPosition(): $IGlobalPosition;
        readText(): $StringOrNbtText;
    }
}
