import { $EntityDynamicLightSource } from "@package/dev/lambdaurora/lambdynlights/engine/source";
import { $Codec } from "@package/com/mojang/serialization";
import { $Recipe, $RecipeHolder_ } from "@package/net/minecraft/world/item/crafting";
import { $Either } from "@package/com/mojang/datafixers/util";
import { $ListTag_, $ListTag, $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $HumanoidArm, $Pose_, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState, $HumanoidArm_, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $LevelBlock } from "@package/dev/latvian/mods/kubejs/level";
import { $ItemPredicate_ } from "@package/dev/latvian/mods/kubejs/item";
import { $WeakReference } from "@package/java/lang/ref";
import { $RandomSource, $SignatureValidator_, $Unit, $SignatureValidator, $OptionEnum } from "@package/net/minecraft/util";
import { $InteractionResult, $MenuProvider, $InteractionHand, $InteractionHand_, $Nameable, $Container } from "@package/net/minecraft/world";
import { $FakePlayer } from "@package/net/neoforged/neoforge/common/util";
import { $PlayerFreezeExtension } from "@package/dev/ryanhcode/sable/mixinterface/player_freezing";
import { $EntityLivingBaseAccessor, $EntityPlayerAccessor } from "@package/com/replaymod/replay/mixin";
import { $SoundEvent_, $SoundSource_ } from "@package/net/minecraft/sounds";
import { $IPlayerExtension } from "@package/net/neoforged/neoforge/common/extensions";
import { $Operation_ } from "@package/com/llamalad7/mixinextras/injector/wrapoperation";
import { $NotificationToastData_, $AttachedData } from "@package/dev/latvian/mods/kubejs/util";
import { $Brain } from "@package/net/minecraft/world/entity/ai";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $PlayerEnderChestContainer, $AbstractContainerMenu, $ClickAction_, $InventoryMenu } from "@package/net/minecraft/world/inventory";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";
import { $MerchantOffers } from "@package/net/minecraft/world/item/trading";
import { $Item_, $Item, $ItemCooldowns, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $MutableComponent, $Component_, $ThrowingComponent, $Component } from "@package/net/minecraft/network/chat";
import { $FishingHook } from "@package/net/minecraft/world/entity/projectile";
import { $Instant, $Duration_, $Duration } from "@package/java/time";
import { $DamageContainer } from "@package/net/neoforged/neoforge/common/damagesource";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $PlayerTypewriterExtension, $PlayerLaunchedPlungerExtension } from "@package/dev/simulated_team/simulated/mixin_interface";
import { $InventoryKJS, $PlayerKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $AABB_, $Vec3, $AABB, $Vec3_ } from "@package/net/minecraft/world/phys";
import { $Stat_ } from "@package/net/minecraft/stats";
import { $Vector3dc } from "@package/org/joml";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $UUID_, $Set_, $Stack, $Map, $OptionalInt, $UUID, $List, $Map_, $Collection_, $List_, $Collection } from "@package/java/util";
import { $PlayerStatsJS, $KubeJSInventoryListener } from "@package/dev/latvian/mods/kubejs/player";
import { $WardenSpawnTracker } from "@package/net/minecraft/world/entity/monster/warden";
import { $AbstractHorse } from "@package/net/minecraft/world/entity/animal/horse";
import { $Consumer_, $Predicate_ } from "@package/java/util/function";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $BlockPos, $GlobalPos, $BlockPos_, $GlobalPos_, $Direction_, $NonNullList } from "@package/net/minecraft/core";
import { $OBB$Part } from "@package/com/atsuishio/superbwarfare/tools";
import { $Enum, $Record, $Class } from "@package/java/lang";
import { $IntList, $Int2IntMap } from "@package/it/unimi/dsi/fastutil/ints";
import { $GameType_, $BaseCommandBlock, $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey, $TagKey_ } from "@package/net/minecraft/tags";
import { $LaunchedPlungerEntity } from "@package/dev/simulated_team/simulated/content/entities/launched_plunger";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $PrivateKey, $PublicKey } from "@package/java/security";
import { $ImmutableList } from "@package/com/google/common/collect";
import { $ItemEntity } from "@package/net/minecraft/world/entity/item";
import { $Trackable } from "@package/dev/uncandango/alltheleaks/mixin";
import { $EntityDataAccessor, $SynchedEntityData } from "@package/net/minecraft/network/syncher";
import { $Stages } from "@package/dev/latvian/mods/kubejs/stages";
import { $ISettingsStorage } from "@package/com/possible_triangle/flightlib/logic";
import { $FoodData } from "@package/net/minecraft/world/food";
import { $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $Scoreboard } from "@package/net/minecraft/world/scores";
import { $SignBlockEntity, $StructureBlockEntity, $JigsawBlockEntity, $CommandBlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $DamageSource, $DamageSource_ } from "@package/net/minecraft/world/damagesource";

declare module "@package/net/minecraft/world/entity/player" {
    export class $ProfileKeyPair extends $Record {
        publicKey(): $ProfilePublicKey;
        privateKey(): $PrivateKey;
        dueRefresh(): boolean;
        refreshedAfter(): $Instant;
        static CODEC: $Codec<$ProfileKeyPair>;
        constructor(arg0: $PrivateKey, arg1: $ProfilePublicKey_, arg2: $Instant);
    }
    export class $ProfilePublicKey$Data extends $Record {
        write(arg0: $FriendlyByteBuf): void;
        key(): $PublicKey;
        hasExpired(): boolean;
        hasExpired(arg0: $Duration_): boolean;
        expiresAt(): $Instant;
        keySignature(): number[];
        validateSignature(arg0: $SignatureValidator_, arg1: $UUID_): boolean;
        static CODEC: $Codec<$ProfilePublicKey$Data>;
        constructor(arg0: $FriendlyByteBuf);
        constructor(arg0: $Instant, arg1: $PublicKey, arg2: number[]);
    }
    export class $Abilities {
        getWalkingSpeed(): number;
        addSaveData(arg0: $CompoundTag_): void;
        loadSaveData(arg0: $CompoundTag_): void;
        setWalkingSpeed(arg0: number): void;
        getFlyingSpeed(): number;
        setFlyingSpeed(arg0: number): void;
        invulnerable: boolean;
        /**
         * @deprecated
         */
        mayfly: boolean;
        instabuild: boolean;
        mayBuild: boolean;
        flying: boolean;
        constructor();
    }
    export class $Inventory implements $Container, $Nameable {
        getName(): $Component;
        load(arg0: $ListTag_): void;
        isEmpty(): boolean;
        add(arg0: number, arg1: $ItemStack_): boolean;
        add(arg0: $ItemStack_): boolean;
        contains(arg0: $Predicate_<$ItemStack>): boolean;
        contains(arg0: $TagKey_<$Item>): boolean;
        contains(arg0: $ItemStack_): boolean;
        save(arg0: $ListTag_): $ListTag;
        replaceWith(arg0: $Inventory): void;
        tick(): void;
        getItem(arg0: number): $ItemStack;
        getSelected(): $ItemStack;
        addResource(arg0: number, arg1: $ItemStack_): number;
        removeItem(arg0: number, arg1: number): $ItemStack;
        removeItem(arg0: $ItemStack_): void;
        getDestroySpeed(arg0: $BlockState_): number;
        clearContent(): void;
        handler$fhf000$inventoryprofilesnext$addStackPre(arg0: $ItemStack_, arg1: $CallbackInfoReturnable<any>): void;
        handler$gmj000$moonlight$ml$restoreNotDropped(arg0: $CallbackInfo, arg1: $List_<any>, arg2: number): void;
        handler$fhf000$inventoryprofilesnext$addStackPost(arg0: $ItemStack_, arg1: $CallbackInfoReturnable<any>): void;
        handler$fhf000$inventoryprofilesnext$getEmptySlot(arg0: $CallbackInfoReturnable<any>): void;
        setItem(arg0: number, arg1: $ItemStack_): void;
        static isHotbarSlot(arg0: number): boolean;
        setPickedItem(arg0: $ItemStack_): void;
        findSlotMatchingItem(arg0: $ItemStack_): number;
        hasAnyMatching(arg0: $Predicate_<any>): boolean;
        getContainerSize(): number;
        removeItemNoUpdate(arg0: number): $ItemStack;
        stillValid(arg0: $Player): boolean;
        dropAll(): void;
        setChanged(): void;
        removeFromSelected(arg0: boolean): $ItemStack;
        handler$ioh000$axiom$swapPaintHead(d: number, ci: $CallbackInfo): void;
        placeItemBackInInventory(arg0: $ItemStack_): void;
        placeItemBackInInventory(arg0: $ItemStack_, arg1: boolean): void;
        fillStackedContents(arg0: $StackedContents): void;
        handler$fhf000$inventoryprofilesnext$setPickedItemPost(arg0: $ItemStack_, arg1: $CallbackInfo): void;
        handler$fhf000$inventoryprofilesnext$setPickedItemPre(arg0: $ItemStack_, arg1: $CallbackInfo): void;
        wrapOperation$ioh000$axiom$setPickedItem(instance: $Inventory, itemStack: $ItemStack_, original: $Operation_<any>): number;
        handler$gmj000$moonlight$ml$fireDropEvent(arg0: $CallbackInfo, arg1: $List_<any>, arg2: number): void;
        pickSlot(arg0: number): void;
        getArmor(arg0: number): $ItemStack;
        swapPaint(arg0: number): void;
        hasRemainingSpaceForItem(arg0: $ItemStack_, arg1: $ItemStack_): boolean;
        findSlotMatchingUnusedItem(arg0: $ItemStack_): number;
        getSlotWithRemainingSpace(arg0: $ItemStack_): number;
        clearOrCountMatchingItems(arg0: $Predicate_<$ItemStack>, arg1: number, arg2: $Container): number;
        getSuitableHotbarSlot(): number;
        getTimesChanged(): number;
        getFreeSlot(): number;
        static getSelectionSize(): number;
        getMaxStackSize(arg0: $ItemStack_): number;
        getMaxStackSize(): number;
        canPlaceItem(arg0: number, arg1: $ItemStack_): boolean;
        canTakeItem(arg0: $Container, arg1: number, arg2: $ItemStack_): boolean;
        startOpen(arg0: $Player): void;
        stopOpen(arg0: $Player): void;
        hasAnyOf(arg0: $Set_<$Item_>): boolean;
        countItem(arg0: $Item_): number;
        getDisplayName(): $Component;
        hasCustomName(): boolean;
        getCustomName(): $Component;
        setStackInSlot(slot: number, stack: $ItemStack_): void;
        isMutable(): boolean;
        getStackInSlot(slot: number): $ItemStack;
        getWidth(): number;
        getSlotLimit(slot: number): number;
        getSlots(): number;
        setChanged(): void;
        extractItem(slot: number, amount: number, simulate: boolean): $ItemStack;
        isItemValid(slot: number, stack: $ItemStack_): boolean;
        insertItem(slot: number, stack: $ItemStack_, simulate: boolean): $ItemStack;
        getHeight(): number;
        asContainer(): $Container;
        self(): $Container;
        getBlock(level: $Level_): $LevelBlock;
        clear(): void;
        countNonEmpty(): number;
        countNonEmpty(match: $ItemPredicate_): number;
        getAllItems(): $List<$ItemStack>;
        insertItem(stack: $ItemStack_, simulate: boolean): $ItemStack;
        isEmpty(): boolean;
        clear(match: $ItemPredicate_): void;
        find(): number;
        find(match: $ItemPredicate_): number;
        count(): number;
        count(match: $ItemPredicate_): number;
        static NOT_FOUND_INDEX: number;
        armor: $NonNullList<$ItemStack>;
        static INVENTORY_SIZE: number;
        static POP_TIME_DURATION: number;
        static SLOT_OFFHAND: number;
        static ALL_ARMOR_SLOTS: number[];
        items: $NonNullList<$ItemStack>;
        offhand: $NonNullList<$ItemStack>;
        selected: number;
        static HELMET_SLOT_ONLY: number[];
        player: $Player;
        constructor(arg0: $Player);
        get name(): $Component;
        set pickedItem(value: $ItemStack_);
        get containerSize(): number;
        get suitableHotbarSlot(): number;
        get timesChanged(): number;
        get freeSlot(): number;
        static get selectionSize(): number;
        get displayName(): $Component;
        get customName(): $Component;
        get mutable(): boolean;
        get width(): number;
        get slots(): number;
        get height(): number;
        get allItems(): $List<$ItemStack>;
    }
    export class $PlayerModelPart extends $Enum<$PlayerModelPart> {
        getName(): $Component;
        static values(): $PlayerModelPart[];
        static valueOf(arg0: string): $PlayerModelPart;
        getId(): string;
        getMask(): number;
        getBit(): number;
        static RIGHT_PANTS_LEG: $PlayerModelPart;
        static LEFT_PANTS_LEG: $PlayerModelPart;
        static JACKET: $PlayerModelPart;
        static RIGHT_SLEEVE: $PlayerModelPart;
        static HAT: $PlayerModelPart;
        static LEFT_SLEEVE: $PlayerModelPart;
        static CAPE: $PlayerModelPart;
        get id(): string;
        get mask(): number;
        get bit(): number;
    }
    /**
     * Values that may be interpreted as {@link $PlayerModelPart}.
     */
    export type $PlayerModelPart_ = "cape" | "jacket" | "left_sleeve" | "right_sleeve" | "left_pants_leg" | "right_pants_leg" | "hat";
    export class $StackedContents$RecipePicker {
    }
    export class $ProfilePublicKey extends $Record {
        data(): $ProfilePublicKey$Data;
        static createValidated(arg0: $SignatureValidator_, arg1: $UUID_, arg2: $ProfilePublicKey$Data_): $ProfilePublicKey;
        createSignatureValidator(): $SignatureValidator;
        static EXPIRED_PROFILE_PUBLIC_KEY: $Component;
        static EXPIRY_GRACE_PERIOD: $Duration;
        static TRUSTED_CODEC: $Codec<$ProfilePublicKey>;
        constructor(arg0: $ProfilePublicKey$Data_);
    }
    export class $Player$BedSleepingProblem extends $Enum<$Player$BedSleepingProblem> {
        static values(): $Player$BedSleepingProblem[];
        static valueOf(arg0: string): $Player$BedSleepingProblem;
        getMessage(): $Component;
        static OBSTRUCTED: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_HERE: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_NOW: $Player$BedSleepingProblem;
        static NOT_SAFE: $Player$BedSleepingProblem;
        static OTHER_PROBLEM: $Player$BedSleepingProblem;
        static TOO_FAR_AWAY: $Player$BedSleepingProblem;
        get message(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $Player$BedSleepingProblem}.
     */
    export type $Player$BedSleepingProblem_ = "not_possible_here" | "not_possible_now" | "too_far_away" | "obstructed" | "other_problem" | "not_safe";
    export class $ChatVisiblity extends $Enum<$ChatVisiblity> implements $OptionEnum {
        static values(): $ChatVisiblity[];
        static valueOf(arg0: string): $ChatVisiblity;
        getKey(): string;
        getId(): number;
        static byId(arg0: number): $ChatVisiblity;
        getCaption(): $Component;
        static SYSTEM: $ChatVisiblity;
        static HIDDEN: $ChatVisiblity;
        static FULL: $ChatVisiblity;
        get key(): string;
        get id(): number;
        get caption(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $ChatVisiblity}.
     */
    export type $ChatVisiblity_ = "full" | "system" | "hidden";
    export class $StackedContents {
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: $IntList): number;
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: number, arg2: $IntList): number;
        put(arg0: number, arg1: number): void;
        clear(): void;
        take(arg0: number, arg1: number): number;
        has(arg0: number): boolean;
        accountStack(arg0: $ItemStack_): void;
        accountStack(arg0: $ItemStack_, arg1: number): void;
        accountSimpleStack(arg0: $ItemStack_): void;
        static getStackingIndex(arg0: $ItemStack_): number;
        canCraft(arg0: $Recipe<never>, arg1: $IntList, arg2: number): boolean;
        canCraft(arg0: $Recipe<never>, arg1: $IntList): boolean;
        static fromStackingIndex(arg0: number): $ItemStack;
        contents: $Int2IntMap;
        constructor();
    }
    export class $ProfilePublicKey$ValidationException extends $ThrowingComponent {
        constructor(arg0: $Component_);
    }
    export class $Player extends $LivingEntity implements $IPlayerExtension, $EntityLivingBaseAccessor, $EntityPlayerAccessor, $ISettingsStorage, $Trackable, $PlayerTypewriterExtension, $PlayerLaunchedPlungerExtension, $EntityDynamicLightSource, $PlayerFreezeExtension, $PlayerKJS {
        drop(arg0: $ItemStack_, arg1: boolean): $ItemEntity;
        drop(arg0: $ItemStack_, arg1: boolean, arg2: boolean): $ItemEntity;
        addItem(arg0: $ItemStack_): boolean;
        getPrefixes(): $Collection<$MutableComponent>;
        createItemCooldowns(): $ItemCooldowns;
        blockActionRestricted(arg0: $Level_, arg1: $BlockPos_, arg2: $GameType_): boolean;
        isSecondaryUseActive(): boolean;
        isStayingOnGroundSurface(): boolean;
        getShoulderEntityRight(): $CompoundTag;
        removeEntitiesOnShoulder(): void;
        startAutoSpinAttack(arg0: number, arg1: number, arg2: $ItemStack_): void;
        setLastDeathLocation(arg0: ($GlobalPos_) | undefined): void;
        getShoulderEntityLeft(): $CompoundTag;
        hasCorrectToolForDrops(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_): boolean;
        /**
         * @deprecated
         */
        hasCorrectToolForDrops(arg0: $BlockState_): boolean;
        setShoulderEntityLeft(arg0: $CompoundTag_): void;
        setShoulderEntityRight(arg0: $CompoundTag_): void;
        giveExperienceLevels(arg0: number): void;
        sable$getFrozenToSubLevel(): $UUID;
        sable$tickStopFreezing(): void;
        getEnderChestInventory(): $PlayerEnderChestContainer;
        causeFoodExhaustion(arg0: number): void;
        onEnchantmentPerformed(arg0: $ItemStack_, arg1: number): void;
        giveExperiencePoints(arg0: number): void;
        canUseGameMasterBlocks(): boolean;
        openMinecartCommandBlock(arg0: $BaseCommandBlock): void;
        resetCurrentImpulseContext(): void;
        entityInteractionRange(): number;
        setEntityOnShoulder(arg0: $CompoundTag_): boolean;
        getWardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        blockInteractionRange(): number;
        isSleepingLongEnough(): boolean;
        triggerRecipeCrafted(arg0: $RecipeHolder_<never>, arg1: $List_<$ItemStack_>): void;
        tryToStartFallFlying(): boolean;
        canInteractWithBlock(arg0: $BlockPos_, arg1: number): boolean;
        getCraftingGrid(): $InventoryKJS;
        canInteractWithEntity(arg0: $AABB_, arg1: number): boolean;
        canInteractWithEntity(arg0: $Entity, arg1: number): boolean;
        getLastDeathLocation(): ($GlobalPos) | undefined;
        getAttackStrengthScale(arg0: number): number;
        getXpNeededForNextLevel(): number;
        setReducedDebugInfo(arg0: boolean): void;
        getEnchantedDamage(arg0: $Entity, arg1: number, arg2: $DamageSource_): number;
        disableShield(): void;
        openCommandBlock(arg0: $CommandBlockEntity): void;
        hasContainerOpen(): boolean;
        sweepAttack(): void;
        openStructureBlock(arg0: $StructureBlockEntity): void;
        canHarmPlayer(arg0: $Player): boolean;
        getDigSpeed(arg0: $BlockState_, arg1: $BlockPos_): number;
        sendMerchantOffers(arg0: number, arg1: $MerchantOffers, arg2: number, arg3: number, arg4: boolean, arg5: boolean): void;
        openJigsawBlock(arg0: $JigsawBlockEntity): void;
        openItemGui(arg0: $ItemStack_, arg1: $InteractionHand_): void;
        awardRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        getSleepTimer(): number;
        awardRecipesByKey(arg0: $List_<$ResourceLocation_>): void;
        resetRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        openHorseInventory(arg0: $AbstractHorse, arg1: $Container): void;
        startSleepInBed(arg0: $BlockPos_): $Either<$Player$BedSleepingProblem, $Unit>;
        openTextEdit(arg0: $SignBlockEntity, arg1: boolean): void;
        /**
         * @deprecated
         */
        getDestroySpeed(arg0: $BlockState_): number;
        getEnchantmentSeed(): number;
        flightlib$get(): $Map<any, any>;
        stopFallFlying(): void;
        getFoodData(): $FoodData;
        refreshDisplayName(): void;
        sable$teleport(): void;
        getForcedPose(): $Pose;
        getSuffixes(): $Collection<$MutableComponent>;
        atl$getBaseClass(): $Class<any>;
        onUpdateAbilities(): void;
        mayUseItemAt(arg0: $BlockPos_, arg1: $Direction_, arg2: $ItemStack_): boolean;
        getInventory(): $InventoryKJS;
        getStages(): $Stages;
        getData(): $AttachedData<any>;
        flightlib$set(arg0: $Map_<any, any>): void;
        startFallFlying(): void;
        setForcedPose(arg0: $Pose_): void;
        isModelPartShown(arg0: $PlayerModelPart_): boolean;
        handler$ehd000$superbwarfare$shouldDismountInjection(arg0: $CallbackInfoReturnable<any>): void;
        handler$cfk000$fabric_entity_events_v1$injectElytraCheck(arg0: $CallbackInfoReturnable<any>): void;
        getInventory(): $Inventory;
        getAbilities(): $Abilities;
        isLocalPlayer(): boolean;
        getCooldowns(): $ItemCooldowns;
        resetAttackStrengthTicker(): void;
        displayClientMessage(arg0: $Component_, arg1: boolean): void;
        isReducedDebugInfo(): boolean;
        getGameProfile(): $GameProfile;
        isTextFilteringEnabled(): boolean;
        attack(arg0: $Entity): void;
        /**
         * Checks, whether the player is in Creative mode.
         */
        isCreative(): boolean;
        respawn(): void;
        handler$ehd000$superbwarfare$updatePostInjection(arg0: $CallbackInfo): void;
        handler$zdm000$openpartiesandclaims$onMayUseItemAt(arg0: $BlockPos_, arg1: $Direction_, arg2: $ItemStack_, arg3: $CallbackInfoReturnable<any>): void;
        wrapOperation$ipc000$axiom$tick_isSpectator(instance: $Player, original: $Operation_<any>): boolean;
        modifyReturnValue$cbi000$vista$modifyIsScoping(arg0: boolean): boolean;
        getScoreboard(): $Scoreboard;
        awardStat(arg0: $ResourceLocation_, arg1: number): void;
        awardStat(arg0: $ResourceLocation_): void;
        awardStat(arg0: $Stat_<never>, arg1: number): void;
        awardStat(arg0: $Stat_<never>): void;
        getLuck(): number;
        sable$freezeTo(arg0: $UUID_, arg1: $Vector3dc): void;
        updateIsUnderwater(): boolean;
        updatePlayerPose(): void;
        doCloseContainer(): void;
        closeMenu(): void;
        increaseScore(arg0: number): void;
        stopSleepInBed(arg0: boolean, arg1: boolean): void;
        wantsToStopRiding(): boolean;
        playNotifySound(arg0: $SoundEvent_, arg1: $SoundSource_, arg2: number, arg3: number): void;
        static createAttributes(): $AttributeSupplier$Builder;
        tryResetCurrentImpulseContext(): void;
        simulated$setCurrentTypewriter(arg0: $BlockPos_): void;
        getInventoryChangeListener(): $KubeJSInventoryListener;
        updateTutorialInventoryAction(arg0: $ItemStack_, arg1: $ItemStack_, arg2: $ClickAction_): void;
        simulated$getLaunchedPlunger(): $LaunchedPlungerEntity;
        simulated$getCurrentTypewriter(): $BlockPos;
        destroyVanishingCursedItems(): void;
        simulated$setLaunchedPlunger(arg0: $LaunchedPlungerEntity): void;
        getCurrentItemAttackStrengthDelay(): number;
        sable$getFrozenToSubLevelAnchor(): $Vector3dc;
        handler$ipc000$axiom$travel(movementInput: $Vec3_, ci: $CallbackInfo): void;
        handler$ipc000$axiom$getFlyingSpeed(cir: $CallbackInfoReturnable<any>): void;
        handler$ipc000$axiom$updatePlayerPose(ci: $CallbackInfo): void;
        redirect$hbk000$sable$fixRidingBoundingBox(arg0: $AABB_, arg1: $AABB_): $AABB;
        setIgnoreFallDamageFromCurrentImpulse(arg0: boolean): void;
        isIgnoringFallDamageFromCurrentImpulse(): boolean;
        canPlayerFitWithinBlocksAndEntitiesWhen(arg0: $Pose_): boolean;
        handler$emg000$railways$addModDataVersions(arg0: $CompoundTag_, arg1: $CallbackInfo): void;
        resetStat(arg0: $Stat_<never>): void;
        mayBuild(): boolean;
        setScore(arg0: number): void;
        getScore(): number;
        crit(arg0: $Entity): void;
        openMenu(arg0: $MenuProvider): $OptionalInt;
        magicCrit(arg0: $Entity): void;
        interactOn(arg0: $Entity, arg1: $InteractionHand_): $InteractionResult;
        setMainArm(arg0: $HumanoidArm_): void;
        canEat(arg0: boolean): boolean;
        freeAt(arg0: $BlockPos_): boolean;
        isHurt(): boolean;
        isScoping(): boolean;
        isFakePlayer(): boolean;
        isCloseEnough(arg0: $Entity, arg1: number): boolean;
        handler$fgf000$create_hypertube$createHypertube$mayFly(arg0: $CallbackInfoReturnable<any>): void;
        openMenu(arg0: $MenuProvider, arg1: $Consumer_<$RegistryFriendlyByteBuf>): $OptionalInt;
        openMenu(arg0: $MenuProvider, arg1: $BlockPos_): $OptionalInt;
        mayFly(): boolean;
        wrap(): $WeakReference<$Trackable>;
        startTracking(): void;
        getOpenInventory(): $AbstractContainerMenu;
        setSelectedSlot(index: number): void;
        sendInventoryUpdate(): void;
        boostElytraFlight(): void;
        addItemCooldown(item: $Item_, ticks: number): void;
        getSelectedSlot(): number;
        giveInHand(item: $ItemStack_): void;
        getMouseItem(): $ItemStack;
        setSaturation(saturation: number): void;
        addXPLevels(levels: number): void;
        setXpLevel(levels: number): void;
        getFoodLevel(): number;
        setFoodLevel(foodLevel: number): void;
        addExhaustion(exhaustion: number): void;
        getXpLevel(): number;
        isMiningBlock(): boolean;
        setMouseItem(item: $ItemStack_): void;
        getStats(): $PlayerStatsJS;
        addFood(hunger: number, saturation: number): void;
        getSaturation(): number;
        /**
         * Checks if the player is fake.
         */
        isFake(): this is $FakePlayer;
        give(item: $ItemStack_): void;
        addXP(xp: number): void;
        notify(builder: $NotificationToastData_): void;
        notify(title: $Component_, text: $Component_): void;
        getXp(): number;
        setXp(xp: number): void;
        sendData(channel: string, data: $CompoundTag_): void;
        sendData(channel: string): void;
        setItemStackMainHand(arg0: $ItemStack_): void;
        getItemStackMainHand(): $ItemStack;
        lastHurtByPlayerTime: number;
        autoSpinAttackItemStack: $ItemStack;
        lerpYRot: number;
        static DEFAULT_BASE_GRAVITY: number;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static ENTITY_COUNTER: $AtomicInteger;
        lerpYHeadRot: number;
        useItem: $ItemStack;
        yHeadRot: number;
        yCloakO: number;
        noPhysics: boolean;
        fallFlyTicks: number;
        autoSpinAttackDmg: number;
        yo: number;
        jumpTriggerTime: number;
        static DATA_LIVING_ENTITY_FLAGS: $EntityDataAccessor<number>;
        yBodyRotO: number;
        static FLAG_ONFIRE: number;
        simulated$currentTypeWriter: $BlockPos;
        sbw$beastKilled: boolean;
        removalReason: $Entity$RemovalReason;
        zza: number;
        passengers: $ImmutableList<$Entity>;
        rotOffs: number;
        swingingArm: $InteractionHand;
        static CRAFTING_SLOT_OFFSET: number;
        static ID_TAG: string;
        static WAKE_UP_DURATION: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        simulated$launchedPlunger: $LaunchedPlungerEntity;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        lastHurt: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        sbw$currentHitPart: $OBB$Part;
        lastDamageSource: $DamageSource;
        appliedScale: number;
        static STANDING_DIMENSIONS: $EntityDimensions;
        static DATA_PLAYER_MODE_CUSTOMISATION: $EntityDataAccessor<number>;
        yya: number;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        static DEFAULT_MODEL_CUSTOMIZATION: number;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        static SWIMMING_BB_HEIGHT: number;
        static DEFAULT_ENTITY_INTERACTION_RANGE: number;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        experienceLevel: number;
        hurtDir: number;
        static DEFAULT_BABY_SCALE: number;
        static ATTRIBUTES_FIELD: string;
        static PERSISTED_NBT_TAG: string;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        zCloak: number;
        lerpHeadSteps: number;
        static $assertionsDisabled: boolean;
        flyDist: number;
        currentImpulseImpactPos: $Vec3;
        brain: $Brain<never>;
        static PASSENGERS_TAG: string;
        stringUUID: string;
        xCloakO: number;
        wasOnFire: boolean;
        autoSpinAttackTicks: number;
        attackAnim: number;
        noActionTime: number;
        zOld: number;
        timeOffs: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static LIVING_ENTITY_FLAG_SPIN_ATTACK: number;
        wasTouchingWater: boolean;
        rotA: number;
        horizontalCollision: boolean;
        static ENDER_SLOT_OFFSET: number;
        firstTick: boolean;
        damageContainers: $Stack<$DamageContainer>;
        static ARMOR_SLOT_OFFSET: number;
        static SLEEP_DURATION: number;
        static HELD_ITEM_SLOT: number;
        yCloak: number;
        run: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        uuid: $UUID;
        xCloak: number;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        animStepO: number;
        lastHurtByPlayer: $Player;
        static BOARDING_COOLDOWN: number;
        static MAX_HEALTH: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        static DEFAULT_EYE_HEIGHT: number;
        enderChestInventory: $PlayerEnderChestContainer;
        static CROUCH_BB_HEIGHT: number;
        moveDist: number;
        enchantmentSeed: number;
        zCloakO: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        oRun: number;
        bob: number;
        experienceProgress: number;
        create_diesel_generators$turretPos: $BlockPos;
        totalExperience: number;
        xOld: number;
        wasInPowderSnow: boolean;
        containerMenu: $AbstractContainerMenu;
        hurtTime: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        useItemRemaining: number;
        entityData: $SynchedEntityData;
        static DEFAULT_MAIN_HAND: $HumanoidArm;
        foodData: $FoodData;
        static SLEEPING_DIMENSIONS: $EntityDimensions;
        deathTime: number;
        static DATA_PLAYER_MAIN_HAND: $EntityDataAccessor<number>;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        wasUnderwater: boolean;
        defaultFlySpeed: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DEFAULT_VEHICLE_ATTACHMENT: $Vec3;
        inventoryMenu: $InventoryMenu;
        inventory: $Inventory;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        static LIVING_ENTITY_FLAG_OFF_HAND: number;
        random: $RandomSource;
        static DATA_SHOULDER_LEFT: $EntityDataAccessor<$CompoundTag>;
        lerpSteps: number;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        minorHorizontalCollision: boolean;
        static LIVING_ENTITY_FLAG_IS_USING: number;
        lastDamageStamp: number;
        levelCallback: $EntityInLevelCallback;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        lerpX: number;
        lerpZ: number;
        lerpY: number;
        lerpXRot: number;
        fishing: $FishingHook;
        removeArrowTime: number;
        walkDistO: number;
        static SWIMMING_BB_WIDTH: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        animStep: number;
        yBodyRot: number;
        blocksBuilding: boolean;
        takeXpDelay: number;
        deathScore: number;
        static DEFAULT_BLOCK_INTERACTION_RANGE: number;
        oBob: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        invulnerableDuration: number;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        static DATA_SHOULDER_RIGHT: $EntityDataAccessor<$CompoundTag>;
        currentExplosionCause: $Entity;
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: number, arg3: $GameProfile);
        get prefixes(): $Collection<$MutableComponent>;
        get secondaryUseActive(): boolean;
        get stayingOnGroundSurface(): boolean;
        set entityOnShoulder(value: $CompoundTag_);
        get wardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        get sleepingLongEnough(): boolean;
        get craftingGrid(): $InventoryKJS;
        get xpNeededForNextLevel(): number;
        get sleepTimer(): number;
        get suffixes(): $Collection<$MutableComponent>;
        get stages(): $Stages;
        get data(): $AttachedData<any>;
        get abilities(): $Abilities;
        get localPlayer(): boolean;
        get cooldowns(): $ItemCooldowns;
        get gameProfile(): $GameProfile;
        get textFilteringEnabled(): boolean;
        get creative(): boolean;
        get scoreboard(): $Scoreboard;
        get luck(): number;
        get inventoryChangeListener(): $KubeJSInventoryListener;
        get currentItemAttackStrengthDelay(): number;
        set ignoreFallDamageFromCurrentImpulse(value: boolean);
        get ignoringFallDamageFromCurrentImpulse(): boolean;
        set mainArm(value: $HumanoidArm_);
        get hurt(): boolean;
        get scoping(): boolean;
        get fakePlayer(): boolean;
        get openInventory(): $AbstractContainerMenu;
        get miningBlock(): boolean;
        get stats(): $PlayerStatsJS;
        get fake(): boolean;
    }
}
