import { $LDLRegisterClient } from "@package/com/lowdragmc/lowdraglib2/registry/annotation";
import { $Codec } from "@package/com/mojang/serialization";
import { $MultiBufferSource_, $RenderType } from "@package/net/minecraft/client/renderer";
import { $Tag_, $CompoundTag, $CompoundTag_, $Tag } from "@package/net/minecraft/nbt";
import { $BakedModel, $ModelResourceLocation } from "@package/net/minecraft/client/resources/model";
import { $List, $Set } from "@package/java/util";
import { $ConfiguratorGroup, $Configurator } from "@package/com/lowdragmc/lowdraglib2/configurator/ui";
import { $RandomSource } from "@package/net/minecraft/util";
import { $Consumer_, $Supplier } from "@package/java/util/function";
import { $TriState } from "@package/net/neoforged/neoforge/common/util";
import { $ChunkRenderTypeSet } from "@package/net/neoforged/neoforge/client";
import { $HolderLookup$Provider, $BlockPos_, $Direction_ } from "@package/net/minecraft/core";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $IPersistedSerializable } from "@package/com/lowdragmc/lowdraglib2/syncdata";
import { $TextureAtlasSprite } from "@package/net/minecraft/client/renderer/texture";
import { $BlockAndTintGetter } from "@package/net/minecraft/world/level";
import { $ItemDisplayContext_, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $BakedQuad } from "@package/net/minecraft/client/renderer/block/model";
import { $Component } from "@package/net/minecraft/network/chat";
import { $AutoRegistry$Holder, $AutoRegistry$LDLibRegisterClient, $ILDLRegisterClient } from "@package/com/lowdragmc/lowdraglib2/registry";
import { $Scene } from "@package/com/lowdragmc/lowdraglib2/gui/ui/elements";
import { $IConfigurable, $IConfigurableHistory } from "@package/com/lowdragmc/lowdraglib2/configurator";
import { $ModelData } from "@package/net/neoforged/neoforge/client/model/data";
import { $ResourceLocation_, $ResourceLocation } from "@package/net/minecraft/resources";
import { $PoseStack } from "@package/com/mojang/blaze3d/vertex";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $Vec3_, $AABB } from "@package/net/minecraft/world/phys";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/com/lowdragmc/lowdraglib2/client/renderer" {
    export class $IRenderer$EmptyRenderer implements $IRenderer {
        copy(): $IRenderer;
        registerEvent(): void;
        clearCache(): void;
        render(arg0: $BlockEntity, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: number, arg5: number): void;
        getRenderTypes(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $BlockState_, arg3: $RandomSource, arg4: $ModelData): $ChunkRenderTypeSet;
        getRenderBoundingBox(arg0: $BlockEntity): $AABB;
        shouldRenderOffScreen(arg0: $BlockEntity): boolean;
        reBakeCustomQuadsOffset(): number;
        onPrepareTextureAtlas(arg0: $ResourceLocation_, arg1: $Consumer_<$ResourceLocation>): void;
        hasBlockEntityRenderer(arg0: $BlockEntity): boolean;
        shouldRender(arg0: $BlockEntity, arg1: $Vec3_): boolean;
        renderItem(arg0: $ItemStack_, arg1: $ItemDisplayContext_, arg2: boolean, arg3: $PoseStack, arg4: $MultiBufferSource_, arg5: number, arg6: number, arg7: $BakedModel): void;
        isGui3d(): boolean;
        getViewDistance(): number;
        useAO(arg0: $BlockState_, arg1: $ModelData, arg2: $RenderType): $TriState;
        useAO(): $TriState;
        renderModel(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $BlockState_, arg3: $Direction_, arg4: $RandomSource, arg5: $ModelData, arg6: $RenderType): $List<$BakedQuad>;
        useBlockLight(arg0: $ItemStack_): boolean;
        createPreview(arg0: $ConfiguratorGroup): void;
        buildConfigurator(arg0: $ConfiguratorGroup): void;
        getParticleTexture(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $ModelData): $TextureAtlasSprite;
        createPreviewScene(): $Scene;
        onAdditionalModel(arg0: $Consumer_<$ModelResourceLocation>): void;
        serializeWrapper(): $CompoundTag;
        reBakeCustomQuads(): boolean;
        name(): string;
        group(): string;
        registryName(): $ResourceLocation;
        getRegistry(): $AutoRegistry$LDLibRegisterClient<$IRenderer, $Supplier<$IRenderer>>;
        getRegisterUIClient(): $LDLRegisterClient;
        getRegistryHolderOptional(): ($AutoRegistry$Holder<$LDLRegisterClient, $IRenderer, $Supplier<$IRenderer>>) | undefined;
        getChatComponent(): $Component;
        getTranslateKey(): string;
        isLDLRegister(): boolean;
        getRegistryHolder(): $AutoRegistry$Holder<$LDLRegisterClient, $IRenderer, $Supplier<$IRenderer>>;
        createHistoryRecorder(): $IConfigurableHistory;
        getConfigurableName(): string;
        createDirectConfigurator(): $Configurator;
        serializeAdditionalNBT(arg0: $HolderLookup$Provider): $Tag;
        deserializeAdditionalNBT(arg0: $Tag_, arg1: $HolderLookup$Provider): void;
        deserializeNBT(arg0: $HolderLookup$Provider, arg1: $CompoundTag_): void;
        beforeSerialize(): void;
        writeToBuff(arg0: $ByteBuf): void;
        afterSerialize(): void;
        readFromBuff(arg0: $ByteBuf): void;
        afterDeserialize(): void;
        beforeDeserialize(): void;
        serializeNBT(arg0: $HolderLookup$Provider): $IRenderer;
        constructor();
        get gui3d(): boolean;
        get viewDistance(): number;
        get registry(): $AutoRegistry$LDLibRegisterClient<$IRenderer, $Supplier<$IRenderer>>;
        get registerUIClient(): $LDLRegisterClient;
        get registryHolderOptional(): ($AutoRegistry$Holder<$LDLRegisterClient, $IRenderer, $Supplier<$IRenderer>>) | undefined;
        get chatComponent(): $Component;
        get translateKey(): string;
        get LDLRegister(): boolean;
        get registryHolder(): $AutoRegistry$Holder<$LDLRegisterClient, $IRenderer, $Supplier<$IRenderer>>;
        get configurableName(): string;
    }
    export class $IRenderer {
        static createCodec(): $Codec<$IRenderer>;
        static deserializeWrapper(arg0: $Tag_): $IRenderer;
        static CODEC: $Codec<$IRenderer>;
        static EVENT_REGISTERS: $Set<$IRenderer>;
        static EMPTY: $IRenderer$EmptyRenderer;
    }
    export interface $IRenderer extends $ILDLRegisterClient<$IRenderer, $Supplier<$IRenderer>>, $IConfigurable, $IPersistedSerializable {
        registerEvent(): void;
        copy(): $IRenderer;
        clearCache(): void;
        render(arg0: $BlockEntity, arg1: number, arg2: $PoseStack, arg3: $MultiBufferSource_, arg4: number, arg5: number): void;
        getRenderTypes(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $BlockState_, arg3: $RandomSource, arg4: $ModelData): $ChunkRenderTypeSet;
        getRenderBoundingBox(arg0: $BlockEntity): $AABB;
        shouldRenderOffScreen(arg0: $BlockEntity): boolean;
        reBakeCustomQuadsOffset(): number;
        onPrepareTextureAtlas(arg0: $ResourceLocation_, arg1: $Consumer_<$ResourceLocation>): void;
        hasBlockEntityRenderer(arg0: $BlockEntity): boolean;
        shouldRender(arg0: $BlockEntity, arg1: $Vec3_): boolean;
        renderItem(arg0: $ItemStack_, arg1: $ItemDisplayContext_, arg2: boolean, arg3: $PoseStack, arg4: $MultiBufferSource_, arg5: number, arg6: number, arg7: $BakedModel): void;
        isGui3d(): boolean;
        getViewDistance(): number;
        useAO(arg0: $BlockState_, arg1: $ModelData, arg2: $RenderType): $TriState;
        useAO(): $TriState;
        renderModel(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $BlockState_, arg3: $Direction_, arg4: $RandomSource, arg5: $ModelData, arg6: $RenderType): $List<$BakedQuad>;
        useBlockLight(arg0: $ItemStack_): boolean;
        createPreview(arg0: $ConfiguratorGroup): void;
        buildConfigurator(arg0: $ConfiguratorGroup): void;
        getParticleTexture(arg0: $BlockAndTintGetter, arg1: $BlockPos_, arg2: $ModelData): $TextureAtlasSprite;
        createPreviewScene(): $Scene;
        onAdditionalModel(arg0: $Consumer_<$ModelResourceLocation>): void;
        serializeWrapper(): $CompoundTag;
        reBakeCustomQuads(): boolean;
        get gui3d(): boolean;
        get viewDistance(): number;
    }
}
